//
// <auto-generated>
// Invoice Ninja API Models - Auto-generated from OpenAPI specification
//
// Generated by: ApiGenerator
// Source: specs/invoiceninja.yaml
// API: Invoice Ninja API Reference.
// Version: 5.12.55
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
// </auto-generated>
//
using System.Text.Json.Serialization;

#nullable enable

namespace Apigen.InvoiceNinja.Client;

/// <summary>
/// Standard API response wrapper
/// </summary>
public partial class ApiResponse<T>
{
  [JsonPropertyName("data")]
  public T Data { get; set; } = default!;
  [JsonPropertyName("meta")]
  public Apigen.InvoiceNinja.Models.Meta? Meta { get; set; }
}
