//
// <auto-generated>
// Invoice Ninja API Models - Auto-generated from OpenAPI specification
//
// Generated by: ApiGenerator
// Source: specs/invoiceninja.yaml
// API: Invoice Ninja API Reference.
// Version: 5.12.55
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
// </auto-generated>
//
using System.Text.Json;
using System.Threading;
using System.Threading.Tasks;
using Apigen.InvoiceNinja.Models;

#nullable enable

namespace Apigen.InvoiceNinja.Client;

/// <summary>
/// Interface for activities operations
/// </summary>
public partial interface IActivitiesClient
{
  /// <summary>
  /// Returns a list of activities
  /// Operation: GET /api/v1/activities
  /// </summary>
  Task<ApiResponse<Activity[]>> ListAsync(GetActivitiesRequest? request = null, CancellationToken cancellationToken = default);

  /// <summary>
  /// Returns a PDF for the given activity
  /// Operation: GET /api/v1/activities/download_entity/{activity_id}
  /// </summary>
  Task<Stream> GetActivityHistoricalEntityPdfAsync(string activityId, GetActivityHistoricalEntityPdfRequest? request = null, CancellationToken cancellationToken = default);

  /// <summary>
  /// Entity activity
  /// Operation: POST /api/v1/activities/entity
  /// </summary>
  Task PostActivitiesEntityAsync(CancellationToken cancellationToken = default);

  /// <summary>
  /// Activity note
  /// Operation: POST /api/v1/activities/notes
  /// </summary>
  Task PostActivitiesNotesAsync(CancellationToken cancellationToken = default);

}
