//
// <auto-generated>
// Invoice Ninja API Models - Auto-generated from OpenAPI specification
//
// Generated by: ApiGenerator
// Source: specs/invoiceninja.yaml
// API: Invoice Ninja API Reference.
// Version: 5.12.55
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
// </auto-generated>
//
using System.Text.Json;
using System.Threading;
using System.Threading.Tasks;
using Apigen.InvoiceNinja.Models;

#nullable enable

namespace Apigen.InvoiceNinja.Client;

/// <summary>
/// Interface for auth operations
/// </summary>
public partial interface IAuthClient
{
  /// <summary>
  /// Login
  /// Operation: POST /api/v1/login
  /// </summary>
  Task<ApiResponse<CompanyUser[]>> loginAsync(Apigen.InvoiceNinja.Models.PostLoginRequest postLoginRequest, LoginRequest? request = null, CancellationToken cancellationToken = default);

  /// <summary>
  /// Passkey login options
  /// Operation: POST /api/v1/passkeys/login/options
  /// </summary>
  Task PostPasskeyLoginOptionsAsync(Apigen.InvoiceNinja.Models.PostPasskeyLoginOptionsRequest postPasskeyLoginOptionsRequest, CancellationToken cancellationToken = default);

  /// <summary>
  /// List passkeys
  /// Operation: GET /api/v1/settings/passkeys
  /// </summary>
  Task GetSettingsPasskeysAsync(CancellationToken cancellationToken = default);

  /// <summary>
  /// Create passkey
  /// Operation: POST /api/v1/settings/passkeys
  /// </summary>
  Task PostSettingsPasskeysAsync(Apigen.InvoiceNinja.Models.PostSettingsPasskeysRequest postSettingsPasskeysRequest, CancellationToken cancellationToken = default);

  /// <summary>
  /// Passkey registration options
  /// Operation: POST /api/v1/settings/passkeys/options
  /// </summary>
  Task PostSettingsPasskeysOptionsAsync(CancellationToken cancellationToken = default);

  /// <summary>
  /// Delete passkey
  /// Operation: DELETE /api/v1/settings/passkeys/{passkey}
  /// </summary>
  Task DeleteSettingsPasskeyAsync(string passkey, CancellationToken cancellationToken = default);

}
