//
// <auto-generated>
// Invoice Ninja API Models - Auto-generated from OpenAPI specification
//
// Generated by: ApiGenerator
// Source: specs/invoiceninja.yaml
// API: Invoice Ninja API Reference.
// Version: 5.12.55
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
// </auto-generated>
//
using System.Text.Json;
using System.Threading;
using System.Threading.Tasks;
using Apigen.InvoiceNinja.Models;

#nullable enable

namespace Apigen.InvoiceNinja.Client;

/// <summary>
/// Interface for company_gateways operations
/// </summary>
public partial interface ICompanyGatewaysClient
{
  /// <summary>
  /// Gets a list of company_gateways
  /// Operation: GET /api/v1/company_gateways
  /// </summary>
  Task<ApiResponse<CompanyGateway[]>> ListAsync(GetCompanyGatewaysRequest? request = null, CancellationToken cancellationToken = default);

  /// <summary>
  /// Adds a CompanyGateway
  /// Operation: POST /api/v1/company_gateways
  /// </summary>
  Task<ApiResponse<CompanyGateway>> CreateAsync(StoreCompanyGatewayRequest? request = null, CancellationToken cancellationToken = default);

  /// <summary>
  /// Gets a new blank CompanyGateway object
  /// Operation: GET /api/v1/company_gateways/create
  /// </summary>
  Task<ApiResponse<CompanyGateway>> GetCompanyGatewaysCreateAsync(GetCompanyGatewaysCreateRequest? request = null, CancellationToken cancellationToken = default);

  /// <summary>
  /// Shows an CompanyGateway
  /// Operation: GET /api/v1/company_gateways/{id}
  /// </summary>
  Task<ApiResponse<CompanyGateway>> GetAsync(string id, ShowCompanyGatewayRequest? request = null, CancellationToken cancellationToken = default);

  /// <summary>
  /// Updates an CompanyGateway
  /// Operation: PUT /api/v1/company_gateways/{id}
  /// </summary>
  Task<ApiResponse<CompanyGateway>> UpdateAsync(string id, UpdateCompanyGatewayRequest? request = null, CancellationToken cancellationToken = default);

  /// <summary>
  /// Deletes a CompanyGateway
  /// Operation: DELETE /api/v1/company_gateways/{id}
  /// </summary>
  Task DeleteAsync(string id, DeleteCompanyGatewayRequest? request = null, CancellationToken cancellationToken = default);

  /// <summary>
  /// Shows an CompanyGateway for editting
  /// Operation: GET /api/v1/company_gateways/{id}/edit
  /// </summary>
  Task<ApiResponse<CompanyGateway>> EditAsync(string id, EditCompanyGatewayRequest? request = null, CancellationToken cancellationToken = default);

  /// <summary>
  /// Performs bulk actions on an array of company_gateways
  /// Operation: POST /api/v1/company_gateways/bulk
  /// </summary>
  Task<ApiResponse<CompanyGateway>> BulkAsync(List<int> body, BulkCompanyGatewaysRequest? request = null, CancellationToken cancellationToken = default);

}
