//
// <auto-generated>
// Invoice Ninja API Models - Auto-generated from OpenAPI specification
//
// Generated by: ApiGenerator
// Source: specs/invoiceninja.yaml
// API: Invoice Ninja API Reference.
// Version: 5.12.55
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
// </auto-generated>
//
using System.Text.Json;
using System.Threading;
using System.Threading.Tasks;
using Apigen.InvoiceNinja.Models;

#nullable enable

namespace Apigen.InvoiceNinja.Client;

/// <summary>
/// Interface for company_user operations
/// </summary>
public partial interface ICompanyUserClient
{
  /// <summary>
  /// Update a company user record
  /// Operation: POST /api/v1/company_users
  /// </summary>
  Task<ApiResponse<CompanyUser>> UpdateAsync(CancellationToken cancellationToken = default);

}
