//
// <auto-generated>
// Invoice Ninja API Models - Auto-generated from OpenAPI specification
//
// Generated by: ApiGenerator
// Source: specs/invoiceninja.yaml
// API: Invoice Ninja API Reference.
// Version: 5.12.55
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
// </auto-generated>
//
using System.Text.Json;
using System.Threading;
using System.Threading.Tasks;
using Apigen.InvoiceNinja.Models;

#nullable enable

namespace Apigen.InvoiceNinja.Client;

/// <summary>
/// Interface for credits operations
/// </summary>
public partial interface ICreditsClient
{
  /// <summary>
  /// List credits
  /// Operation: GET /api/v1/credits
  /// </summary>
  Task<ApiResponse<Credit[]>> ListAsync(GetCreditsRequest? request = null, CancellationToken cancellationToken = default);

  /// <summary>
  /// Create credit
  /// Operation: POST /api/v1/credits
  /// </summary>
  Task<ApiResponse<Credit>> CreateAsync(Apigen.InvoiceNinja.Models.CreditRequest creditRequest, StoreCreditRequest? request = null, CancellationToken cancellationToken = default);

  /// <summary>
  /// Show credit
  /// Operation: GET /api/v1/credits/{id}
  /// </summary>
  Task<ApiResponse<Credit>> GetAsync(string id, ShowCreditRequest? request = null, CancellationToken cancellationToken = default);

  /// <summary>
  /// Delete credit
  /// Operation: DELETE /api/v1/credits/{id}
  /// </summary>
  Task DeleteAsync(string id, DeleteCreditRequest? request = null, CancellationToken cancellationToken = default);

  /// <summary>
  /// Edit credit
  /// Operation: GET /api/v1/credits/{id}/edit
  /// </summary>
  Task<ApiResponse<Invoice>> EditAsync(string id, EditCreditRequest? request = null, CancellationToken cancellationToken = default);

  /// <summary>
  /// Blank credit
  /// Operation: GET /api/v1/credits/create
  /// </summary>
  Task<ApiResponse<Credit>> GetCreditsCreateAsync(GetCreditsCreateRequest? request = null, CancellationToken cancellationToken = default);

  /// <summary>
  /// Bulk credit actions
  /// Operation: POST /api/v1/credits/bulk
  /// </summary>
  Task BulkAsync(List<string> body, BulkCreditsRequest? request = null, CancellationToken cancellationToken = default);

  /// <summary>
  /// Upload a credit document
  /// Operation: POST /api/v1/credits/{id}/upload
  /// </summary>
  Task<ApiResponse<Credit>> UploadAsync(string id, Apigen.InvoiceNinja.Models.UploadCreditsRequest uploadCreditsRequest, UploadCreditsRequest? request = null, CancellationToken cancellationToken = default);

}
