//
// <auto-generated>
// Invoice Ninja API Models - Auto-generated from OpenAPI specification
//
// Generated by: ApiGenerator
// Source: specs/invoiceninja.yaml
// API: Invoice Ninja API Reference.
// Version: 5.12.55
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
// </auto-generated>
//
using System.Text.Json;
using System.Threading;
using System.Threading.Tasks;
using Apigen.InvoiceNinja.Models;

#nullable enable

namespace Apigen.InvoiceNinja.Client;

/// <summary>
/// Interface for imports operations
/// </summary>
public partial interface IImportsClient
{
  /// <summary>
  /// Pre Import CSV data
  /// Operation: POST /api/v1/preimport
  /// </summary>
  Task<ApiResponse<JsonElement>> PreimportAsync(Apigen.InvoiceNinja.Models.PreImportRequest preImportRequest, PreimportRequest? request = null, CancellationToken cancellationToken = default);

  /// <summary>
  /// Import CSV data
  /// Operation: POST /api/v1/import
  /// </summary>
  Task<ApiResponse<JsonElement>> PostAsync(Apigen.InvoiceNinja.Models.PostImportRequest postImportRequest, PostImportRequest? request = null, CancellationToken cancellationToken = default);

}
