//
// <auto-generated>
// Invoice Ninja API Models - Auto-generated from OpenAPI specification
//
// Generated by: ApiGenerator
// Source: specs/invoiceninja.yaml
// API: Invoice Ninja API Reference.
// Version: 5.12.55
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
// </auto-generated>
//
using System.Text.Json;
using System.Threading;
using System.Threading.Tasks;
using Apigen.InvoiceNinja.Models;

#nullable enable

namespace Apigen.InvoiceNinja.Client;

/// <summary>
/// Interface for ping operations
/// </summary>
public partial interface IPingClient
{
  /// <summary>
  /// Attempts to ping the API
  /// Operation: GET /api/v1/ping
  /// </summary>
  Task GetAsync(CancellationToken cancellationToken = default);

  /// <summary>
  /// Returns the last error
  /// Operation: GET /api/v1/last_error
  /// </summary>
  Task GetLastErrorAsync(CancellationToken cancellationToken = default);

}
