//
// <auto-generated>
// Invoice Ninja API Models - Auto-generated from OpenAPI specification
//
// Generated by: ApiGenerator
// Source: specs/invoiceninja.yaml
// API: Invoice Ninja API Reference.
// Version: 5.12.55
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
// </auto-generated>
//
using System.Text.Json;
using System.Threading;
using System.Threading.Tasks;
using Apigen.InvoiceNinja.Models;

#nullable enable

namespace Apigen.InvoiceNinja.Client;

/// <summary>
/// Interface for postmark operations
/// </summary>
public partial interface IPostmarkClient
{
  /// <summary>
  /// Processing webhooks from Apple for in app purchases
  /// Operation: POST /api/v1/apple/confirm_purchase
  /// </summary>
  Task ConfirmApplePurchaseAsync(ConfirmApplePurchaseRequest? request = null, CancellationToken cancellationToken = default);

  /// <summary>
  /// Processing event webhooks from Apple for in purchase / subscription status update
  /// Operation: POST /api/v1/apple/process_webhook
  /// </summary>
  Task ProcessAppleWebhookAsync(ProcessAppleWebhookRequest? request = null, CancellationToken cancellationToken = default);

  /// <summary>
  /// Processing webhooks from PostMark
  /// Operation: POST /api/v1/postmark_webhook
  /// </summary>
  Task<ApiResponse<Credit>> WebhookAsync(PostmarkWebhookRequest? request = null, CancellationToken cancellationToken = default);

}
