//
// <auto-generated>
// Invoice Ninja API Models - Auto-generated from OpenAPI specification
//
// Generated by: ApiGenerator
// Source: specs/invoiceninja.yaml
// API: Invoice Ninja API Reference.
// Version: 5.12.55
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
// </auto-generated>
//
using System.Text.Json;
using System.Threading;
using System.Threading.Tasks;
using Apigen.InvoiceNinja.Models;

#nullable enable

namespace Apigen.InvoiceNinja.Client;

/// <summary>
/// Interface for preview operations
/// </summary>
public partial interface IPreviewClient
{
  /// <summary>
  /// Returns a pdf preview
  /// Operation: POST /api/v1/preview
  /// </summary>
  Task CreateAsync(CancellationToken cancellationToken = default);

  /// <summary>
  /// Returns a pdf preview for purchase order
  /// Operation: POST /api/v1/preview/purchase_order
  /// </summary>
  Task GetPreviewPurchaseOrderAsync(CancellationToken cancellationToken = default);

}
