//
// <auto-generated>
// Invoice Ninja API Models - Auto-generated from OpenAPI specification
//
// Generated by: ApiGenerator
// Source: specs/invoiceninja.yaml
// API: Invoice Ninja API Reference.
// Version: 5.12.55
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
// </auto-generated>
//
using System.Text.Json;
using System.Threading;
using System.Threading.Tasks;
using Apigen.InvoiceNinja.Models;

#nullable enable

namespace Apigen.InvoiceNinja.Client;

/// <summary>
/// Interface for quotes operations
/// </summary>
public partial interface IQuotesClient
{
  /// <summary>
  /// Download quote PDF
  /// Operation: GET /api/v1/credit/{invitation_key}/download
  /// </summary>
  Task<Stream> DownloadCreditAsync(string invitationKey, DownloadCreditRequest? request = null, CancellationToken cancellationToken = default);

  /// <summary>
  /// List quotes
  /// Operation: GET /api/v1/quotes
  /// </summary>
  Task<ApiResponse<Quote[]>> ListAsync(GetQuotesRequest? request = null, CancellationToken cancellationToken = default);

  /// <summary>
  /// Create quote
  /// Operation: POST /api/v1/quotes
  /// </summary>
  Task<ApiResponse<Quote>> CreateAsync(Apigen.InvoiceNinja.Models.QuoteRequest quoteRequest, StoreQuoteRequest? request = null, CancellationToken cancellationToken = default);

  /// <summary>
  /// Show quote
  /// Operation: GET /api/v1/quotes/{id}
  /// </summary>
  Task<ApiResponse<Quote>> GetAsync(string id, ShowQuoteRequest? request = null, CancellationToken cancellationToken = default);

  /// <summary>
  /// Update quote
  /// Operation: PUT /api/v1/quotes/{id}
  /// </summary>
  Task<ApiResponse<Quote>> UpdateAsync(string id, Apigen.InvoiceNinja.Models.QuoteRequest quoteRequest, UpdateQuoteRequest? request = null, CancellationToken cancellationToken = default);

  /// <summary>
  /// Delete quote
  /// Operation: DELETE /api/v1/quotes/{id}
  /// </summary>
  Task DeleteAsync(string id, DeleteQuoteRequest? request = null, CancellationToken cancellationToken = default);

  /// <summary>
  /// Edit quote
  /// Operation: GET /api/v1/quotes/{id}/edit
  /// </summary>
  Task<ApiResponse<Quote>> EditAsync(string id, EditQuoteRequest? request = null, CancellationToken cancellationToken = default);

  /// <summary>
  /// Blank quote
  /// Operation: GET /api/v1/quotes/create
  /// </summary>
  Task<ApiResponse<Quote>> GetQuotesCreateAsync(GetQuotesCreateRequest? request = null, CancellationToken cancellationToken = default);

  /// <summary>
  /// Bulk quote actions
  /// Operation: POST /api/v1/quotes/bulk
  /// </summary>
  Task<ApiResponse<Quote>> BulkAsync(Apigen.InvoiceNinja.Models.BulkQuotesRequest bulkQuotesRequest, BulkQuotesRequest? request = null, CancellationToken cancellationToken = default);

  /// <summary>
  /// Performs a custom action on an Quote
  /// Operation: GET /api/v1/quotes/{id}/{action}
  /// </summary>
  Task<ApiResponse<Quote>> ActionAsync(string id, string action, ActionQuoteRequest? request = null, CancellationToken cancellationToken = default);

  /// <summary>
  /// Download quote PDF
  /// Operation: GET /api/v1/quote/{invitation_key}/download
  /// </summary>
  Task<Stream> DownloadAsync(string invitationKey, DownloadQuoteRequest? request = null, CancellationToken cancellationToken = default);

  /// <summary>
  /// Upload a quote document
  /// Operation: POST /api/v1/quotes/{id}/upload
  /// </summary>
  Task<ApiResponse<Quote>> UploadAsync(string id, Apigen.InvoiceNinja.Models.UploadQuoteRequest uploadQuoteRequest, UploadQuoteRequest? request = null, CancellationToken cancellationToken = default);

}
