//
// <auto-generated>
// Invoice Ninja API Models - Auto-generated from OpenAPI specification
//
// Generated by: ApiGenerator
// Source: specs/invoiceninja.yaml
// API: Invoice Ninja API Reference.
// Version: 5.12.55
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
// </auto-generated>
//
using System.Text.Json;
using System.Threading;
using System.Threading.Tasks;
using Apigen.InvoiceNinja.Models;

#nullable enable

namespace Apigen.InvoiceNinja.Client;

/// <summary>
/// Interface for recurring_expenses operations
/// </summary>
public partial interface IRecurringExpensesClient
{
  /// <summary>
  /// Gets a list of recurring_expenses
  /// Operation: GET /api/v1/recurring_expenses
  /// </summary>
  Task<ApiResponse<RecurringExpense[]>> ListAsync(GetRecurringExpensesRequest? request = null, CancellationToken cancellationToken = default);

  /// <summary>
  /// Adds a recurring expense
  /// Operation: POST /api/v1/recurring_expenses
  /// </summary>
  Task<ApiResponse<RecurringExpense>> CreateAsync(StoreRecurringExpenseRequest? request = null, CancellationToken cancellationToken = default);

  /// <summary>
  /// Shows a recurring expense
  /// Operation: GET /api/v1/recurring_expenses/{id}
  /// </summary>
  Task<ApiResponse<RecurringExpense>> GetAsync(string id, ShowRecurringExpenseRequest? request = null, CancellationToken cancellationToken = default);

  /// <summary>
  /// Updates a recurring expense
  /// Operation: PUT /api/v1/recurring_expenses/{id}
  /// </summary>
  Task<ApiResponse<RecurringExpense>> UpdateAsync(string id, UpdateRecurringExpenseRequest? request = null, CancellationToken cancellationToken = default);

  /// <summary>
  /// Deletes a recurring expense
  /// Operation: DELETE /api/v1/recurring_expenses/{id}
  /// </summary>
  Task DeleteAsync(string id, DeleteRecurringExpenseRequest? request = null, CancellationToken cancellationToken = default);

  /// <summary>
  /// Shows a recurring expense for editting
  /// Operation: GET /api/v1/recurring_expenses/{id}/edit
  /// </summary>
  Task<ApiResponse<RecurringExpense>> EditAsync(string id, EditRecurringExpenseRequest? request = null, CancellationToken cancellationToken = default);

  /// <summary>
  /// Gets a new blank recurring expense object
  /// Operation: GET /api/v1/recurring_expenses/create
  /// </summary>
  Task<ApiResponse<RecurringExpense>> GetRecurringExpensesCreateAsync(GetRecurringExpensesCreateRequest? request = null, CancellationToken cancellationToken = default);

  /// <summary>
  /// Performs bulk actions on an array of recurring_expenses
  /// Operation: POST /api/v1/recurring_expenses/bulk
  /// </summary>
  Task<ApiResponse<RecurringExpense>> BulkAsync(List<int> body, BulkRecurringExpensesRequest? request = null, CancellationToken cancellationToken = default);

}
