//
// <auto-generated>
// Invoice Ninja API Models - Auto-generated from OpenAPI specification
//
// Generated by: ApiGenerator
// Source: specs/invoiceninja.yaml
// API: Invoice Ninja API Reference.
// Version: 5.12.55
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
// </auto-generated>
//
using System.Text.Json;
using System.Threading;
using System.Threading.Tasks;
using Apigen.InvoiceNinja.Models;

#nullable enable

namespace Apigen.InvoiceNinja.Client;

/// <summary>
/// Interface for reports operations
/// </summary>
public partial interface IReportsClient
{
  /// <summary>
  /// Contact reports
  /// Operation: POST /api/v1/reports/contacts
  /// </summary>
  Task GetContactAsync(Apigen.InvoiceNinja.Models.GenericReportSchema genericReportSchema, GetContactReportRequest? request = null, CancellationToken cancellationToken = default);

  /// <summary>
  /// Client reports
  /// Operation: POST /api/v1/reports/clients
  /// </summary>
  Task GetClientAsync(Apigen.InvoiceNinja.Models.GenericReportSchema genericReportSchema, GetClientReportRequest? request = null, CancellationToken cancellationToken = default);

  /// <summary>
  /// Credit reports
  /// Operation: POST /api/v1/reports/credits
  /// </summary>
  Task GetCreditAsync(Apigen.InvoiceNinja.Models.GenericReportSchema genericReportSchema, CancellationToken cancellationToken = default);

  /// <summary>
  /// Document reports
  /// Operation: POST /api/v1/reports/documents
  /// </summary>
  Task GetDocumentAsync(Apigen.InvoiceNinja.Models.GenericReportSchema genericReportSchema, GetDocumentReportRequest? request = null, CancellationToken cancellationToken = default);

  /// <summary>
  /// Expense reports
  /// Operation: POST /api/v1/reports/expenses
  /// </summary>
  Task GetExpenseAsync(Apigen.InvoiceNinja.Models.GenericReportSchema genericReportSchema, CancellationToken cancellationToken = default);

  /// <summary>
  /// Invoice item reports
  /// Operation: POST /api/v1/reports/invoice_items
  /// </summary>
  Task GetInvoiceItemAsync(Apigen.InvoiceNinja.Models.GenericReportSchema genericReportSchema, GetInvoiceItemReportRequest? request = null, CancellationToken cancellationToken = default);

  /// <summary>
  /// Invoice reports
  /// Operation: POST /api/v1/reports/invoices
  /// </summary>
  Task GetInvoiceAsync(Apigen.InvoiceNinja.Models.GenericReportSchema genericReportSchema, GetInvoiceReportRequest? request = null, CancellationToken cancellationToken = default);

  /// <summary>
  /// Payment reports
  /// Operation: POST /api/v1/reports/payments
  /// </summary>
  Task GetPaymentAsync(Apigen.InvoiceNinja.Models.GenericReportSchema genericReportSchema, GetPaymentReportRequest? request = null, CancellationToken cancellationToken = default);

  /// <summary>
  /// Product reports
  /// Operation: POST /api/v1/reports/products
  /// </summary>
  Task GetProductAsync(Apigen.InvoiceNinja.Models.GenericReportSchema genericReportSchema, GetProductReportRequest? request = null, CancellationToken cancellationToken = default);

  /// <summary>
  /// Product Salesreports
  /// Operation: POST /api/v1/reports/product_sales
  /// </summary>
  Task GetProductSalesAsync(Apigen.InvoiceNinja.Models.GenericReportSchema genericReportSchema, GetProductSalesReportRequest? request = null, CancellationToken cancellationToken = default);

  /// <summary>
  /// Profit loss reports
  /// Operation: POST /api/v1/reports/profitloss
  /// </summary>
  Task GetProfitLossAsync(Apigen.InvoiceNinja.Models.GenericReportSchema genericReportSchema, GetProfitLossReportRequest? request = null, CancellationToken cancellationToken = default);

  /// <summary>
  /// Quote item reports
  /// Operation: POST /api/v1/reports/quote_items
  /// </summary>
  Task GetQuoteItemAsync(Apigen.InvoiceNinja.Models.GenericReportSchema genericReportSchema, GetQuoteItemReportRequest? request = null, CancellationToken cancellationToken = default);

  /// <summary>
  /// Quote reports
  /// Operation: POST /api/v1/reports/quotes
  /// </summary>
  Task GetQuoteAsync(Apigen.InvoiceNinja.Models.GenericReportSchema genericReportSchema, GetQuoteReportRequest? request = null, CancellationToken cancellationToken = default);

  /// <summary>
  /// Recurring Invoice reports
  /// Operation: POST /api/v1/reports/recurring_invoices
  /// </summary>
  Task GetRecurringInvoiceAsync(Apigen.InvoiceNinja.Models.GenericReportSchema genericReportSchema, GetRecurringInvoiceReportRequest? request = null, CancellationToken cancellationToken = default);

  /// <summary>
  /// Task reports
  /// Operation: POST /api/v1/reports/tasks
  /// </summary>
  Task GetTaskAsync(Apigen.InvoiceNinja.Models.GenericReportSchema genericReportSchema, GetTaskReportRequest? request = null, CancellationToken cancellationToken = default);

  /// <summary>
  /// Activity reports
  /// Operation: POST /api/v1/reports/activities
  /// </summary>
  Task GetActivityAsync(Apigen.InvoiceNinja.Models.GenericReportSchema genericReportSchema, CancellationToken cancellationToken = default);

  /// <summary>
  /// Client contact reports
  /// Operation: POST /api/v1/reports/client_contacts
  /// </summary>
  Task GetClientContactAsync(Apigen.InvoiceNinja.Models.GenericReportSchema genericReportSchema, CancellationToken cancellationToken = default);

  /// <summary>
  /// AR detail report
  /// Operation: POST /api/v1/reports/ar_detail_report
  /// </summary>
  Task GetARDetailAsync(Apigen.InvoiceNinja.Models.GenericReportSchema genericReportSchema, CancellationToken cancellationToken = default);

  /// <summary>
  /// AR summary report
  /// Operation: POST /api/v1/reports/ar_summary_report
  /// </summary>
  Task GetARSummaryAsync(Apigen.InvoiceNinja.Models.GenericReportSchema genericReportSchema, CancellationToken cancellationToken = default);

  /// <summary>
  /// Client balance report
  /// Operation: POST /api/v1/reports/client_balance_report
  /// </summary>
  Task GetClientBalanceAsync(Apigen.InvoiceNinja.Models.GenericReportSchema genericReportSchema, CancellationToken cancellationToken = default);

  /// <summary>
  /// Client sales report
  /// Operation: POST /api/v1/reports/client_sales_report
  /// </summary>
  Task GetClientSalesAsync(Apigen.InvoiceNinja.Models.GenericReportSchema genericReportSchema, CancellationToken cancellationToken = default);

  /// <summary>
  /// Tax summary report
  /// Operation: POST /api/v1/reports/tax_summary_report
  /// </summary>
  Task GetTaxSummaryAsync(Apigen.InvoiceNinja.Models.GenericReportSchema genericReportSchema, CancellationToken cancellationToken = default);

  /// <summary>
  /// Tax period report
  /// Operation: POST /api/v1/reports/tax_period_report
  /// </summary>
  Task GetTaxPeriodAsync(Apigen.InvoiceNinja.Models.GenericReportSchema genericReportSchema, CancellationToken cancellationToken = default);

  /// <summary>
  /// User sales report
  /// Operation: POST /api/v1/reports/user_sales_report
  /// </summary>
  Task GetUserSalesAsync(Apigen.InvoiceNinja.Models.GenericReportSchema genericReportSchema, CancellationToken cancellationToken = default);

  /// <summary>
  /// Project reports
  /// Operation: POST /api/v1/reports/projects
  /// </summary>
  Task GetProjectAsync(Apigen.InvoiceNinja.Models.GenericReportSchema genericReportSchema, CancellationToken cancellationToken = default);

  /// <summary>
  /// Report preview
  /// Operation: POST /api/v1/reports/preview/{hash}
  /// </summary>
  Task GetReportPreviewAsync(string hash, CancellationToken cancellationToken = default);

  /// <summary>
  /// Export preview
  /// Operation: POST /api/v1/exports/preview/{hash}
  /// </summary>
  Task GetExportPreviewAsync(string hash, CancellationToken cancellationToken = default);

}
