//
// <auto-generated>
// Invoice Ninja API Models - Auto-generated from OpenAPI specification
//
// Generated by: ApiGenerator
// Source: specs/invoiceninja.yaml
// API: Invoice Ninja API Reference.
// Version: 5.12.55
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
// </auto-generated>
//
using System.Text.Json;
using System.Threading;
using System.Threading.Tasks;
using Apigen.InvoiceNinja.Models;

#nullable enable

namespace Apigen.InvoiceNinja.Client;

/// <summary>
/// Interface for system_logs operations
/// </summary>
public partial interface ISystemLogsClient
{
  /// <summary>
  /// Gets a list of system logs
  /// Operation: GET /api/v1/system_logs
  /// </summary>
  Task<ApiResponse<SystemLog[]>> ListAsync(GetSystemLogsRequest? request = null, CancellationToken cancellationToken = default);

  /// <summary>
  /// Shows a system_logs
  /// Operation: GET /api/v1/system_logs/{id}
  /// </summary>
  Task<ApiResponse<SystemLog>> GetAsync(string id, ShowSystemLogsRequest? request = null, CancellationToken cancellationToken = default);

}
