//
// <auto-generated>
// Invoice Ninja API Models - Auto-generated from OpenAPI specification
//
// Generated by: ApiGenerator
// Source: specs/invoiceninja.yaml
// API: Invoice Ninja API Reference.
// Version: 5.12.55
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
// </auto-generated>
//
using System.Text.Json;
using System.Threading;
using System.Threading.Tasks;
using Apigen.InvoiceNinja.Models;

#nullable enable

namespace Apigen.InvoiceNinja.Client;

/// <summary>
/// Interface for tags operations
/// </summary>
public partial interface ITagsClient
{
  /// <summary>
  /// List tags
  /// Operation: GET /api/v1/tags
  /// </summary>
  Task<ApiResponse<Tag[]>> ListAsync(GetTagsRequest? request = null, CancellationToken cancellationToken = default);

  /// <summary>
  /// Create tag
  /// Operation: POST /api/v1/tags
  /// </summary>
  Task<ApiResponse<Tag>> CreateAsync(Apigen.InvoiceNinja.Models.TagRequest tagRequest, CancellationToken cancellationToken = default);

  /// <summary>
  /// Blank tag
  /// Operation: GET /api/v1/tags/create
  /// </summary>
  Task<ApiResponse<Tag>> GetTagsCreateAsync(CancellationToken cancellationToken = default);

  /// <summary>
  /// Show tag
  /// Operation: GET /api/v1/tags/{id}
  /// </summary>
  Task<ApiResponse<Tag>> GetAsync(string id, CancellationToken cancellationToken = default);

  /// <summary>
  /// Update tag
  /// Operation: PUT /api/v1/tags/{id}
  /// </summary>
  Task<ApiResponse<Tag>> UpdateAsync(string id, Apigen.InvoiceNinja.Models.UpdateTagRequest updateTagRequest, CancellationToken cancellationToken = default);

  /// <summary>
  /// Delete tag
  /// Operation: DELETE /api/v1/tags/{id}
  /// </summary>
  Task<ApiResponse<Tag>> DeleteAsync(string id, CancellationToken cancellationToken = default);

  /// <summary>
  /// Edit tag
  /// Operation: GET /api/v1/tags/{id}/edit
  /// </summary>
  Task<ApiResponse<Tag>> EditAsync(string id, CancellationToken cancellationToken = default);

  /// <summary>
  /// Bulk tag actions
  /// Operation: POST /api/v1/tags/bulk
  /// </summary>
  Task<ApiResponse<Tag[]>> BulkAsync(Apigen.InvoiceNinja.Models.TagBulkAction tagBulkAction, BulkTagsRequest? request = null, CancellationToken cancellationToken = default);

}
