//
// <auto-generated>
// Invoice Ninja API Models - Auto-generated from OpenAPI specification
//
// Generated by: ApiGenerator
// Source: specs/invoiceninja.yaml
// API: Invoice Ninja API Reference.
// Version: 5.12.55
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
// </auto-generated>
//
using System.Text.Json;
using System.Threading;
using System.Threading.Tasks;
using Apigen.InvoiceNinja.Models;

#nullable enable

namespace Apigen.InvoiceNinja.Client;

/// <summary>
/// Interface for tax_rates operations
/// </summary>
public partial interface ITaxRatesClient
{
  /// <summary>
  /// Gets a list of tax_rates
  /// Operation: GET /api/v1/tax_rates
  /// </summary>
  Task<ApiResponse<TaxRate[]>> ListAsync(GetTaxRatesRequest? request = null, CancellationToken cancellationToken = default);

  /// <summary>
  /// Gets a new blank Tax Rate object
  /// Operation: GET /api/v1/tax_rates/create
  /// </summary>
  Task<ApiResponse<TaxRate>> GetTaxRateCreateAsync(CancellationToken cancellationToken = default);

  /// <summary>
  /// Shows a Tax Rate
  /// Operation: GET /api/v1/tax_rates/{id}
  /// </summary>
  Task<ApiResponse<TaxRate>> GetAsync(string id, CancellationToken cancellationToken = default);

  /// <summary>
  /// Updates a tax rate
  /// Operation: PUT /api/v1/tax_rates/{id}
  /// </summary>
  Task<ApiResponse<TaxRate>> UpdateAsync(string id, CancellationToken cancellationToken = default);

  /// <summary>
  /// Deletes a TaxRate
  /// Operation: DELETE /api/v1/tax_rates/{id}
  /// </summary>
  Task DeleteAsync(string id, CancellationToken cancellationToken = default);

  /// <summary>
  /// Shows a Tax Rate for editting
  /// Operation: GET /api/v1/tax_rates/{id}/edit
  /// </summary>
  Task<ApiResponse<TaxRate>> EditAsync(string id, CancellationToken cancellationToken = default);

  /// <summary>
  /// Performs bulk actions on an array of TaxRates
  /// Operation: POST /api/v1/tax_rates/bulk
  /// </summary>
  Task<ApiResponse<Webhook>> BulkAsync(List<int> body, BulkTaxRatesRequest? request = null, CancellationToken cancellationToken = default);

}
