//
// <auto-generated>
// Invoice Ninja API Models - Auto-generated from OpenAPI specification
//
// Generated by: ApiGenerator
// Source: specs/invoiceninja.yaml
// API: Invoice Ninja API Reference.
// Version: 5.12.55
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
// </auto-generated>
//
using System.Text.Json;
using System.Threading;
using System.Threading.Tasks;
using Apigen.InvoiceNinja.Models;

#nullable enable

namespace Apigen.InvoiceNinja.Client;

/// <summary>
/// Interface for templates operations
/// </summary>
public partial interface ITemplatesClient
{
  /// <summary>
  /// Returns a entity template with the template variables replaced with the Entities
  /// Operation: POST /api/v1/templates
  /// </summary>
  Task<ApiResponse<Template>> CreateAsync(Apigen.InvoiceNinja.Models.GetShowTemplateRequest getShowTemplateRequest, GetShowTemplateRequest? request = null, CancellationToken cancellationToken = default);

  /// <summary>
  /// Preview template by hash
  /// Operation: POST /api/v1/templates/preview/{hash}
  /// </summary>
  Task GetTemplatePreviewAsync(string hash, CancellationToken cancellationToken = default);

}
