//
// <auto-generated>
// Invoice Ninja API Models - Auto-generated from OpenAPI specification
//
// Generated by: ApiGenerator
// Source: specs/invoiceninja.yaml
// API: Invoice Ninja API Reference.
// Version: 5.12.55
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
// </auto-generated>
//
using System.Text.Json;
using System.Threading;
using System.Threading.Tasks;
using Apigen.InvoiceNinja.Models;

#nullable enable

namespace Apigen.InvoiceNinja.Client;

/// <summary>
/// Interface for update operations
/// </summary>
public partial interface IUpdateClient
{
  /// <summary>
  /// Performs a system update
  /// Operation: POST /api/v1/self-update
  /// </summary>
  Task SelfAsync(SelfUpdateRequest? request = null, CancellationToken cancellationToken = default);

  /// <summary>
  /// Check for available update
  /// Operation: POST /api/v1/self-update/check_version
  /// </summary>
  Task SelfUpdateCheckVersionAsync(CancellationToken cancellationToken = default);

}
