//
// <auto-generated>
// Invoice Ninja API Models - Auto-generated from OpenAPI specification
//
// Generated by: ApiGenerator
// Source: specs/invoiceninja.yaml
// API: Invoice Ninja API Reference.
// Version: 5.12.55
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
// </auto-generated>
//
using System.Text.Json;
using System.Threading;
using System.Threading.Tasks;
using Apigen.InvoiceNinja.Models;

#nullable enable

namespace Apigen.InvoiceNinja.Client;

/// <summary>
/// Interface for webhooks operations
/// </summary>
public partial interface IWebhooksClient
{
  /// <summary>
  /// Gets a list of Webhooks
  /// Operation: GET /api/v1/webhooks
  /// </summary>
  Task<ApiResponse<Webhook[]>> ListAsync(GetWebhooksRequest? request = null, CancellationToken cancellationToken = default);

  /// <summary>
  /// Adds a Webhook
  /// Operation: POST /api/v1/webhooks
  /// </summary>
  Task<ApiResponse<Webhook>> CreateAsync(StoreWebhookRequest? request = null, CancellationToken cancellationToken = default);

  /// <summary>
  /// Shows a Webhook
  /// Operation: GET /api/v1/webhooks/{id}
  /// </summary>
  Task<ApiResponse<Webhook>> GetAsync(string id, ShowWebhookRequest? request = null, CancellationToken cancellationToken = default);

  /// <summary>
  /// Updates a Webhook
  /// Operation: PUT /api/v1/webhooks/{id}
  /// </summary>
  Task<ApiResponse<Webhook>> UpdateAsync(string id, UpdateWebhookRequest? request = null, CancellationToken cancellationToken = default);

  /// <summary>
  /// Shows a Webhook for editting
  /// Operation: GET /api/v1/webhooks/{id}/edit
  /// </summary>
  Task<ApiResponse<Webhook>> EditAsync(string id, EditWebhookRequest? request = null, CancellationToken cancellationToken = default);

  /// <summary>
  /// Gets a new blank Webhook object
  /// Operation: GET /api/v1/webhooks/create
  /// </summary>
  Task<ApiResponse<Webhook>> GetWebhooksCreateAsync(GetWebhooksCreateRequest? request = null, CancellationToken cancellationToken = default);

  /// <summary>
  /// Performs bulk actions on an array of Webhooks
  /// Operation: POST /api/v1/webhooks/bulk
  /// </summary>
  Task<ApiResponse<Webhook>> BulkAsync(List<int> body, BulkWebhooksRequest? request = null, CancellationToken cancellationToken = default);

}
