//
// <auto-generated>
// Invoice Ninja API Models - Auto-generated from OpenAPI specification
//
// Generated by: ApiGenerator
// Source: specs/invoiceninja.yaml
// API: Invoice Ninja API Reference.
// Version: 5.12.55
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
// </auto-generated>
//
using System.Collections.Generic;
using System.Linq;
using System.Text.Json.Serialization;
using System.Web;

#nullable enable

namespace Apigen.InvoiceNinja.Client;

/// <summary>
/// Request parameters for Bulk tag actions
/// Operation: POST /api/v1/tags/bulk
/// </summary>
public partial class BulkTagsRequest : BaseRequest
{
  /// <summary>
  /// Action to perform
  /// </summary>
  [JsonPropertyName("action")]
  public string? Action { get; set; }

  public override string ToQueryString()
  {
    Dictionary<string, object> queryParams = new Dictionary<string, object>();

    queryParams["_method"] = "POST";

    // Fixed parameters added for POST /api/v1/tags/bulk
    if (Action != null)
      queryParams["action"] = Action;

    return queryParams.ToQueryString();
  }
}
