//
// <auto-generated>
// Invoice Ninja API Models - Auto-generated from OpenAPI specification
//
// Generated by: ApiGenerator
// Source: specs/invoiceninja.yaml
// API: Invoice Ninja API Reference.
// Version: 5.12.55
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
// </auto-generated>
//
using System.Collections.Generic;
using System.Linq;
using System.Text.Json.Serialization;
using System.Web;

#nullable enable

namespace Apigen.InvoiceNinja.Client;

/// <summary>
/// Request parameters for List locations
/// Operation: GET /api/v1/locations
/// </summary>
public partial class GetLocationsRequest : BaseRequest
{
  /// <summary>
  /// Replaces the default response index from data to a user specific string
  /// 
  /// ie.
  /// 
  /// ```html
  ///   ?index=new_index
  /// ```
  /// 
  /// response is wrapped
  /// 
  /// ```json
  ///   {
  ///     &apos;new_index&apos; : [
  ///       .....  
  ///     ]
  ///   }
  /// ```
  /// 
  /// </summary>
  [JsonPropertyName("index")]
  public string? Index { get; set; }

  /// <summary>
  /// The number of records to return for each request, default is 20
  /// </summary>
  [JsonPropertyName("per_page")]
  public int? PerPage { get; set; }

  /// <summary>
  /// The page number to return for this request (when performing pagination), default is 1
  /// </summary>
  [JsonPropertyName("page")]
  public int? Page { get; set; }

  /// <summary>
  /// Order the list by choosing a column and direction. Each value uses the form `column|asc` or `column|desc`.
  /// 
  /// **Single sort** — for example `sort=name|desc`.
  /// 
  /// **Multiple sorts** — for example  
  /// `sort[]=name|asc&amp;sort[]=id|desc`.
  /// 
  /// Location ordering is limited by the filter: `name` is the primary supported case; other column names must exist on the locations schema to take effect.
  /// 
  /// </summary>
  [JsonPropertyName("sort")]
  public List<string>? Sort { get; set; }

  /// <summary>
  /// Filter by location name
  /// 
  /// ```html
  /// ?name=warehouse
  /// ```
  /// 
  /// </summary>
  [JsonPropertyName("name")]
  public string? Name { get; set; }

  public override string ToQueryString()
  {
    Dictionary<string, object> queryParams = new Dictionary<string, object>();

    if (Index != null)
      queryParams["index"] = Index;
    if (PerPage != null)
      queryParams["per_page"] = PerPage;
    if (Page != null)
      queryParams["page"] = Page;
    if (Sort != null)
      queryParams["sort"] = Sort;
    if (Name != null)
      queryParams["name"] = Name;

    return queryParams.ToQueryString();
  }
}
