//
// <auto-generated>
// Invoice Ninja API Models - Auto-generated from OpenAPI specification
//
// Generated by: ApiGenerator
// Source: specs/invoiceninja.yaml
// API: Invoice Ninja API Reference.
// Version: 5.12.55
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
// </auto-generated>
//
using System.Collections.Generic;
using System.Linq;
using System.Text.Json.Serialization;
using System.Web;

#nullable enable

namespace Apigen.InvoiceNinja.Client;

/// <summary>
/// Request parameters for Gets a list of recurring_quotes
/// Operation: GET /api/v1/recurring_quotes
/// </summary>
public partial class GetRecurringQuotesRequest : BaseRequest
{
  /// <summary>
  /// Includes child relationships in the response, format is comma separated. Check each model for the list of associated includes
  /// </summary>
  [JsonPropertyName("include")]
  public string? Include { get; set; }

  /// <summary>
  /// The number of records to return for each request, default is 20
  /// </summary>
  [JsonPropertyName("per_page")]
  public int? PerPage { get; set; }

  /// <summary>
  /// The page number to return for this request (when performing pagination), default is 1
  /// </summary>
  [JsonPropertyName("page")]
  public int? Page { get; set; }

  /// <summary>
  /// Order the list by choosing a column and direction. Each value uses the form `column|asc` or `column|desc`.
  /// 
  /// **Single sort** — for example `sort=next_send_date|desc`.
  /// 
  /// **Multiple sorts** — for example  
  /// `sort[]=number|asc&amp;sort[]=id|desc`.
  /// 
  /// Recurring quotes use their table columns and related sorts from `RecurringQuoteFilters`. Unsupported keys are ignored.
  /// 
  /// </summary>
  [JsonPropertyName("sort")]
  public List<string>? Sort { get; set; }

  public override string ToQueryString()
  {
    Dictionary<string, object> queryParams = new Dictionary<string, object>();

    if (Include != null)
      queryParams["include"] = Include;
    if (PerPage != null)
      queryParams["per_page"] = PerPage;
    if (Page != null)
      queryParams["page"] = Page;
    if (Sort != null)
      queryParams["sort"] = Sort;

    return queryParams.ToQueryString();
  }
}
