//
// <auto-generated>
// Invoice Ninja API Models - Auto-generated from OpenAPI specification
//
// Generated by: ApiGenerator
// Source: specs/invoiceninja.yaml
// API: Invoice Ninja API Reference.
// Version: 5.12.55
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
// </auto-generated>
//
using System.Collections.Generic;
using System.Linq;
using System.Text.Json.Serialization;
using System.Web;

#nullable enable

namespace Apigen.InvoiceNinja.Client;

/// <summary>
/// Request parameters for List tags
/// Operation: GET /api/v1/tags
/// </summary>
public partial class GetTagsRequest : BaseRequest
{
  /// <summary>
  /// Replaces the default response index from data to a user specific string
  /// 
  /// ie.
  /// 
  /// ```html
  ///   ?index=new_index
  /// ```
  /// 
  /// response is wrapped
  /// 
  /// ```json
  ///   {
  ///     &apos;new_index&apos; : [
  ///       .....  
  ///     ]
  ///   }
  /// ```
  /// 
  /// </summary>
  [JsonPropertyName("index")]
  public string? Index { get; set; }

  /// <summary>
  /// The number of records to return for each request, default is 20
  /// </summary>
  [JsonPropertyName("per_page")]
  public int? PerPage { get; set; }

  /// <summary>
  /// The page number to return for this request (when performing pagination), default is 1
  /// </summary>
  [JsonPropertyName("page")]
  public int? Page { get; set; }

  /// <summary>
  /// Supported values: App\Models\Task, App\Models\Project
  /// </summary>
  [JsonPropertyName("entity_type")]
  public string? EntityType { get; set; }

  /// <summary>
  /// Search by tag name
  /// </summary>
  [JsonPropertyName("filter")]
  public string? Filter { get; set; }

  /// <summary>
  /// Sort using column|direction, for example name|asc or created_at|desc
  /// </summary>
  [JsonPropertyName("sort")]
  public string? Sort { get; set; }

  public override string ToQueryString()
  {
    Dictionary<string, object> queryParams = new Dictionary<string, object>();

    if (Index != null)
      queryParams["index"] = Index;
    if (PerPage != null)
      queryParams["per_page"] = PerPage;
    if (Page != null)
      queryParams["page"] = Page;
    if (EntityType != null)
      queryParams["entity_type"] = EntityType;
    if (Filter != null)
      queryParams["filter"] = Filter;
    if (Sort != null)
      queryParams["sort"] = Sort;

    return queryParams.ToQueryString();
  }
}
