//
// <auto-generated>
// Invoice Ninja API Models - Auto-generated from OpenAPI specification
//
// Generated by: ApiGenerator
// Source: specs/invoiceninja.yaml
// API: Invoice Ninja API Reference.
// Version: 5.12.55
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
// </auto-generated>
//
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Text.Json;
using System.Text.Json.Serialization;

#nullable enable

namespace Apigen.InvoiceNinja.Models;

/// <summary>
/// Activity from OpenAPI schema.
/// Schema path: #/components/schemas/Activity
/// </summary>
public class Activity
{
  /// <summary>
  /// The id field of the activity
  /// </summary>
  [System.Text.Json.Serialization.JsonPropertyName("id")]
  public string? Id { get; set; }

  /// <summary>
  /// The activity type id
  /// </summary>
  [System.Text.Json.Serialization.JsonPropertyName("activity_type_id")]
  public string? ActivityTypeId { get; set; }

  /// <summary>
  /// The client hashed id
  /// </summary>
  [System.Text.Json.Serialization.JsonPropertyName("client_id")]
  public string? ClientId { get; set; }

  /// <summary>
  /// The company hashed id
  /// </summary>
  [System.Text.Json.Serialization.JsonPropertyName("company_id")]
  public string? CompanyId { get; set; }

  /// <summary>
  /// The user hashed id
  /// </summary>
  [System.Text.Json.Serialization.JsonPropertyName("user_id")]
  public string? UserId { get; set; }

  /// <summary>
  /// The invoice hashed id
  /// </summary>
  [System.Text.Json.Serialization.JsonPropertyName("invoice_id")]
  public string? InvoiceId { get; set; }

  /// <summary>
  /// The payment hashed id
  /// </summary>
  [System.Text.Json.Serialization.JsonPropertyName("payment_id")]
  public string? PaymentId { get; set; }

  /// <summary>
  /// The credit hashed id
  /// </summary>
  [System.Text.Json.Serialization.JsonPropertyName("credit_id")]
  public string? CreditId { get; set; }

  /// <summary>
  /// Unixtimestamp the last time the record was updated
  /// </summary>
  [JsonConverter(typeof(UnixTimestampConverter))]
  [System.Text.Json.Serialization.JsonPropertyName("updated_at")]
  public DateTimeOffset? UpdatedAt { get; set; }

  /// <summary>
  /// The expense hashed id
  /// </summary>
  [System.Text.Json.Serialization.JsonPropertyName("expense_id")]
  public string? ExpenseId { get; set; }

  /// <summary>
  /// Defines is the activity was performed by the system
  /// </summary>
  [System.Text.Json.Serialization.JsonPropertyName("is_system")]
  public bool? IsSystem { get; set; }

  /// <summary>
  /// The contact hashed id
  /// </summary>
  [System.Text.Json.Serialization.JsonPropertyName("contact_id")]
  public string? ContactId { get; set; }

  /// <summary>
  /// The task hashed id
  /// </summary>
  [System.Text.Json.Serialization.JsonPropertyName("task_id")]
  public string? TaskId { get; set; }

  /// <summary>
  /// Activity Notes
  /// </summary>
  [System.Text.Json.Serialization.JsonPropertyName("notes")]
  public string? Notes { get; set; }

  /// <summary>
  /// The hashed ID of the token who performed the action
  /// </summary>
  [System.Text.Json.Serialization.JsonPropertyName("token_id")]
  public string? TokenId { get; set; }

  /// <summary>
  /// The IP Address of the user who performed the action
  /// </summary>
  [System.Text.Json.Serialization.JsonPropertyName("ip")]
  public string? Ip { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("user")]
  public User? User { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("client")]
  public Client? Client { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("contact")]
  public ClientContact? Contact { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("recurring_invoice")]
  public RecurringInvoice? RecurringInvoice { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("invoice")]
  public Invoice? Invoice { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("credit")]
  public Credit? Credit { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("quote")]
  public Quote? Quote { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("payment")]
  public Payment? Payment { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("expense")]
  public Expense? Expense { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("task")]
  public TaskItem? Task { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("purchase_order")]
  public PurchaseOrder? PurchaseOrder { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("vendor")]
  public Vendor? Vendor { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("vendor_contact")]
  public VendorContact? VendorContact { get; set; }
}
