//
// <auto-generated>
// Invoice Ninja API Models - Auto-generated from OpenAPI specification
//
// Generated by: ApiGenerator
// Source: specs/invoiceninja.yaml
// API: Invoice Ninja API Reference.
// Version: 5.11.48
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
// </auto-generated>
//
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Text.Json;
using System.Text.Json.Serialization;

#nullable enable

namespace Apigen.InvoiceNinja.Models;

/// <summary>
/// BankIntegration from OpenAPI schema.
/// Schema path: #/components/schemas/BankIntegration
/// </summary>
public class BankIntegration
{
  /// <summary>
  /// The bank integration hashed id
  /// </summary>
  [System.Text.Json.Serialization.JsonPropertyName("id")]
  public string? Id { get; set; }

  /// <summary>
  /// The user hashed id
  /// </summary>
  [System.Text.Json.Serialization.JsonPropertyName("user_id")]
  public string? UserId { get; set; }

  /// <summary>
  /// The providers bank name
  /// </summary>
  [System.Text.Json.Serialization.JsonPropertyName("provider_bank_name")]
  public string? ProviderBankName { get; set; }

  /// <summary>
  /// The bank account id
  /// </summary>
  [JsonConverter(typeof(StringToIntegerConverter))]
  [System.Text.Json.Serialization.JsonPropertyName("bank_account_id")]
  public int? BankAccountId { get; set; }

  /// <summary>
  /// The name of the account
  /// </summary>
  [System.Text.Json.Serialization.JsonPropertyName("bank_account_name")]
  public string? BankAccountName { get; set; }

  /// <summary>
  /// The account number
  /// </summary>
  [System.Text.Json.Serialization.JsonPropertyName("bank_account_number")]
  public string? BankAccountNumber { get; set; }

  /// <summary>
  /// The status of the bank account
  /// </summary>
  [System.Text.Json.Serialization.JsonPropertyName("bank_account_status")]
  public string? BankAccountStatus { get; set; }

  /// <summary>
  /// The type of account
  /// </summary>
  [System.Text.Json.Serialization.JsonPropertyName("bank_account_type")]
  public string? BankAccountType { get; set; }

  /// <summary>
  /// The current bank balance if available
  /// </summary>
  [JsonConverter(typeof(EmptyStringToNullableDecimalConverter))]
  [System.Text.Json.Serialization.JsonPropertyName("balance")]
  public decimal? Balance { get; set; }

  /// <summary>
  /// iso_3166_3 code
  /// </summary>
  [System.Text.Json.Serialization.JsonPropertyName("currency")]
  public string? Currency { get; set; }
}
