//
// <auto-generated>
// Invoice Ninja API Models - Auto-generated from OpenAPI specification
//
// Generated by: ApiGenerator
// Source: specs/invoiceninja.yaml
// API: Invoice Ninja API Reference.
// Version: 5.11.48
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
// </auto-generated>
//
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Text.Json;
using System.Text.Json.Serialization;

#nullable enable

namespace Apigen.InvoiceNinja.Models;

/// <summary>
/// BankTransactionRule from OpenAPI schema.
/// Schema path: #/components/schemas/BankTransactionRule
/// </summary>
public class BankTransactionRule
{
  /// <summary>
  /// The bank transaction rules hashed id
  /// </summary>
  [System.Text.Json.Serialization.JsonPropertyName("id")]
  public string? Id { get; set; }

  /// <summary>
  /// The user hashed id
  /// </summary>
  [System.Text.Json.Serialization.JsonPropertyName("user_id")]
  public string? UserId { get; set; }

  /// <summary>
  /// The name of the transaction
  /// </summary>
  [System.Text.Json.Serialization.JsonPropertyName("name")]
  public string? Name { get; set; }

  /// <summary>
  /// A mapped collection of the sub rules for the BankTransactionRule
  /// </summary>
  [System.Text.Json.Serialization.JsonPropertyName("rules")]
  public List<BTRules>? Rules { get; set; }

  /// <summary>
  /// Flags whether the rule converts the transaction automatically
  /// </summary>
  [System.Text.Json.Serialization.JsonPropertyName("auto_convert")]
  public bool? AutoConvert { get; set; }

  /// <summary>
  /// Flags whether all subrules are required for the match
  /// </summary>
  [System.Text.Json.Serialization.JsonPropertyName("matches_on_all")]
  public bool? MatchesOnAll { get; set; }

  /// <summary>
  /// Flags whether the rule applies to a CREDIT or DEBIT
  /// </summary>
  [System.Text.Json.Serialization.JsonPropertyName("applies_to")]
  public string? AppliesTo { get; set; }

  /// <summary>
  /// The client hashed id
  /// </summary>
  [System.Text.Json.Serialization.JsonPropertyName("client_id")]
  public string? ClientId { get; set; }

  /// <summary>
  /// The vendor hashed id
  /// </summary>
  [System.Text.Json.Serialization.JsonPropertyName("vendor_id")]
  public string? VendorId { get; set; }

  /// <summary>
  /// The category hashed id
  /// </summary>
  [System.Text.Json.Serialization.JsonPropertyName("category_id")]
  public string? CategoryId { get; set; }
}
