//
// <auto-generated>
// Invoice Ninja API Models - Auto-generated from OpenAPI specification
//
// Generated by: ApiGenerator
// Source: specs/invoiceninja.yaml
// API: Invoice Ninja API Reference.
// Version: 5.12.55
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
// </auto-generated>
//
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Text.Json;
using System.Text.Json.Serialization;

#nullable enable

namespace Apigen.InvoiceNinja.Models;

/// <summary>
/// BankTransaction from OpenAPI schema.
/// Schema path: #/components/schemas/BankTransaction
/// </summary>
public partial class BankTransaction
{
  /// <summary>
  /// The bank integration hashed id
  /// </summary>
  [System.Text.Json.Serialization.JsonPropertyName("id")]
  public string? Id { get; set; }

  /// <summary>
  /// The user hashed id
  /// </summary>
  [System.Text.Json.Serialization.JsonPropertyName("user_id")]
  public string? UserId { get; set; }

  /// <summary>
  /// The id of the transaction rule
  /// </summary>
  [JsonConverter(typeof(StringToIntegerConverter))]
  [System.Text.Json.Serialization.JsonPropertyName("transaction_id")]
  public int? TransactionId { get; set; }

  /// <summary>
  /// The transaction amount
  /// </summary>
  [JsonConverter(typeof(EmptyStringToNullableDecimalConverter))]
  [System.Text.Json.Serialization.JsonPropertyName("amount")]
  public decimal? Amount { get; set; }

  /// <summary>
  /// The currency ID of the currency
  /// </summary>
  [System.Text.Json.Serialization.JsonPropertyName("currency_id")]
  public string? CurrencyId { get; set; }

  /// <summary>
  /// The account type
  /// </summary>
  [System.Text.Json.Serialization.JsonPropertyName("account_type")]
  public string? AccountType { get; set; }

  /// <summary>
  /// The description of the transaction
  /// </summary>
  [System.Text.Json.Serialization.JsonPropertyName("description")]
  public string? Description { get; set; }

  /// <summary>
  /// The category id
  /// </summary>
  [JsonConverter(typeof(StringToIntegerConverter))]
  [System.Text.Json.Serialization.JsonPropertyName("category_id")]
  public int? CategoryId { get; set; }

  /// <summary>
  /// The category description
  /// </summary>
  [System.Text.Json.Serialization.JsonPropertyName("category_type")]
  public string? CategoryType { get; set; }

  /// <summary>
  /// Either CREDIT or DEBIT
  /// </summary>
  [System.Text.Json.Serialization.JsonPropertyName("base_type")]
  public string? BaseType { get; set; }

  /// <summary>
  /// The date of the transaction
  /// </summary>
  [System.Text.Json.Serialization.JsonPropertyName("date")]
  public string? Date { get; set; }

  /// <summary>
  /// The ID number of the bank account
  /// </summary>
  [JsonConverter(typeof(StringToIntegerConverter))]
  [System.Text.Json.Serialization.JsonPropertyName("bank_account_id")]
  public int? BankAccountId { get; set; }
}
