//
// <auto-generated>
// Invoice Ninja API Models - Auto-generated from OpenAPI specification
//
// Generated by: ApiGenerator
// Source: specs/invoiceninja.yaml
// API: Invoice Ninja API Reference.
// Version: 5.11.48
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
// </auto-generated>
//
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Text.Json;
using System.Text.Json.Serialization;

#nullable enable

namespace Apigen.InvoiceNinja.Models;

/// <summary>
/// BTRules from OpenAPI schema.
/// Schema path: #/components/schemas/BTRules
/// </summary>
public class BTRules
{
  /// <summary>
  /// The key to search
  /// </summary>
  [System.Text.Json.Serialization.JsonPropertyName("data_key")]
  public string? DataKey { get; set; }

  /// <summary>
  /// The operator flag of the search
  /// </summary>
  [System.Text.Json.Serialization.JsonPropertyName("operator")]
  public string? Operator { get; set; }

  /// <summary>
  /// The value to search for
  /// </summary>
  [System.Text.Json.Serialization.JsonPropertyName("value")]
  public string? Value { get; set; }
}
