//
// <auto-generated>
// Invoice Ninja API Models - Auto-generated from OpenAPI specification
//
// Generated by: ApiGenerator
// Source: specs/invoiceninja.yaml
// API: Invoice Ninja API Reference.
// Version: 5.11.48
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
// </auto-generated>
//
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Text.Json;
using System.Text.Json.Serialization;

#nullable enable

namespace Apigen.InvoiceNinja.Models;

/// <summary>
/// BulkProductsRequest from OpenAPI schema.
/// Schema path: #/components/schemas/BulkProductsRequest
/// </summary>
public class BulkProductsRequest
{
  /// <summary>
  /// The action to perform ie. archive / restore / delete / set_tax_id
  /// </summary>
  [Required]
  [System.Text.Json.Serialization.JsonIgnore(Condition = System.Text.Json.Serialization.JsonIgnoreCondition.Never)]
  [System.Text.Json.Serialization.JsonPropertyName("action")]
  public string? Action { get; set; }

  [Required]
  [System.Text.Json.Serialization.JsonIgnore(Condition = System.Text.Json.Serialization.JsonIgnoreCondition.Never)]
  [System.Text.Json.Serialization.JsonPropertyName("ids")]
  public List<string?>? Ids { get; set; }

  /// <summary>
  /// The tax rate id to set on the list of products
  /// 
  /// The following constants are available (default = &apos;1&apos;)
  /// 
  /// 
  /// PRODUCT_TYPE_PHYSICAL = &apos;1&apos;
  /// PRODUCT_TYPE_SERVICE = &apos;2&apos;
  /// PRODUCT_TYPE_DIGITAL = &apos;3&apos;
  /// PRODUCT_TYPE_SHIPPING = &apos;4&apos;
  /// PRODUCT_TYPE_EXEMPT = &apos;5&apos;
  /// PRODUCT_TYPE_REDUCED_TAX = &apos;6&apos;
  /// PRODUCT_TYPE_OVERRIDE_TAX = &apos;7&apos;
  /// PRODUCT_TYPE_ZERO_RATED = &apos;8&apos;
  /// PRODUCT_TYPE_REVERSE_TAX = &apos;9&apos;
  /// 
  /// 
  /// </summary>
  [System.Text.Json.Serialization.JsonIgnore(Condition = System.Text.Json.Serialization.JsonIgnoreCondition.WhenWritingNull)]
  [System.Text.Json.Serialization.JsonPropertyName("tax_id")]
  public string? TaxId { get; set; }
}
