//
// <auto-generated>
// Invoice Ninja API Models - Auto-generated from OpenAPI specification
//
// Generated by: ApiGenerator
// Source: specs/invoiceninja.yaml
// API: Invoice Ninja API Reference.
// Version: 5.12.55
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
// </auto-generated>
//
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Text.Json;
using System.Text.Json.Serialization;

#nullable enable

namespace Apigen.InvoiceNinja.Models;

/// <summary>
/// BulkInvoicesRequest (generated from inline request body).
/// Source: POST /api/v1/invoices/bulk (requestBody)
/// </summary>
public partial class BulkInvoicesRequest
{
  /// <summary>
  /// The email type to be sent, when bulk emailing invoices options include:
  /// invoice (default)
  /// quote
  /// credit
  /// payment
  /// payment_partial
  /// statement
  /// reminder1
  /// reminder2
  /// reminder3
  /// reminder_endless
  /// custom1
  /// custom2
  /// custom3
  /// purchase_order
  /// email_quote_template_reminder1
  /// 
  /// </summary>
  [System.Text.Json.Serialization.JsonIgnore(Condition = System.Text.Json.Serialization.JsonIgnoreCondition.WhenWritingNull)]
  [System.Text.Json.Serialization.JsonPropertyName("email_type")]
  public string? EmailType { get; set; }

  /// <summary>
  /// The action to be performed, options include:
  /// bulk_download
  /// Bulk download an array of invoice PDFs (These are sent to the admin via email.)
  /// download
  /// Download a single PDF. (Returns a single PDF object)
  /// bulk_print
  /// Merges an array of Invoice PDFs for easy one click printing.
  /// auto_bill
  /// Attempts to automatically bill the invoices with the payment method on file.
  /// clone_to_invoice
  /// Returns a clone of the invoice.
  /// clone_to_quote
  /// Returns a quote cloned using the properties of the given invoice.
  /// mark_paid
  /// Marks an array of invoices as paid.
  /// mark_sent
  /// Marks an array of invoices as sent.
  /// restore
  /// Restores an array of invoices
  /// delete
  /// Deletes an array of invoices
  /// archive
  /// Archives an array of invoices
  /// cancel
  /// Cancels an array of invoices
  /// email
  /// Emails an array of invoices
  /// send_email
  /// Emails an array of invoices. Requires additional properties to be sent. email_type
  /// 
  /// </summary>
  [System.Text.Json.Serialization.JsonIgnore(Condition = System.Text.Json.Serialization.JsonIgnoreCondition.WhenWritingNull)]
  [System.Text.Json.Serialization.JsonPropertyName("action")]
  public string? Action { get; set; }

  [System.Text.Json.Serialization.JsonIgnore(Condition = System.Text.Json.Serialization.JsonIgnoreCondition.WhenWritingNull)]
  [System.Text.Json.Serialization.JsonPropertyName("ids")]
  public List<string?>? Ids { get; set; }
}
