//
// <auto-generated>
// Invoice Ninja API Models - Auto-generated from OpenAPI specification
//
// Generated by: ApiGenerator
// Source: specs/invoiceninja.yaml
// API: Invoice Ninja API Reference.
// Version: 5.11.48
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
// </auto-generated>
//
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Text.Json;
using System.Text.Json.Serialization;

#nullable enable

namespace Apigen.InvoiceNinja.Models;

/// <summary>
/// BulkRecurringInvoicesRequest from OpenAPI schema.
/// Schema path: #/components/schemas/BulkRecurringInvoicesRequest
/// </summary>
public class BulkRecurringInvoicesRequest
{
  /// <summary>
  /// The action to be performed, options include:
  /// start
  /// Starts (or restarts) the recurring invoice. **note** if the recurring invoice has been stopped for a long time, it will attempt to catch back up firing a new Invoice every hour per interval that has been missed.
  /// If you do not wish to have the recurring invoice catch up, you should set the next_send_date to the correct date you wish the recurring invoice to commence from.
  /// stop
  /// Stops the recurring invoice.
  /// send_now
  /// Force sends the recurring invoice - this option is only available when the recurring invoice is in a draft state.
  /// restore
  /// Restores the recurring invoice from an archived or deleted state.
  /// archive
  /// Archives the recurring invoice. The recurring invoice will not fire in this state.
  /// delete
  /// Deletes a recurring invoice.
  /// 
  /// </summary>
  [System.Text.Json.Serialization.JsonIgnore(Condition = System.Text.Json.Serialization.JsonIgnoreCondition.WhenWritingNull)]
  [System.Text.Json.Serialization.JsonPropertyName("action")]
  public string? Action { get; set; }

  [System.Text.Json.Serialization.JsonIgnore(Condition = System.Text.Json.Serialization.JsonIgnoreCondition.WhenWritingNull)]
  [System.Text.Json.Serialization.JsonPropertyName("ids")]
  public List<string?>? Ids { get; set; }
}
