//
// <auto-generated>
// Invoice Ninja API Models - Auto-generated from OpenAPI specification
//
// Generated by: ApiGenerator
// Source: specs/invoiceninja.yaml
// API: Invoice Ninja API Reference.
// Version: 5.12.55
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
// </auto-generated>
//
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Text.Json;
using System.Text.Json.Serialization;

#nullable enable

namespace Apigen.InvoiceNinja.Models;

/// <summary>
/// BulkQuotesRequest from OpenAPI schema.
/// Schema path: #/components/schemas/BulkQuotesRequest
/// </summary>
public class BulkQuotesRequest
{
  /// <summary>
  /// The action to be performed, options include:
  /// approve
  /// Bulk approve an array of quotes
  /// convert
  /// Bulk convert an array of quotes to invoices
  /// send_email
  /// Bulk send an array of quotes as emails
  /// mark_sent
  /// Bulk mark an array of quotes as sent
  /// restore
  /// Restores an array of quotes
  /// delete
  /// Deletes an array of invoices
  /// archive
  /// Archives an array of invoices
  /// 
  /// </summary>
  [System.Text.Json.Serialization.JsonIgnore(Condition = System.Text.Json.Serialization.JsonIgnoreCondition.WhenWritingNull)]
  [System.Text.Json.Serialization.JsonPropertyName("action")]
  public string? Action { get; set; }

  [System.Text.Json.Serialization.JsonIgnore(Condition = System.Text.Json.Serialization.JsonIgnoreCondition.WhenWritingNull)]
  [System.Text.Json.Serialization.JsonPropertyName("ids")]
  public List<string?>? Ids { get; set; }
}
