//
// <auto-generated>
// Invoice Ninja API Models - Auto-generated from OpenAPI specification
//
// Generated by: ApiGenerator
// Source: specs/invoiceninja.yaml
// API: Invoice Ninja API Reference.
// Version: 5.11.48
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
// </auto-generated>
//
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Text.Json;
using System.Text.Json.Serialization;

#nullable enable

namespace Apigen.InvoiceNinja.Models;

/// <summary>
/// ClientStatementRequest from OpenAPI schema.
/// Schema path: #/components/schemas/ClientStatementRequest
/// </summary>
public class ClientStatementRequest
{
  /// <summary>
  /// The start date of the statement period - format Y-m-d
  /// </summary>
  [System.Text.Json.Serialization.JsonIgnore(Condition = System.Text.Json.Serialization.JsonIgnoreCondition.WhenWritingNull)]
  [System.Text.Json.Serialization.JsonPropertyName("start_date")]
  public string? StartDate { get; set; }

  /// <summary>
  /// The start date of the statement period - format Y-m-d
  /// </summary>
  [System.Text.Json.Serialization.JsonIgnore(Condition = System.Text.Json.Serialization.JsonIgnoreCondition.WhenWritingNull)]
  [System.Text.Json.Serialization.JsonPropertyName("end_date")]
  public string? EndDate { get; set; }

  /// <summary>
  /// The hashed ID of the client
  /// </summary>
  [System.Text.Json.Serialization.JsonIgnore(Condition = System.Text.Json.Serialization.JsonIgnoreCondition.WhenWritingNull)]
  [System.Text.Json.Serialization.JsonPropertyName("client_id")]
  public string? ClientId { get; set; }

  /// <summary>
  /// Flag which determines if the payments table is shown
  /// </summary>
  [System.Text.Json.Serialization.JsonIgnore(Condition = System.Text.Json.Serialization.JsonIgnoreCondition.WhenWritingNull)]
  [System.Text.Json.Serialization.JsonPropertyName("show_payments_table")]
  public bool? ShowPaymentsTable { get; set; }

  /// <summary>
  /// Flag which determines if the credits table is shown
  /// </summary>
  [System.Text.Json.Serialization.JsonIgnore(Condition = System.Text.Json.Serialization.JsonIgnoreCondition.WhenWritingNull)]
  [System.Text.Json.Serialization.JsonPropertyName("show_credits_table")]
  public bool? ShowCreditsTable { get; set; }

  /// <summary>
  /// Flag which determines if the aging table is shown
  /// </summary>
  [System.Text.Json.Serialization.JsonIgnore(Condition = System.Text.Json.Serialization.JsonIgnoreCondition.WhenWritingNull)]
  [System.Text.Json.Serialization.JsonPropertyName("show_aging_table")]
  public bool? ShowAgingTable { get; set; }
}
