//
// <auto-generated>
// Invoice Ninja API Models - Auto-generated from OpenAPI specification
//
// Generated by: ApiGenerator
// Source: specs/invoiceninja.yaml
// API: Invoice Ninja API Reference.
// Version: 5.12.55
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
// </auto-generated>
//
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Text.Json;
using System.Text.Json.Serialization;

#nullable enable

namespace Apigen.InvoiceNinja.Models;

/// <summary>
/// ClientGatewayToken from OpenAPI schema.
/// Schema path: #/components/schemas/ClientGatewayToken
/// </summary>
public class ClientGatewayToken
{
  /// <summary>
  /// The hashed id of the client gateway token
  /// </summary>
  [System.Text.Json.Serialization.JsonPropertyName("id")]
  public string? Id { get; set; }

  /// <summary>
  /// The hashed_id of the client
  /// </summary>
  [System.Text.Json.Serialization.JsonPropertyName("client_id")]
  public string? ClientId { get; set; }

  /// <summary>
  /// The payment token
  /// </summary>
  [System.Text.Json.Serialization.JsonPropertyName("token")]
  public string? Token { get; set; }

  /// <summary>
  /// THe bank account routing number
  /// </summary>
  [System.Text.Json.Serialization.JsonPropertyName("routing_number")]
  public string? RoutingNumber { get; set; }

  /// <summary>
  /// The hashed id of the company gateway
  /// </summary>
  [System.Text.Json.Serialization.JsonPropertyName("company_gateway_id")]
  public string? CompanyGatewayId { get; set; }

  /// <summary>
  /// Flag determining if the token is the default payment method
  /// </summary>
  [System.Text.Json.Serialization.JsonPropertyName("is_default")]
  public bool? IsDefault { get; set; }
}
