//
// <auto-generated>
// Invoice Ninja API Models - Auto-generated from OpenAPI specification
//
// Generated by: ApiGenerator
// Source: specs/invoiceninja.yaml
// API: Invoice Ninja API Reference.
// Version: 5.12.55
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
// </auto-generated>
//
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Text.Json;
using System.Text.Json.Serialization;

#nullable enable

namespace Apigen.InvoiceNinja.Models;

/// <summary>
/// ClientContact from OpenAPI schema.
/// Schema path: #/components/schemas/ClientContact
/// </summary>
public partial class ClientContact
{
  /// <summary>
  /// The hashed if of the contact
  /// </summary>
  [System.Text.Json.Serialization.JsonPropertyName("id")]
  public string? Id { get; set; }

  /// <summary>
  /// The hashed id of the user who created the contact
  /// </summary>
  [System.Text.Json.Serialization.JsonPropertyName("user_id")]
  public string? UserId { get; set; }

  /// <summary>
  /// The hashed id of the client
  /// </summary>
  [System.Text.Json.Serialization.JsonPropertyName("client_id")]
  public string? ClientId { get; set; }

  /// <summary>
  /// The first name of the contact
  /// </summary>
  [System.Text.Json.Serialization.JsonPropertyName("first_name")]
  public string? FirstName { get; set; }

  /// <summary>
  /// The last name of the contact
  /// </summary>
  [System.Text.Json.Serialization.JsonPropertyName("last_name")]
  public string? LastName { get; set; }

  /// <summary>
  /// The phone number of the contact
  /// </summary>
  [System.Text.Json.Serialization.JsonPropertyName("phone")]
  public string? Phone { get; set; }

  /// <summary>
  /// A Custom field value
  /// </summary>
  [System.Text.Json.Serialization.JsonPropertyName("custom_value1")]
  public string? CustomValue1 { get; set; }

  /// <summary>
  /// A Custom field value
  /// </summary>
  [System.Text.Json.Serialization.JsonPropertyName("custom_value2")]
  public string? CustomValue2 { get; set; }

  /// <summary>
  /// A Custom field value
  /// </summary>
  [System.Text.Json.Serialization.JsonPropertyName("custom_value3")]
  public string? CustomValue3 { get; set; }

  /// <summary>
  /// A Custom field value
  /// </summary>
  [System.Text.Json.Serialization.JsonPropertyName("custom_value4")]
  public string? CustomValue4 { get; set; }

  /// <summary>
  /// The email of the contact
  /// </summary>
  [System.Text.Json.Serialization.JsonPropertyName("email")]
  public string? Email { get; set; }

  /// <summary>
  /// The terms of service which the contact has accpeted
  /// </summary>
  [System.Text.Json.Serialization.JsonPropertyName("accepted_terms_version")]
  public string? AcceptedTermsVersion { get; set; }

  /// <summary>
  /// The hashed password of the contact
  /// </summary>
  [System.Text.Json.Serialization.JsonPropertyName("password")]
  public string? Password { get; set; }

  /// <summary>
  /// The confirmation code used to authenticate the contacts email address
  /// </summary>
  [System.Text.Json.Serialization.JsonPropertyName("confirmation_code")]
  public string? ConfirmationCode { get; set; }

  /// <summary>
  /// A uuid based token.
  /// </summary>
  [System.Text.Json.Serialization.JsonPropertyName("token")]
  public string? Token { get; set; }

  /// <summary>
  /// A unique identifier for the contact
  /// </summary>
  [System.Text.Json.Serialization.JsonPropertyName("contact_key")]
  public string? ContactKey { get; set; }

  /// <summary>
  /// Defines is this contact is the primary contact for the client
  /// </summary>
  [System.Text.Json.Serialization.JsonPropertyName("is_primary")]
  public bool? IsPrimary { get; set; }

  /// <summary>
  /// Boolean value confirms the user has confirmed their account.
  /// </summary>
  [System.Text.Json.Serialization.JsonPropertyName("confirmed")]
  public bool? Confirmed { get; set; }

  /// <summary>
  /// Boolean value defines if the contact has been locked out.
  /// </summary>
  [System.Text.Json.Serialization.JsonPropertyName("is_locked")]
  public bool? IsLocked { get; set; }

  /// <summary>
  /// Boolean value determines is this contact should receive emails
  /// </summary>
  [System.Text.Json.Serialization.JsonPropertyName("send_email")]
  public bool? SendEmail { get; set; }

  /// <summary>
  /// The number of failed logins the contact has had
  /// </summary>
  [System.Text.Json.Serialization.JsonPropertyName("failed_logins")]
  public decimal? FailedLogins { get; set; }

  /// <summary>
  /// The date which the contact confirmed their email
  /// </summary>
  [JsonConverter(typeof(UnixTimestampConverter))]
  [System.Text.Json.Serialization.JsonPropertyName("email_verified_at")]
  public DateTimeOffset? EmailVerifiedAt { get; set; }

  /// <summary>
  /// Timestamp
  /// </summary>
  [System.Text.Json.Serialization.JsonPropertyName("last_login")]
  public decimal? LastLogin { get; set; }

  /// <summary>
  /// Timestamp
  /// </summary>
  [JsonConverter(typeof(UnixTimestampConverter))]
  [System.Text.Json.Serialization.JsonPropertyName("created_at")]
  public DateTimeOffset? CreatedAt { get; set; }

  /// <summary>
  /// Timestamp
  /// </summary>
  [JsonConverter(typeof(UnixTimestampConverter))]
  [System.Text.Json.Serialization.JsonPropertyName("updated_at")]
  public DateTimeOffset? UpdatedAt { get; set; }

  /// <summary>
  /// Timestamp
  /// </summary>
  [JsonConverter(typeof(UnixTimestampConverter))]
  [System.Text.Json.Serialization.JsonPropertyName("deleted_at")]
  public DateTimeOffset? DeletedAt { get; set; }
}
