//
// <auto-generated>
// Invoice Ninja API Models - Auto-generated from OpenAPI specification
//
// Generated by: ApiGenerator
// Source: specs/invoiceninja.yaml
// API: Invoice Ninja API Reference.
// Version: 5.11.48
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
// </auto-generated>
//
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Text.Json;
using System.Text.Json.Serialization;

#nullable enable

namespace Apigen.InvoiceNinja.Models;

/// <summary>
/// CompanyUser from OpenAPI schema.
/// Schema path: #/components/schemas/CompanyUser
/// </summary>
public class CompanyUser
{
  /// <summary>
  /// The user permissions for this company in a comma separated list
  /// </summary>
  [System.Text.Json.Serialization.JsonPropertyName("permissions")]
  public string? Permissions { get; set; }

  /// <summary>
  /// Settings that are used for the flutter applications to store user preferences / metadata
  /// </summary>
  [System.Text.Json.Serialization.JsonPropertyName("settings")]
  public object? Settings { get; set; }

  /// <summary>
  /// Dedicated settings object for the react web application
  /// </summary>
  [System.Text.Json.Serialization.JsonPropertyName("react_settings")]
  public object? ReactSettings { get; set; }

  /// <summary>
  /// Determines whether the user owns this company
  /// </summary>
  [System.Text.Json.Serialization.JsonPropertyName("is_owner")]
  public bool? IsOwner { get; set; }

  /// <summary>
  /// Determines whether the user is the admin of this company
  /// </summary>
  [System.Text.Json.Serialization.JsonPropertyName("is_admin")]
  public bool? IsAdmin { get; set; }

  /// <summary>
  /// Determines whether the users access to this company has been locked
  /// </summary>
  [System.Text.Json.Serialization.JsonPropertyName("is_locked")]
  public bool? IsLocked { get; set; }

  /// <summary>
  /// The last time the record was modified, format Unix Timestamp
  /// </summary>
  [JsonConverter(typeof(UnixTimestampConverter))]
  [System.Text.Json.Serialization.JsonPropertyName("updated_at")]
  public DateTimeOffset? UpdatedAt { get; set; }

  /// <summary>
  /// Timestamp when the user was archived, format Unix Timestamp
  /// </summary>
  [JsonConverter(typeof(StringToIntegerConverter))]
  [System.Text.Json.Serialization.JsonPropertyName("deleted_at")]
  public int? DeletedAt { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("account")]
  public Account? Account { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("company")]
  public Company? Company { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("user")]
  public UserRef? User { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("token")]
  public CompanyToken? Token { get; set; }
}
