//
// <auto-generated>
// Invoice Ninja API Models - Auto-generated from OpenAPI specification
//
// Generated by: ApiGenerator
// Source: specs/invoiceninja.yaml
// API: Invoice Ninja API Reference.
// Version: 5.11.48
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
// </auto-generated>
//
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Text.Json;
using System.Text.Json.Serialization;

#nullable enable

namespace Apigen.InvoiceNinja.Models;

/// <summary>
/// Company from OpenAPI schema.
/// Schema path: #/components/schemas/Company
/// </summary>
public class Company
{
  /// <summary>
  /// The unique hashed identifier for the company
  /// </summary>
  [System.Text.Json.Serialization.JsonPropertyName("id")]
  public string? Id { get; set; }

  /// <summary>
  /// The unique identifier representing the company&apos;s size category
  /// </summary>
  [System.Text.Json.Serialization.JsonPropertyName("size_id")]
  public string? SizeId { get; set; }

  /// <summary>
  /// The unique identifier representing the company&apos;s industry category
  /// </summary>
  [System.Text.Json.Serialization.JsonPropertyName("industry_id")]
  public string? IndustryId { get; set; }

  /// <summary>
  /// The URL for the company&apos;s Slack webhook notifications
  /// </summary>
  [System.Text.Json.Serialization.JsonPropertyName("slack_webhook_url")]
  public string? SlackWebhookUrl { get; set; }

  /// <summary>
  /// The company&apos;s Google Analytics tracking ID
  /// </summary>
  [System.Text.Json.Serialization.JsonPropertyName("google_analytics_key")]
  public string? GoogleAnalyticsKey { get; set; }

  /// <summary>
  /// The mode determining how client-facing URLs are structured (e.g., subdomain, domain, or iframe)
  /// </summary>
  [System.Text.Json.Serialization.JsonPropertyName("portal_mode")]
  public string? PortalMode { get; set; }

  /// <summary>
  /// The subdomain prefix for the company&apos;s domain (e.g., &apos;acme&apos; in acme.domain.com)
  /// </summary>
  [System.Text.Json.Serialization.JsonPropertyName("subdomain")]
  public string? Subdomain { get; set; }

  /// <summary>
  /// The fully qualified domain used for client-facing URLs
  /// </summary>
  [System.Text.Json.Serialization.JsonPropertyName("portal_domain")]
  public string? PortalDomain { get; set; }

  /// <summary>
  /// The number of tax rates used per entity
  /// </summary>
  [JsonConverter(typeof(StringToIntegerConverter))]
  [System.Text.Json.Serialization.JsonPropertyName("enabled_tax_rates")]
  public int? EnabledTaxRates { get; set; }

  /// <summary>
  /// A flag determining whether to auto-fill product descriptions based on the product key
  /// </summary>
  [System.Text.Json.Serialization.JsonPropertyName("fill_products")]
  public bool? FillProducts { get; set; }

  /// <summary>
  /// A flag determining whether to convert products between different types or units
  /// </summary>
  [System.Text.Json.Serialization.JsonPropertyName("convert_products")]
  public bool? ConvertProducts { get; set; }

  /// <summary>
  /// A flag determining whether to update product descriptions when the description changes
  /// </summary>
  [System.Text.Json.Serialization.JsonPropertyName("update_products")]
  public bool? UpdateProducts { get; set; }

  /// <summary>
  /// A flag determining whether to display product details in the user interface
  /// </summary>
  [System.Text.Json.Serialization.JsonPropertyName("show_product_details")]
  public bool? ShowProductDetails { get; set; }

  /// <summary>
  /// A flag determining whether to display product cost is shown in the user interface
  /// </summary>
  [System.Text.Json.Serialization.JsonPropertyName("show_product_cost")]
  public bool? ShowProductCost { get; set; }

  /// <summary>
  /// A mapping of custom fields for various objects within the company
  /// 
  /// note**
  /// The custom fields object is formatted as follows
  /// 
  /// key : value
  /// entity(integer) : label|type
  /// 
  /// for example:
  /// &quot;company1&quot;: &quot;Number|single_line_text&quot;,
  /// 
  /// This defines the first company custom field, with label Number which has a custom field type of a single text line
  /// 
  /// Supported entity types
  /// 
  /// invoice
  /// product
  /// client
  /// contact
  /// task
  /// user
  /// project
  /// vendor
  /// expense
  /// payment
  /// 
  /// Supported input types values
  /// 
  /// single_line_text
  /// date
  /// switch
  /// 
  /// For text areas, you only need to supply the label ie &quot;TextArea&quot;, the | and type values are not required.
  /// For the dropdown the data format is as follows:
  /// 
  /// label|your,drop,down,values,in,comma,separated,format
  /// 
  /// </summary>
  [System.Text.Json.Serialization.JsonPropertyName("custom_fields")]
  public object? CustomFields { get; set; }

  /// <summary>
  /// A flag determining whether to show or hide the product cost field in the user interface
  /// </summary>
  [System.Text.Json.Serialization.JsonPropertyName("enable_product_cost")]
  public bool? EnableProductCost { get; set; }

  /// <summary>
  /// A flag determining whether to show or hide the product quantity field in the user interface
  /// </summary>
  [System.Text.Json.Serialization.JsonPropertyName("enable_product_quantity")]
  public bool? EnableProductQuantity { get; set; }

  /// <summary>
  /// A flag determining whether to use a default quantity for products
  /// </summary>
  [System.Text.Json.Serialization.JsonPropertyName("default_quantity")]
  public bool? DefaultQuantity { get; set; }

  /// <summary>
  /// A flag determining whether to apply taxes on custom surcharge amounts for the first custom surcharge field
  /// </summary>
  [System.Text.Json.Serialization.JsonPropertyName("custom_surcharge_taxes1")]
  public bool? CustomSurchargeTaxes1 { get; set; }

  /// <summary>
  /// A flag determining whether to apply taxes on custom surcharge amounts for the second custom surcharge field
  /// </summary>
  [System.Text.Json.Serialization.JsonPropertyName("custom_surcharge_taxes2")]
  public bool? CustomSurchargeTaxes2 { get; set; }

  /// <summary>
  /// A flag determining whether to apply taxes on custom surcharge amounts for the third custom surcharge field
  /// </summary>
  [System.Text.Json.Serialization.JsonPropertyName("custom_surcharge_taxes3")]
  public bool? CustomSurchargeTaxes3 { get; set; }

  /// <summary>
  /// A flag determining whether to apply taxes on custom surcharge amounts for the fourth custom
  /// </summary>
  [JsonConverter(typeof(StringToIntegerConverter))]
  [System.Text.Json.Serialization.JsonPropertyName("custom_surcharge_taxes4")]
  public int? CustomSurchargeTaxes4 { get; set; }

  /// <summary>
  /// The company logo file in binary format
  /// </summary>
  [System.Text.Json.Serialization.JsonPropertyName("logo")]
  public byte[]? Logo { get; set; }

  /// <summary>
  /// The static company key hash used to identify the Company
  /// </summary>
  [System.Text.Json.Serialization.JsonPropertyName("company_key")]
  public string? CompanyKey { get; set; }

  /// <summary>
  /// A flag determining whether clients can register for the client portal
  /// </summary>
  [System.Text.Json.Serialization.JsonPropertyName("client_can_register")]
  public bool? ClientCanRegister { get; set; }

  /// <summary>
  /// Bitmask representation of the modules that are enabled in the application
  /// 
  /// 
  /// self::ENTITY_RECURRING_INVOICE =&gt; 1,
  /// self::ENTITY_CREDIT =&gt; 2,
  /// self::ENTITY_QUOTE =&gt; 4,
  /// self::ENTITY_TASK =&gt; 8,
  /// self::ENTITY_EXPENSE =&gt; 16,
  /// self::ENTITY_PROJECT =&gt; 32,
  /// self::ENTITY_VENDOR =&gt; 64,
  /// self::ENTITY_TICKET =&gt; 128,
  /// self::ENTITY_PROPOSAL =&gt; 256,
  /// self::ENTITY_RECURRING_EXPENSE =&gt; 512,
  /// self::ENTITY_RECURRING_TASK =&gt; 1024,
  /// self::ENTITY_RECURRING_QUOTE =&gt; 2048,
  /// 
  /// 
  /// The default per_page value is 20.
  /// 
  /// </summary>
  [JsonConverter(typeof(StringToIntegerConverter))]
  [System.Text.Json.Serialization.JsonPropertyName("enabled_modules")]
  public int? EnabledModules { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("db")]
  public string? Db { get; set; }

  /// <summary>
  /// The first day of the week for the company
  /// </summary>
  [System.Text.Json.Serialization.JsonPropertyName("first_day_of_week")]
  public string? FirstDayOfWeek { get; set; }

  /// <summary>
  /// The first month for the company financial year
  /// </summary>
  [System.Text.Json.Serialization.JsonPropertyName("first_month_of_year")]
  public string? FirstMonthOfYear { get; set; }

  /// <summary>
  /// The number of tax rates used per item
  /// </summary>
  [JsonConverter(typeof(StringToIntegerConverter))]
  [System.Text.Json.Serialization.JsonPropertyName("enabled_item_tax_rates")]
  public int? EnabledItemTaxRates { get; set; }

  /// <summary>
  /// A flag determining whether the company is considered large
  /// </summary>
  [System.Text.Json.Serialization.JsonPropertyName("is_large")]
  public bool? IsLarge { get; set; }

  /// <summary>
  /// A flag determining whether to auto-bill clients by default
  /// 
  /// values:
  /// 
  /// always - Always auto bill
  /// disabled - Never auto bill
  /// optin - Allow the client to select their auto bill status with the default being disabled
  /// optout -Allow the client to select their auto bill status with the default being enabled
  /// 
  /// </summary>
  [System.Text.Json.Serialization.JsonPropertyName("default_auto_bill")]
  public string? DefaultAutoBill { get; set; }

  /// <summary>
  /// A flag determining whether to mark expenses as invoiceable by default
  /// </summary>
  [System.Text.Json.Serialization.JsonPropertyName("mark_expenses_invoiceable")]
  public bool? MarkExpensesInvoiceable { get; set; }

  /// <summary>
  /// A flag determining whether to mark expenses as paid by default
  /// </summary>
  [System.Text.Json.Serialization.JsonPropertyName("mark_expenses_paid")]
  public bool? MarkExpensesPaid { get; set; }

  /// <summary>
  /// A flag determining whether to include expense documents on invoices by default
  /// </summary>
  [System.Text.Json.Serialization.JsonPropertyName("invoice_expense_documents")]
  public bool? InvoiceExpenseDocuments { get; set; }

  /// <summary>
  /// A flag determining whether to auto-start tasks by default
  /// </summary>
  [System.Text.Json.Serialization.JsonPropertyName("auto_start_tasks")]
  public bool? AutoStartTasks { get; set; }

  /// <summary>
  /// A flag determining whether to include task time logs on invoices by default
  /// </summary>
  [System.Text.Json.Serialization.JsonPropertyName("invoice_task_timelog")]
  public bool? InvoiceTaskTimelog { get; set; }

  /// <summary>
  /// A flag determining whether to include task documents on invoices by default
  /// </summary>
  [System.Text.Json.Serialization.JsonPropertyName("invoice_task_documents")]
  public bool? InvoiceTaskDocuments { get; set; }

  /// <summary>
  /// A flag determining whether to show the tasks table on invoices by default
  /// </summary>
  [System.Text.Json.Serialization.JsonPropertyName("show_tasks_table")]
  public bool? ShowTasksTable { get; set; }

  /// <summary>
  /// A flag determining whether the company is disabled
  /// </summary>
  [System.Text.Json.Serialization.JsonPropertyName("is_disabled")]
  public bool? IsDisabled { get; set; }

  /// <summary>
  /// A flag determining whether to default tasks to be date-based
  /// </summary>
  [System.Text.Json.Serialization.JsonPropertyName("default_task_is_date_based")]
  public bool? DefaultTaskIsDateBased { get; set; }

  /// <summary>
  /// A flag determining whether to show or hide the product discount field in the user interface
  /// </summary>
  [System.Text.Json.Serialization.JsonPropertyName("enable_product_discount")]
  public bool? EnableProductDiscount { get; set; }

  /// <summary>
  /// A flag determining whether to calculate expense taxes by amount
  /// </summary>
  [System.Text.Json.Serialization.JsonPropertyName("calculate_expense_tax_by_amount")]
  public bool? CalculateExpenseTaxByAmount { get; set; }

  /// <summary>
  /// A flag determining whether to include taxes in the expense amount
  /// </summary>
  [System.Text.Json.Serialization.JsonPropertyName("expense_inclusive_taxes")]
  public bool? ExpenseInclusiveTaxes { get; set; }

  /// <summary>
  /// The session timeout for the company
  /// </summary>
  [JsonConverter(typeof(StringToIntegerConverter))]
  [System.Text.Json.Serialization.JsonPropertyName("session_timeout")]
  public int? SessionTimeout { get; set; }

  /// <summary>
  /// A flag determining whether to require a password for dangerous actions when using OAuth
  /// </summary>
  [System.Text.Json.Serialization.JsonPropertyName("oauth_password_required")]
  public bool? OauthPasswordRequired { get; set; }

  /// <summary>
  /// A flag determining whether to include task date logs on invoices by default
  /// </summary>
  [System.Text.Json.Serialization.JsonPropertyName("invoice_task_datelog")]
  public bool? InvoiceTaskDatelog { get; set; }

  /// <summary>
  /// The default password timeout for the company
  /// </summary>
  [JsonConverter(typeof(StringToIntegerConverter))]
  [System.Text.Json.Serialization.JsonPropertyName("default_password_timeout")]
  public int? DefaultPasswordTimeout { get; set; }

  /// <summary>
  /// A flag determining whether to show the task end date on invoices by default
  /// </summary>
  [System.Text.Json.Serialization.JsonPropertyName("show_task_end_date")]
  public bool? ShowTaskEndDate { get; set; }

  /// <summary>
  /// A flag determining whether markdown is enabled for the company
  /// </summary>
  [System.Text.Json.Serialization.JsonPropertyName("markdown_enabled")]
  public bool? MarkdownEnabled { get; set; }

  /// <summary>
  /// A flag determining whether to include draft invoices in reports
  /// </summary>
  [System.Text.Json.Serialization.JsonPropertyName("report_include_drafts")]
  public bool? ReportIncludeDrafts { get; set; }

  /// <summary>
  /// The client registration fields for the company
  /// </summary>
  [System.Text.Json.Serialization.JsonPropertyName("client_registration_fields")]
  public object? ClientRegistrationFields { get; set; }

  /// <summary>
  /// A flag determining whether to stop recurring invoices when they are unpaid
  /// </summary>
  [System.Text.Json.Serialization.JsonPropertyName("stop_on_unpaid_recurring")]
  public bool? StopOnUnpaidRecurring { get; set; }

  /// <summary>
  /// A flag determining whether to use quote terms on conversion to an invoice
  /// </summary>
  [System.Text.Json.Serialization.JsonPropertyName("use_quote_terms_on_conversion")]
  public bool? UseQuoteTermsOnConversion { get; set; }

  /// <summary>
  /// A flag determining whether to enable applying payments to invoices
  /// </summary>
  [System.Text.Json.Serialization.JsonPropertyName("enable_applying_payments")]
  public bool? EnableApplyingPayments { get; set; }

  /// <summary>
  /// A flag determining whether to track inventory for the company
  /// </summary>
  [System.Text.Json.Serialization.JsonPropertyName("track_inventory")]
  public bool? TrackInventory { get; set; }

  /// <summary>
  /// The inventory notification threshold for the company
  /// </summary>
  [JsonConverter(typeof(StringToIntegerConverter))]
  [System.Text.Json.Serialization.JsonPropertyName("inventory_notification_threshold")]
  public int? InventoryNotificationThreshold { get; set; }

  /// <summary>
  /// A flag determining whether to send stock notifications for the company
  /// </summary>
  [System.Text.Json.Serialization.JsonPropertyName("stock_notification")]
  public bool? StockNotification { get; set; }

  /// <summary>
  /// The Matomo URL for the company
  /// </summary>
  [System.Text.Json.Serialization.JsonPropertyName("matomo_url")]
  public string? MatomoUrl { get; set; }

  /// <summary>
  /// The Matomo ID for the company
  /// </summary>
  [System.Text.Json.Serialization.JsonPropertyName("matomo_id")]
  public string? MatomoId { get; set; }

  /// <summary>
  /// The number of tax rates used per expense
  /// </summary>
  [JsonConverter(typeof(StringToIntegerConverter))]
  [System.Text.Json.Serialization.JsonPropertyName("enabled_expense_tax_rates")]
  public int? EnabledExpenseTaxRates { get; set; }

  /// <summary>
  /// A flag determining whether to include the project on invoices by default
  /// </summary>
  [System.Text.Json.Serialization.JsonPropertyName("invoice_task_project")]
  public bool? InvoiceTaskProject { get; set; }

  /// <summary>
  /// A flag determining whether to include deleted invoices in reports
  /// </summary>
  [System.Text.Json.Serialization.JsonPropertyName("report_include_deleted")]
  public bool? ReportIncludeDeleted { get; set; }

  /// <summary>
  /// A flag determining whether to lock tasks when invoiced
  /// </summary>
  [System.Text.Json.Serialization.JsonPropertyName("invoice_task_lock")]
  public bool? InvoiceTaskLock { get; set; }

  /// <summary>
  /// A flag determining whether to convert the payment currency
  /// </summary>
  [System.Text.Json.Serialization.JsonPropertyName("convert_payment_currency")]
  public bool? ConvertPaymentCurrency { get; set; }

  /// <summary>
  /// A flag determining whether to convert the expense currency
  /// </summary>
  [System.Text.Json.Serialization.JsonPropertyName("convert_expense_currency")]
  public bool? ConvertExpenseCurrency { get; set; }

  /// <summary>
  /// A flag determining whether to notify the vendor when an expense is paid
  /// </summary>
  [System.Text.Json.Serialization.JsonPropertyName("notify_vendor_when_paid")]
  public bool? NotifyVendorWhenPaid { get; set; }

  /// <summary>
  /// A flag determining whether to include the task hours on invoices by default
  /// </summary>
  [System.Text.Json.Serialization.JsonPropertyName("invoice_task_hours")]
  public bool? InvoiceTaskHours { get; set; }

  /// <summary>
  /// A flag determining whether to calculate taxes for the company
  /// </summary>
  [System.Text.Json.Serialization.JsonPropertyName("calculate_taxes")]
  public bool? CalculateTaxes { get; set; }

  /// <summary>
  /// The tax data for the company
  /// </summary>
  [System.Text.Json.Serialization.JsonPropertyName("tax_data")]
  public object? TaxData { get; set; }

  /// <summary>
  /// The e-invoice certificate for the company
  /// </summary>
  [System.Text.Json.Serialization.JsonPropertyName("e_invoice_certificate")]
  public string? EInvoiceCertificate { get; set; }

  /// <summary>
  /// The e-invoice certificate passphrase for the company
  /// </summary>
  [System.Text.Json.Serialization.JsonPropertyName("e_invoice_certificate_passphrase")]
  public string? EInvoiceCertificatePassphrase { get; set; }

  /// <summary>
  /// The origin tax data for the company
  /// </summary>
  [System.Text.Json.Serialization.JsonPropertyName("origin_tax_data")]
  public object? OriginTaxData { get; set; }

  /// <summary>
  /// A flag determining whether to include the project header on invoices by default
  /// </summary>
  [System.Text.Json.Serialization.JsonPropertyName("invoice_task_project_header")]
  public bool? InvoiceTaskProjectHeader { get; set; }

  /// <summary>
  /// A flag determining whether to include the item description on invoices by default
  /// </summary>
  [System.Text.Json.Serialization.JsonPropertyName("invoice_task_item_description")]
  public bool? InvoiceTaskItemDescription { get; set; }

  /// <summary>
  /// The email address for the expense mailbox
  /// </summary>
  [System.Text.Json.Serialization.JsonPropertyName("expense_mailbox")]
  public string? ExpenseMailbox { get; set; }

  /// <summary>
  /// Whether the expense mailbox is active
  /// </summary>
  [System.Text.Json.Serialization.JsonPropertyName("expense_mailbox_active")]
  public bool? ExpenseMailboxActive { get; set; }

  /// <summary>
  /// Whether company users are allowed to use the inbound mailbox
  /// </summary>
  [System.Text.Json.Serialization.JsonPropertyName("inbound_mailbox_allow_company_users")]
  public bool? InboundMailboxAllowCompanyUsers { get; set; }

  /// <summary>
  /// Whether vendors are allowed to use the inbound mailbox
  /// </summary>
  [System.Text.Json.Serialization.JsonPropertyName("inbound_mailbox_allow_vendors")]
  public bool? InboundMailboxAllowVendors { get; set; }

  /// <summary>
  /// Whether clients are allowed to use the inbound mailbox
  /// </summary>
  [System.Text.Json.Serialization.JsonPropertyName("inbound_mailbox_allow_clients")]
  public bool? InboundMailboxAllowClients { get; set; }

  /// <summary>
  /// Whether unknown senders are allowed to use the inbound mailbox
  /// </summary>
  [System.Text.Json.Serialization.JsonPropertyName("inbound_mailbox_allow_unknown")]
  public bool? InboundMailboxAllowUnknown { get; set; }

  /// <summary>
  /// Comma-separated list of whitelisted email addresses for the inbound mailbox
  /// </summary>
  [System.Text.Json.Serialization.JsonPropertyName("inbound_mailbox_whitelist")]
  public string? InboundMailboxWhitelist { get; set; }

  /// <summary>
  /// Comma-separated list of blacklisted email addresses for the inbound mailbox
  /// </summary>
  [System.Text.Json.Serialization.JsonPropertyName("inbound_mailbox_blacklist")]
  public string? InboundMailboxBlacklist { get; set; }

  /// <summary>
  /// The SMTP host for sending emails
  /// </summary>
  [System.Text.Json.Serialization.JsonPropertyName("smtp_host")]
  public string? SmtpHost { get; set; }

  /// <summary>
  /// The SMTP port for sending emails
  /// </summary>
  [JsonConverter(typeof(StringToIntegerConverter))]
  [System.Text.Json.Serialization.JsonPropertyName("smtp_port")]
  public int? SmtpPort { get; set; }

  /// <summary>
  /// The encryption method for SMTP
  /// </summary>
  [System.Text.Json.Serialization.JsonPropertyName("smtp_encryption")]
  public string? SmtpEncryption { get; set; }

  /// <summary>
  /// The local domain for SMTP
  /// </summary>
  [System.Text.Json.Serialization.JsonPropertyName("smtp_local_domain")]
  public string? SmtpLocalDomain { get; set; }

  /// <summary>
  /// Whether to verify the SMTP peer
  /// </summary>
  [System.Text.Json.Serialization.JsonPropertyName("smtp_verify_peer")]
  public bool? SmtpVerifyPeer { get; set; }

  /// <summary>
  /// E-invoice settings for the company
  /// </summary>
  [System.Text.Json.Serialization.JsonPropertyName("e_invoice")]
  public object? EInvoice { get; set; }

  /// <summary>
  /// The ID of the legal entity associated with the company
  /// </summary>
  [JsonConverter(typeof(StringToIntegerConverter))]
  [System.Text.Json.Serialization.JsonPropertyName("legal_entity_id")]
  public int? LegalEntityId { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("settings")]
  public CompanySettings? Settings { get; set; }
}
