//
// <auto-generated>
// Invoice Ninja API Models - Auto-generated from OpenAPI specification
//
// Generated by: ApiGenerator
// Source: specs/invoiceninja.yaml
// API: Invoice Ninja API Reference.
// Version: 5.12.55
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
// </auto-generated>
//
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Text.Json;
using System.Text.Json.Serialization;

#nullable enable

namespace Apigen.InvoiceNinja.Models;

/// <summary>
/// CreditInvitation from OpenAPI schema.
/// Schema path: #/components/schemas/CreditInvitation
/// </summary>
public partial class CreditInvitation
{
  /// <summary>
  /// The entity invitation hashed id
  /// </summary>
  [System.Text.Json.Serialization.JsonPropertyName("id")]
  public string? Id { get; set; }

  /// <summary>
  /// The client contact hashed id
  /// </summary>
  [System.Text.Json.Serialization.JsonPropertyName("client_contact_id")]
  public string? ClientContactId { get; set; }

  /// <summary>
  /// The invitation key
  /// </summary>
  [System.Text.Json.Serialization.JsonPropertyName("key")]
  public string? Key { get; set; }

  /// <summary>
  /// The invitation link
  /// </summary>
  [System.Text.Json.Serialization.JsonPropertyName("link")]
  public string? Link { get; set; }

  /// <summary>
  /// The invitation sent date
  /// </summary>
  [System.Text.Json.Serialization.JsonPropertyName("sent_date")]
  public DateTime? SentDate { get; set; }

  /// <summary>
  /// The invitation viewed date
  /// </summary>
  [System.Text.Json.Serialization.JsonPropertyName("viewed_date")]
  public DateTime? ViewedDate { get; set; }

  /// <summary>
  /// The invitation opened date
  /// </summary>
  [System.Text.Json.Serialization.JsonPropertyName("opened_date")]
  public DateTime? OpenedDate { get; set; }

  /// <summary>
  /// Timestamp
  /// </summary>
  [JsonConverter(typeof(UnixTimestampConverter))]
  [System.Text.Json.Serialization.JsonPropertyName("updated_at")]
  public DateTimeOffset? UpdatedAt { get; set; }

  /// <summary>
  /// Timestamp
  /// </summary>
  [JsonConverter(typeof(UnixTimestampConverter))]
  [System.Text.Json.Serialization.JsonPropertyName("archived_at")]
  public DateTimeOffset? ArchivedAt { get; set; }

  /// <summary>
  /// The email error
  /// </summary>
  [System.Text.Json.Serialization.JsonPropertyName("email_error")]
  public string? EmailError { get; set; }

  /// <summary>
  /// The email status
  /// </summary>
  [System.Text.Json.Serialization.JsonPropertyName("email_status")]
  public string? EmailStatus { get; set; }
}
