//
// <auto-generated>
// Invoice Ninja API Models - Auto-generated from OpenAPI specification
//
// Generated by: ApiGenerator
// Source: specs/invoiceninja.yaml
// API: Invoice Ninja API Reference.
// Version: 5.12.55
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
// </auto-generated>
//
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Text.Json;
using System.Text.Json.Serialization;

#nullable enable

namespace Apigen.InvoiceNinja.Models;

/// <summary>
/// CreditPaymentable from OpenAPI schema.
/// Schema path: #/components/schemas/CreditPaymentable
/// </summary>
public partial class CreditPaymentable
{
  /// <summary>
  /// The credit hashed id
  /// </summary>
  [System.Text.Json.Serialization.JsonPropertyName("credit_id")]
  public string? CreditId { get; set; }

  /// <summary>
  /// The credit amount
  /// </summary>
  [JsonConverter(typeof(EmptyStringToNullableDecimalConverter))]
  [System.Text.Json.Serialization.JsonPropertyName("amount")]
  public decimal? Amount { get; set; }
}
