//
// <auto-generated>
// Invoice Ninja API Models - Auto-generated from OpenAPI specification
//
// Generated by: ApiGenerator
// Source: specs/invoiceninja.yaml
// API: Invoice Ninja API Reference.
// Version: 5.12.55
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
// </auto-generated>
//
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Text.Json;
using System.Text.Json.Serialization;

#nullable enable

namespace Apigen.InvoiceNinja.Models;

/// <summary>
/// Design from OpenAPI schema.
/// Schema path: #/components/schemas/Design
/// </summary>
public partial class Design
{
  /// <summary>
  /// The design hashed id
  /// </summary>
  [System.Text.Json.Serialization.JsonPropertyName("id")]
  public string? Id { get; set; }

  /// <summary>
  /// The design name
  /// </summary>
  [System.Text.Json.Serialization.JsonPropertyName("name")]
  public string? Name { get; set; }

  /// <summary>
  /// The design HTML
  /// </summary>
  [System.Text.Json.Serialization.JsonPropertyName("design")]
  public string? DesignValue { get; set; }

  /// <summary>
  /// Flag to determine if the design is a custom user design
  /// </summary>
  [System.Text.Json.Serialization.JsonPropertyName("is_custom")]
  public bool? IsCustom { get; set; }

  /// <summary>
  /// Flag to determine if the design is available for use
  /// </summary>
  [System.Text.Json.Serialization.JsonPropertyName("is_active")]
  public bool? IsActive { get; set; }

  /// <summary>
  /// Flag to determine if the design is deleted
  /// </summary>
  [System.Text.Json.Serialization.JsonPropertyName("is_deleted")]
  public bool? IsDeleted { get; set; }

  /// <summary>
  /// Timestamp
  /// </summary>
  [JsonConverter(typeof(UnixTimestampConverter))]
  [System.Text.Json.Serialization.JsonPropertyName("created_at")]
  public DateTimeOffset? CreatedAt { get; set; }

  /// <summary>
  /// Timestamp
  /// </summary>
  [JsonConverter(typeof(UnixTimestampConverter))]
  [System.Text.Json.Serialization.JsonPropertyName("updated_at")]
  public DateTimeOffset? UpdatedAt { get; set; }

  /// <summary>
  /// Timestamp
  /// </summary>
  [JsonConverter(typeof(UnixTimestampConverter))]
  [System.Text.Json.Serialization.JsonPropertyName("deleted_at")]
  public DateTimeOffset? DeletedAt { get; set; }
}
