//
// <auto-generated>
// Invoice Ninja API Models - Auto-generated from OpenAPI specification
//
// Generated by: ApiGenerator
// Source: specs/invoiceninja.yaml
// API: Invoice Ninja API Reference.
// Version: 5.12.55
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
// </auto-generated>
//
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Text.Json;
using System.Text.Json.Serialization;

#nullable enable

namespace Apigen.InvoiceNinja.Models;

/// <summary>
/// Document from OpenAPI schema.
/// Schema path: #/components/schemas/Document
/// </summary>
public class Document
{
  /// <summary>
  /// The document hashed id
  /// </summary>
  [System.Text.Json.Serialization.JsonPropertyName("id")]
  public string? Id { get; set; }

  /// <summary>
  /// The user hashed id
  /// </summary>
  [System.Text.Json.Serialization.JsonPropertyName("user_id")]
  public string? UserId { get; set; }

  /// <summary>
  /// The assigned user hashed id
  /// </summary>
  [System.Text.Json.Serialization.JsonPropertyName("assigned_user_id")]
  public string? AssignedUserId { get; set; }

  /// <summary>
  /// The project associated with this document
  /// </summary>
  [System.Text.Json.Serialization.JsonPropertyName("project_id")]
  public string? ProjectId { get; set; }

  /// <summary>
  /// The vendor associated with this documents
  /// </summary>
  [System.Text.Json.Serialization.JsonPropertyName("vendor_id")]
  public string? VendorId { get; set; }

  /// <summary>
  /// The document name
  /// </summary>
  [System.Text.Json.Serialization.JsonPropertyName("name")]
  public string? Name { get; set; }

  /// <summary>
  /// The document url
  /// </summary>
  [System.Text.Json.Serialization.JsonPropertyName("url")]
  public string? Url { get; set; }

  /// <summary>
  /// The document preview url
  /// </summary>
  [System.Text.Json.Serialization.JsonPropertyName("preview")]
  public string? Preview { get; set; }

  /// <summary>
  /// The document type
  /// </summary>
  [System.Text.Json.Serialization.JsonPropertyName("type")]
  public string? Type { get; set; }

  /// <summary>
  /// The document disk
  /// </summary>
  [System.Text.Json.Serialization.JsonPropertyName("disk")]
  public string? Disk { get; set; }

  /// <summary>
  /// The document hashed
  /// </summary>
  [System.Text.Json.Serialization.JsonPropertyName("hash")]
  public string? Hash { get; set; }

  /// <summary>
  /// Flag to determine if the document is deleted
  /// </summary>
  [System.Text.Json.Serialization.JsonPropertyName("is_deleted")]
  public bool? IsDeleted { get; set; }

  /// <summary>
  /// Flag to determine if the document is a default doc
  /// </summary>
  [System.Text.Json.Serialization.JsonPropertyName("is_default")]
  public bool? IsDefault { get; set; }

  /// <summary>
  /// Timestamp
  /// </summary>
  [JsonConverter(typeof(UnixTimestampConverter))]
  [System.Text.Json.Serialization.JsonPropertyName("created_at")]
  public DateTimeOffset? CreatedAt { get; set; }

  /// <summary>
  /// Timestamp
  /// </summary>
  [JsonConverter(typeof(UnixTimestampConverter))]
  [System.Text.Json.Serialization.JsonPropertyName("updated_at")]
  public DateTimeOffset? UpdatedAt { get; set; }

  /// <summary>
  /// Timestamp
  /// </summary>
  [JsonConverter(typeof(UnixTimestampConverter))]
  [System.Text.Json.Serialization.JsonPropertyName("deleted_at")]
  public DateTimeOffset? DeletedAt { get; set; }
}
