//
// <auto-generated>
// Invoice Ninja API Models - Auto-generated from OpenAPI specification
//
// Generated by: ApiGenerator
// Source: specs/invoiceninja.yaml
// API: Invoice Ninja API Reference.
// Version: 5.12.55
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
// </auto-generated>
//
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Text.Json;
using System.Text.Json.Serialization;

#nullable enable

namespace Apigen.InvoiceNinja.Models;

/// <summary>
/// Error from OpenAPI schema.
/// Schema path: #/components/schemas/Error
/// </summary>
public partial class Error
{
  /// <summary>
  /// Something terrible went wrong
  /// </summary>
  [System.Text.Json.Serialization.JsonPropertyName("message")]
  public string? Message { get; set; }

  /// <summary>
  /// The HTTP error code, ie 5xx 4xx
  /// </summary>
  [JsonConverter(typeof(StringToIntegerConverter))]
  [System.Text.Json.Serialization.JsonPropertyName("code")]
  public int? Code { get; set; }
}
