//
// <auto-generated>
// Invoice Ninja API Models - Auto-generated from OpenAPI specification
//
// Generated by: ApiGenerator
// Source: specs/invoiceninja.yaml
// API: Invoice Ninja API Reference.
// Version: 5.11.48
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
// </auto-generated>
//
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Text.Json;
using System.Text.Json.Serialization;

#nullable enable

namespace Apigen.InvoiceNinja.Models;

/// <summary>
/// Expense from OpenAPI schema.
/// Schema path: #/components/schemas/Expense
/// </summary>
public class Expense
{
  /// <summary>
  /// The expense hashed id
  /// </summary>
  [System.Text.Json.Serialization.JsonPropertyName("id")]
  public string? Id { get; set; }

  /// <summary>
  /// The user hashed id
  /// </summary>
  [System.Text.Json.Serialization.JsonPropertyName("user_id")]
  public string? UserId { get; set; }

  /// <summary>
  /// The assigned user hashed id
  /// </summary>
  [System.Text.Json.Serialization.JsonPropertyName("assigned_user_id")]
  public string? AssignedUserId { get; set; }

  /// <summary>
  /// The associated project_id
  /// </summary>
  [System.Text.Json.Serialization.JsonPropertyName("project_id")]
  public string? ProjectId { get; set; }

  /// <summary>
  /// The client hashed id
  /// </summary>
  [System.Text.Json.Serialization.JsonPropertyName("client_id")]
  public string? ClientId { get; set; }

  /// <summary>
  /// The related invoice hashed id
  /// </summary>
  [System.Text.Json.Serialization.JsonPropertyName("invoice_id")]
  public string? InvoiceId { get; set; }

  /// <summary>
  /// The bank id related to this expense
  /// </summary>
  [System.Text.Json.Serialization.JsonPropertyName("bank_id")]
  public string? BankId { get; set; }

  /// <summary>
  /// The currency id of the related invoice
  /// </summary>
  [System.Text.Json.Serialization.JsonPropertyName("invoice_currency_id")]
  public string? InvoiceCurrencyId { get; set; }

  /// <summary>
  /// The currency id of the expense
  /// </summary>
  [System.Text.Json.Serialization.JsonPropertyName("currency_id")]
  public string? CurrencyId { get; set; }

  /// <summary>
  /// The invoice category id
  /// </summary>
  [System.Text.Json.Serialization.JsonPropertyName("invoice_category_id")]
  public string? InvoiceCategoryId { get; set; }

  /// <summary>
  /// The payment type id
  /// </summary>
  [System.Text.Json.Serialization.JsonPropertyName("payment_type_id")]
  public string? PaymentTypeId { get; set; }

  /// <summary>
  /// The related recurring expense this expense was created from
  /// </summary>
  [System.Text.Json.Serialization.JsonPropertyName("recurring_expense_id")]
  public string? RecurringExpenseId { get; set; }

  /// <summary>
  /// The private notes of the expense
  /// </summary>
  [System.Text.Json.Serialization.JsonPropertyName("private_notes")]
  public string? PrivateNotes { get; set; }

  /// <summary>
  /// The public notes of the expense
  /// </summary>
  [System.Text.Json.Serialization.JsonPropertyName("public_notes")]
  public string? PublicNotes { get; set; }

  /// <summary>
  /// The transaction references of the expense
  /// </summary>
  [System.Text.Json.Serialization.JsonPropertyName("transaction_reference")]
  public string? TransactionReference { get; set; }

  /// <summary>
  /// The transaction id of the expense
  /// </summary>
  [System.Text.Json.Serialization.JsonPropertyName("transcation_id")]
  public string? TranscationId { get; set; }

  /// <summary>
  /// A custom value
  /// </summary>
  [System.Text.Json.Serialization.JsonPropertyName("custom_value1")]
  public string? CustomValue1 { get; set; }

  /// <summary>
  /// A custom value
  /// </summary>
  [System.Text.Json.Serialization.JsonPropertyName("custom_value2")]
  public string? CustomValue2 { get; set; }

  /// <summary>
  /// A custom value
  /// </summary>
  [System.Text.Json.Serialization.JsonPropertyName("custom_value3")]
  public string? CustomValue3 { get; set; }

  /// <summary>
  /// A custom value
  /// </summary>
  [System.Text.Json.Serialization.JsonPropertyName("custom_value4")]
  public string? CustomValue4 { get; set; }

  /// <summary>
  /// The tax amount
  /// </summary>
  [JsonConverter(typeof(EmptyStringToNullableDecimalConverter))]
  [System.Text.Json.Serialization.JsonPropertyName("tax_amount")]
  public decimal? TaxAmount { get; set; }

  /// <summary>
  /// Tax Name 1
  /// </summary>
  [System.Text.Json.Serialization.JsonPropertyName("tax_name1")]
  public string? TaxName1 { get; set; }

  /// <summary>
  /// Tax Name 2
  /// </summary>
  [System.Text.Json.Serialization.JsonPropertyName("tax_name2")]
  public string? TaxName2 { get; set; }

  /// <summary>
  /// Tax Name 3
  /// </summary>
  [System.Text.Json.Serialization.JsonPropertyName("tax_name3")]
  public string? TaxName3 { get; set; }

  /// <summary>
  /// Tax rate 1
  /// </summary>
  [System.Text.Json.Serialization.JsonPropertyName("tax_rate1")]
  public float? TaxRate1 { get; set; }

  /// <summary>
  /// Tax rate 2
  /// </summary>
  [System.Text.Json.Serialization.JsonPropertyName("tax_rate2")]
  public float? TaxRate2 { get; set; }

  /// <summary>
  /// Tax rate 3
  /// </summary>
  [System.Text.Json.Serialization.JsonPropertyName("tax_rate3")]
  public float? TaxRate3 { get; set; }

  /// <summary>
  /// The total expense amont
  /// </summary>
  [JsonConverter(typeof(EmptyStringToNullableDecimalConverter))]
  [System.Text.Json.Serialization.JsonPropertyName("amount")]
  public decimal? Amount { get; set; }

  /// <summary>
  /// The total foreign amount of the expense
  /// </summary>
  [JsonConverter(typeof(EmptyStringToNullableDecimalConverter))]
  [System.Text.Json.Serialization.JsonPropertyName("foreign_amount")]
  public decimal? ForeignAmount { get; set; }

  /// <summary>
  /// The exchange rate at the time of the expense
  /// </summary>
  [JsonConverter(typeof(EmptyStringToNullableDecimalConverter))]
  [System.Text.Json.Serialization.JsonPropertyName("exchange_rate")]
  public decimal? ExchangeRate { get; set; }

  /// <summary>
  /// The expense date format Y-m-d
  /// </summary>
  [System.Text.Json.Serialization.JsonPropertyName("date")]
  public string? Date { get; set; }

  /// <summary>
  /// The date of payment for the expense, format Y-m-d
  /// </summary>
  [System.Text.Json.Serialization.JsonPropertyName("payment_date")]
  public string? PaymentDate { get; set; }

  /// <summary>
  /// Flag whether the expense should be invoiced
  /// </summary>
  [System.Text.Json.Serialization.JsonPropertyName("should_be_invoiced")]
  public bool? ShouldBeInvoiced { get; set; }

  /// <summary>
  /// Boolean determining whether the expense has been deleted
  /// </summary>
  [System.Text.Json.Serialization.JsonPropertyName("is_deleted")]
  public bool? IsDeleted { get; set; }

  /// <summary>
  /// Passing the expense documents over to the invoice
  /// </summary>
  [System.Text.Json.Serialization.JsonPropertyName("invoice_documents")]
  public bool? InvoiceDocuments { get; set; }

  /// <summary>
  /// Timestamp
  /// </summary>
  [JsonConverter(typeof(UnixTimestampConverter))]
  [System.Text.Json.Serialization.JsonPropertyName("updated_at")]
  public DateTimeOffset? UpdatedAt { get; set; }

  /// <summary>
  /// Timestamp
  /// </summary>
  [JsonConverter(typeof(UnixTimestampConverter))]
  [System.Text.Json.Serialization.JsonPropertyName("archived_at")]
  public DateTimeOffset? ArchivedAt { get; set; }
}
