//
// <auto-generated>
// Invoice Ninja API Models - Auto-generated from OpenAPI specification
//
// Generated by: ApiGenerator
// Source: specs/invoiceninja.yaml
// API: Invoice Ninja API Reference.
// Version: 5.12.55
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
// </auto-generated>
//
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Text.Json;
using System.Text.Json.Serialization;

#nullable enable

namespace Apigen.InvoiceNinja.Models;

/// <summary>
/// GetRecurringInvoiceReportRequest from OpenAPI schema.
/// Schema path: #/components/schemas/GetRecurringInvoiceReportRequest
/// </summary>
public class GetRecurringInvoiceReportRequest
{
  /// <summary>
  /// The string representation of the date range of data to be returned
  /// </summary>
  [System.Text.Json.Serialization.JsonIgnore(Condition = System.Text.Json.Serialization.JsonIgnoreCondition.WhenWritingNull)]
  [System.Text.Json.Serialization.JsonPropertyName("date_range")]
  public string? DateRange { get; set; }

  /// <summary>
  /// The date column to search between.
  /// </summary>
  [System.Text.Json.Serialization.JsonIgnore(Condition = System.Text.Json.Serialization.JsonIgnoreCondition.WhenWritingNull)]
  [System.Text.Json.Serialization.JsonPropertyName("date_key")]
  public string? DateKey { get; set; }

  /// <summary>
  /// The start date to search between
  /// </summary>
  [JsonConverter(typeof(EmptyStringToDateOnlyConverter))]
  [System.Text.Json.Serialization.JsonIgnore(Condition = System.Text.Json.Serialization.JsonIgnoreCondition.WhenWritingNull)]
  [System.Text.Json.Serialization.JsonPropertyName("start_date")]
  public DateOnly? StartDate { get; set; }

  /// <summary>
  /// The end date to search between
  /// </summary>
  [JsonConverter(typeof(EmptyStringToDateOnlyConverter))]
  [System.Text.Json.Serialization.JsonIgnore(Condition = System.Text.Json.Serialization.JsonIgnoreCondition.WhenWritingNull)]
  [System.Text.Json.Serialization.JsonPropertyName("end_date")]
  public DateOnly? EndDate { get; set; }

  [System.Text.Json.Serialization.JsonIgnore(Condition = System.Text.Json.Serialization.JsonIgnoreCondition.WhenWritingNull)]
  [System.Text.Json.Serialization.JsonPropertyName("report_keys")]
  public List<string?>? ReportKeys { get; set; }
}
