//
// <auto-generated>
// Invoice Ninja API Models - Auto-generated from OpenAPI specification
//
// Generated by: ApiGenerator
// Source: specs/invoiceninja.yaml
// API: Invoice Ninja API Reference.
// Version: 5.11.48
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
// </auto-generated>
//
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Text.Json;
using System.Text.Json.Serialization;

#nullable enable

namespace Apigen.InvoiceNinja.Models;

/// <summary>
/// Invoice from OpenAPI schema.
/// Schema path: #/components/schemas/Invoice
/// </summary>
public class Invoice
{
  /// <summary>
  /// The invoice hashed id
  /// </summary>
  [System.Text.Json.Serialization.JsonPropertyName("id")]
  public string? Id { get; set; }

  /// <summary>
  /// The user hashed id
  /// </summary>
  [System.Text.Json.Serialization.JsonPropertyName("user_id")]
  public string? UserId { get; set; }

  /// <summary>
  /// The assigned user hashed id
  /// </summary>
  [System.Text.Json.Serialization.JsonPropertyName("assigned_user_id")]
  public string? AssignedUserId { get; set; }

  /// <summary>
  /// The client hashed id
  /// </summary>
  [System.Text.Json.Serialization.JsonPropertyName("client_id")]
  public string? ClientId { get; set; }

  /// <summary>
  /// The invoice status variable
  /// </summary>
  [System.Text.Json.Serialization.JsonPropertyName("status_id")]
  public string? StatusId { get; set; }

  /// <summary>
  /// The invoice number - is a unique alpha numeric number per invoice per company
  /// </summary>
  [System.Text.Json.Serialization.JsonPropertyName("number")]
  public string? Number { get; set; }

  /// <summary>
  /// The purchase order associated with this invoice
  /// </summary>
  [System.Text.Json.Serialization.JsonPropertyName("po_number")]
  public string? PoNumber { get; set; }

  /// <summary>
  /// The invoice terms
  /// </summary>
  [System.Text.Json.Serialization.JsonPropertyName("terms")]
  public string? Terms { get; set; }

  /// <summary>
  /// The public notes of the invoice
  /// </summary>
  [System.Text.Json.Serialization.JsonPropertyName("public_notes")]
  public string? PublicNotes { get; set; }

  /// <summary>
  /// The private notes of the invoice
  /// </summary>
  [System.Text.Json.Serialization.JsonPropertyName("private_notes")]
  public string? PrivateNotes { get; set; }

  /// <summary>
  /// The invoice footer notes
  /// </summary>
  [System.Text.Json.Serialization.JsonPropertyName("footer")]
  public string? Footer { get; set; }

  /// <summary>
  /// A custom field value
  /// </summary>
  [System.Text.Json.Serialization.JsonPropertyName("custom_value1")]
  public string? CustomValue1 { get; set; }

  /// <summary>
  /// A custom field value
  /// </summary>
  [System.Text.Json.Serialization.JsonPropertyName("custom_value2")]
  public string? CustomValue2 { get; set; }

  /// <summary>
  /// A custom field value
  /// </summary>
  [System.Text.Json.Serialization.JsonPropertyName("custom_value3")]
  public string? CustomValue3 { get; set; }

  /// <summary>
  /// A custom field value
  /// </summary>
  [System.Text.Json.Serialization.JsonPropertyName("custom_value4")]
  public string? CustomValue4 { get; set; }

  /// <summary>
  /// The tax name
  /// </summary>
  [System.Text.Json.Serialization.JsonPropertyName("tax_name1")]
  public string? TaxName1 { get; set; }

  /// <summary>
  /// The tax name
  /// </summary>
  [System.Text.Json.Serialization.JsonPropertyName("tax_name2")]
  public string? TaxName2 { get; set; }

  /// <summary>
  /// The tax rate
  /// </summary>
  [System.Text.Json.Serialization.JsonPropertyName("tax_rate1")]
  public float? TaxRate1 { get; set; }

  /// <summary>
  /// The tax rate
  /// </summary>
  [System.Text.Json.Serialization.JsonPropertyName("tax_rate2")]
  public float? TaxRate2 { get; set; }

  /// <summary>
  /// The tax name
  /// </summary>
  [System.Text.Json.Serialization.JsonPropertyName("tax_name3")]
  public string? TaxName3 { get; set; }

  /// <summary>
  /// The tax rate
  /// </summary>
  [System.Text.Json.Serialization.JsonPropertyName("tax_rate3")]
  public float? TaxRate3 { get; set; }

  /// <summary>
  /// The total taxes for the invoice
  /// </summary>
  [System.Text.Json.Serialization.JsonPropertyName("total_taxes")]
  public float? TotalTaxes { get; set; }

  /// <summary>
  /// An array of objects which define the line items of the invoice
  /// </summary>
  [System.Text.Json.Serialization.JsonPropertyName("line_items")]
  public List<InvoiceItem>? LineItems { get; set; }

  /// <summary>
  /// An array of objects which define the invitations of the invoice
  /// </summary>
  [System.Text.Json.Serialization.JsonPropertyName("invitations")]
  public List<InvoiceInvitation>? Invitations { get; set; }

  /// <summary>
  /// The invoice amount
  /// </summary>
  [JsonConverter(typeof(EmptyStringToNullableDecimalConverter))]
  [System.Text.Json.Serialization.JsonPropertyName("amount")]
  public decimal? Amount { get; set; }

  /// <summary>
  /// The invoice balance
  /// </summary>
  [JsonConverter(typeof(EmptyStringToNullableDecimalConverter))]
  [System.Text.Json.Serialization.JsonPropertyName("balance")]
  public decimal? Balance { get; set; }

  /// <summary>
  /// The amount paid on the invoice to date
  /// </summary>
  [System.Text.Json.Serialization.JsonPropertyName("paid_to_date")]
  public float? PaidToDate { get; set; }

  /// <summary>
  /// The invoice discount, can be an amount or a percentage
  /// </summary>
  [JsonConverter(typeof(EmptyStringToNullableDecimalConverter))]
  [System.Text.Json.Serialization.JsonPropertyName("discount")]
  public decimal? Discount { get; set; }

  /// <summary>
  /// The deposit/partial amount
  /// </summary>
  [System.Text.Json.Serialization.JsonPropertyName("partial")]
  public float? Partial { get; set; }

  /// <summary>
  /// Flag determining if the discount is an amount or a percentage
  /// </summary>
  [System.Text.Json.Serialization.JsonPropertyName("is_amount_discount")]
  public bool? IsAmountDiscount { get; set; }

  /// <summary>
  /// Defines if the invoice has been deleted
  /// </summary>
  [System.Text.Json.Serialization.JsonPropertyName("is_deleted")]
  public bool? IsDeleted { get; set; }

  /// <summary>
  /// Defines the type of taxes used as either inclusive or exclusive
  /// </summary>
  [System.Text.Json.Serialization.JsonPropertyName("uses_inclusive_taxes")]
  public bool? UsesInclusiveTaxes { get; set; }

  /// <summary>
  /// The Invoice Date
  /// </summary>
  [System.Text.Json.Serialization.JsonPropertyName("date")]
  public DateOnly? Date { get; set; }

  /// <summary>
  /// The last date the invoice was sent out
  /// </summary>
  [JsonConverter(typeof(EmptyStringToDateOnlyConverter))]
  [System.Text.Json.Serialization.JsonPropertyName("last_sent_date")]
  public DateOnly? LastSentDate { get; set; }

  /// <summary>
  /// The Next date for a reminder to be sent
  /// </summary>
  [JsonConverter(typeof(EmptyStringToDateOnlyConverter))]
  [System.Text.Json.Serialization.JsonPropertyName("next_send_date")]
  public DateOnly? NextSendDate { get; set; }

  /// <summary>
  /// The due date for the deposit/partial amount
  /// </summary>
  [JsonConverter(typeof(EmptyStringToDateOnlyConverter))]
  [System.Text.Json.Serialization.JsonPropertyName("partial_due_date")]
  public DateOnly? PartialDueDate { get; set; }

  /// <summary>
  /// The due date of the invoice
  /// </summary>
  [JsonConverter(typeof(EmptyStringToDateOnlyConverter))]
  [System.Text.Json.Serialization.JsonPropertyName("due_date")]
  public DateOnly? DueDate { get; set; }

  /// <summary>
  /// Timestamp
  /// </summary>
  [System.Text.Json.Serialization.JsonPropertyName("last_viewed")]
  public decimal? LastViewed { get; set; }

  /// <summary>
  /// Timestamp
  /// </summary>
  [JsonConverter(typeof(UnixTimestampConverter))]
  [System.Text.Json.Serialization.JsonPropertyName("updated_at")]
  public DateTimeOffset? UpdatedAt { get; set; }

  /// <summary>
  /// Timestamp
  /// </summary>
  [JsonConverter(typeof(UnixTimestampConverter))]
  [System.Text.Json.Serialization.JsonPropertyName("archived_at")]
  public DateTimeOffset? ArchivedAt { get; set; }

  /// <summary>
  /// First Custom Surcharge
  /// </summary>
  [System.Text.Json.Serialization.JsonPropertyName("custom_surcharge1")]
  public float? CustomSurcharge1 { get; set; }

  /// <summary>
  /// Second Custom Surcharge
  /// </summary>
  [System.Text.Json.Serialization.JsonPropertyName("custom_surcharge2")]
  public float? CustomSurcharge2 { get; set; }

  /// <summary>
  /// Third Custom Surcharge
  /// </summary>
  [System.Text.Json.Serialization.JsonPropertyName("custom_surcharge3")]
  public float? CustomSurcharge3 { get; set; }

  /// <summary>
  /// Fourth Custom Surcharge
  /// </summary>
  [System.Text.Json.Serialization.JsonPropertyName("custom_surcharge4")]
  public float? CustomSurcharge4 { get; set; }

  /// <summary>
  /// Toggles charging taxes on custom surcharge amounts
  /// </summary>
  [System.Text.Json.Serialization.JsonPropertyName("custom_surcharge_tax1")]
  public bool? CustomSurchargeTax1 { get; set; }

  /// <summary>
  /// Toggles charging taxes on custom surcharge amounts
  /// </summary>
  [System.Text.Json.Serialization.JsonPropertyName("custom_surcharge_tax2")]
  public bool? CustomSurchargeTax2 { get; set; }

  /// <summary>
  /// Toggles charging taxes on custom surcharge amounts
  /// </summary>
  [System.Text.Json.Serialization.JsonPropertyName("custom_surcharge_tax3")]
  public bool? CustomSurchargeTax3 { get; set; }

  /// <summary>
  /// Toggles charging taxes on custom surcharge amounts
  /// </summary>
  [System.Text.Json.Serialization.JsonPropertyName("custom_surcharge_tax4")]
  public bool? CustomSurchargeTax4 { get; set; }

  /// <summary>
  /// The project associated with this invoice
  /// </summary>
  [System.Text.Json.Serialization.JsonPropertyName("project_id")]
  public string? ProjectId { get; set; }

  /// <summary>
  /// The number of times the invoice has attempted to be auto billed
  /// </summary>
  [JsonConverter(typeof(StringToIntegerConverter))]
  [System.Text.Json.Serialization.JsonPropertyName("auto_bill_tries")]
  public int? AutoBillTries { get; set; }

  /// <summary>
  /// Boolean flag determining if the invoice is set to auto bill
  /// </summary>
  [System.Text.Json.Serialization.JsonPropertyName("auto_bill_enabled")]
  public bool? AutoBillEnabled { get; set; }

  /// <summary>
  /// The subscription associated with this invoice
  /// </summary>
  [System.Text.Json.Serialization.JsonPropertyName("subscription_id")]
  public string? SubscriptionId { get; set; }

  /// <summary>
  /// The client location id that this invoice relates to
  /// </summary>
  [System.Text.Json.Serialization.JsonPropertyName("location_id")]
  public string? LocationId { get; set; }
}
