//
// <auto-generated>
// Invoice Ninja API Models - Auto-generated from OpenAPI specification
//
// Generated by: ApiGenerator
// Source: specs/invoiceninja.yaml
// API: Invoice Ninja API Reference.
// Version: 5.12.55
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
// </auto-generated>
//
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Text.Json;
using System.Text.Json.Serialization;

#nullable enable

namespace Apigen.InvoiceNinja.Models;

/// <summary>
/// InvoiceItem from OpenAPI schema.
/// Schema path: #/components/schemas/InvoiceItem
/// </summary>
public class InvoiceItem
{
  /// <summary>
  /// The quantity of the product offered for this line item
  /// </summary>
  [JsonConverter(typeof(EmptyStringToNullableDecimalConverter))]
  [System.Text.Json.Serialization.JsonPropertyName("quantity")]
  public decimal? Quantity { get; set; }

  /// <summary>
  /// The cost of the product offered for this line item
  /// </summary>
  [JsonConverter(typeof(EmptyStringToNullableDecimalConverter))]
  [System.Text.Json.Serialization.JsonPropertyName("cost")]
  public decimal? Cost { get; set; }

  /// <summary>
  /// The product key of the product offered for this line item (Referred to as Product in the product tab)
  /// </summary>
  [System.Text.Json.Serialization.JsonPropertyName("product_key")]
  public string? ProductKey { get; set; }

  /// <summary>
  /// The cost of the product offered for this line item (Referred to as Cost in the product tab)
  /// </summary>
  [JsonConverter(typeof(EmptyStringToNullableDecimalConverter))]
  [System.Text.Json.Serialization.JsonPropertyName("product_cost")]
  public decimal? ProductCost { get; set; }

  /// <summary>
  /// The notes/description for the product offered for this line item
  /// </summary>
  [System.Text.Json.Serialization.JsonPropertyName("notes")]
  public string? Notes { get; set; }

  /// <summary>
  /// The discount applied to the product offered for this line item
  /// </summary>
  [JsonConverter(typeof(EmptyStringToNullableDecimalConverter))]
  [System.Text.Json.Serialization.JsonPropertyName("discount")]
  public decimal? Discount { get; set; }

  /// <summary>
  /// Indicates whether the discount applied to the product offered for this line item is a fixed amount or a percentage
  /// </summary>
  [System.Text.Json.Serialization.JsonPropertyName("is_amount_discount")]
  public bool? IsAmountDiscount { get; set; }

  /// <summary>
  /// The name of the first tax applied to the product offered for this line item
  /// </summary>
  [System.Text.Json.Serialization.JsonPropertyName("tax_name1")]
  public string? TaxName1 { get; set; }

  /// <summary>
  /// The rate of the first tax applied to the product offered for this line item
  /// </summary>
  [System.Text.Json.Serialization.JsonPropertyName("tax_rate1")]
  public float? TaxRate1 { get; set; }

  /// <summary>
  /// The name of the second tax applied to the product offered for this line item
  /// </summary>
  [System.Text.Json.Serialization.JsonPropertyName("tax_name2")]
  public string? TaxName2 { get; set; }

  /// <summary>
  /// The rate of the second tax applied to the product offered for this line item
  /// </summary>
  [System.Text.Json.Serialization.JsonPropertyName("tax_rate2")]
  public float? TaxRate2 { get; set; }

  /// <summary>
  /// The name of the third tax applied to the product offered for this line item
  /// </summary>
  [System.Text.Json.Serialization.JsonPropertyName("tax_name3")]
  public string? TaxName3 { get; set; }

  /// <summary>
  /// The rate of the third tax applied to the product offered for this line item
  /// </summary>
  [System.Text.Json.Serialization.JsonPropertyName("tax_rate3")]
  public float? TaxRate3 { get; set; }

  /// <summary>
  /// Deprecated
  /// </summary>
  [System.Text.Json.Serialization.JsonPropertyName("sort_id")]
  public string? SortId { get; set; }

  /// <summary>
  /// The total amount of the product offered for this line item
  /// </summary>
  [JsonConverter(typeof(EmptyStringToNullableDecimalConverter))]
  [System.Text.Json.Serialization.JsonPropertyName("line_total")]
  public decimal? LineTotal { get; set; }

  /// <summary>
  /// The total amount of the product offered for this line item before discounts
  /// </summary>
  [JsonConverter(typeof(EmptyStringToNullableDecimalConverter))]
  [System.Text.Json.Serialization.JsonPropertyName("gross_line_total")]
  public decimal? GrossLineTotal { get; set; }

  /// <summary>
  /// The total amount of tax applied to the product offered for this line item
  /// </summary>
  [JsonConverter(typeof(EmptyStringToNullableDecimalConverter))]
  [System.Text.Json.Serialization.JsonPropertyName("tax_amount")]
  public decimal? TaxAmount { get; set; }

  /// <summary>
  /// The first custom value of the product offered for this line item
  /// </summary>
  [System.Text.Json.Serialization.JsonPropertyName("custom_value1")]
  public string? CustomValue1 { get; set; }

  /// <summary>
  /// The second custom value of the product offered for this line item
  /// </summary>
  [System.Text.Json.Serialization.JsonPropertyName("custom_value2")]
  public string? CustomValue2 { get; set; }

  /// <summary>
  /// The third custom value of the product offered for this line item
  /// </summary>
  [System.Text.Json.Serialization.JsonPropertyName("custom_value3")]
  public string? CustomValue3 { get; set; }

  /// <summary>
  /// The fourth custom value of the product offered for this line item
  /// </summary>
  [System.Text.Json.Serialization.JsonPropertyName("custom_value4")]
  public string? CustomValue4 { get; set; }

  /// <summary>
  /// 1 = product, 2 = service, 3 unpaid gateway fee, 4 paid gateway fee, 5 late fee, 6 expense
  /// </summary>
  [System.Text.Json.Serialization.JsonPropertyName("type_id")]
  public string? TypeId { get; set; }

  /// <summary>
  /// The tax ID of the product: 1 product, 2 service, 3 digital, 4 shipping, 5 exempt, 5 reduced tax, 7 override, 8 zero rate, 9 reverse tax
  /// </summary>
  [System.Text.Json.Serialization.JsonPropertyName("tax_id")]
  public string? TaxId { get; set; }
}
