//
// <auto-generated>
// Invoice Ninja API Models - Auto-generated from OpenAPI specification
//
// Generated by: ApiGenerator
// Source: specs/invoiceninja.yaml
// API: Invoice Ninja API Reference.
// Version: 5.11.48
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
// </auto-generated>
//
using System;

#nullable enable

namespace Apigen.InvoiceNinja.Models;

/// <summary>
/// Extension methods for converting between Request and Response models
/// </summary>
public static class ModelConversionExtensions
{
  /// <summary>
  /// Converts TaskItemStatus to TaskItemStatusRequest
  /// </summary>
  public static TaskItemStatusRequest ToRequest(this TaskItemStatus source)
  {
    return new TaskItemStatusRequest
    {
      Name = source.Name,
      Color = source.Color,
      TaskStatusOrder = source.TaskStatusOrder
    };
  }

  /// <summary>
  /// Converts Payment to PaymentRequest
  /// </summary>
  public static PaymentRequest ToRequest(this Payment source)
  {
    return new PaymentRequest
    {
      ClientId = source.ClientId,
      InvitationId = source.InvitationId,
      ClientContactId = source.ClientContactId,
      UserId = source.UserId,
      TypeId = source.TypeId,
      Date = source.Date,
      TransactionReference = source.TransactionReference,
      AssignedUserId = source.AssignedUserId,
      PrivateNotes = source.PrivateNotes,
      IsManual = source.IsManual,
      IsDeleted = source.IsDeleted,
      Amount = source.Amount,
      Refunded = source.Refunded,
      UpdatedAt = source.UpdatedAt,
      ArchivedAt = source.ArchivedAt,
      CompanyGatewayId = source.CompanyGatewayId,
      Paymentables = source.Paymentables,
      Invoices = source.Invoices,
      Credits = source.Credits,
      Number = source.Number
    };
  }

}
