//
// <auto-generated>
// Invoice Ninja API Models - Auto-generated from OpenAPI specification
//
// Generated by: ApiGenerator
// Source: specs/invoiceninja.yaml
// API: Invoice Ninja API Reference.
// Version: 5.12.55
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
// </auto-generated>
//
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Text.Json;
using System.Text.Json.Serialization;

#nullable enable

namespace Apigen.InvoiceNinja.Models;

/// <summary>
/// Paymentable from OpenAPI schema.
/// Schema path: #/components/schemas/Paymentable
/// </summary>
public class Paymentable
{
  /// <summary>
  /// The paymentable hashed id
  /// </summary>
  [System.Text.Json.Serialization.JsonPropertyName("id")]
  public string? Id { get; set; }

  /// <summary>
  /// The invoice hashed id
  /// </summary>
  [System.Text.Json.Serialization.JsonPropertyName("invoice_id")]
  public string? InvoiceId { get; set; }

  /// <summary>
  /// The credit hashed id
  /// </summary>
  [System.Text.Json.Serialization.JsonPropertyName("credit_id")]
  public string? CreditId { get; set; }

  /// <summary>
  /// The amount that has been refunded for this payment
  /// </summary>
  [System.Text.Json.Serialization.JsonPropertyName("refunded")]
  public float? Refunded { get; set; }

  /// <summary>
  /// The amount that has been applied to the payment
  /// </summary>
  [JsonConverter(typeof(EmptyStringToNullableDecimalConverter))]
  [System.Text.Json.Serialization.JsonPropertyName("amount")]
  public decimal? Amount { get; set; }

  /// <summary>
  /// Timestamp
  /// </summary>
  [JsonConverter(typeof(UnixTimestampConverter))]
  [System.Text.Json.Serialization.JsonPropertyName("updated_at")]
  public DateTimeOffset? UpdatedAt { get; set; }

  /// <summary>
  /// Timestamp
  /// </summary>
  [JsonConverter(typeof(UnixTimestampConverter))]
  [System.Text.Json.Serialization.JsonPropertyName("created_at")]
  public DateTimeOffset? CreatedAt { get; set; }
}
