//
// <auto-generated>
// Invoice Ninja API Models - Auto-generated from OpenAPI specification
//
// Generated by: ApiGenerator
// Source: specs/invoiceninja.yaml
// API: Invoice Ninja API Reference.
// Version: 5.11.48
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
// </auto-generated>
//
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Text.Json;
using System.Text.Json.Serialization;

#nullable enable

namespace Apigen.InvoiceNinja.Models;

/// <summary>
/// Request model for Payment
/// </summary>
public class PaymentRequest
{
  /// <summary>
  /// The client hashed id
  /// </summary>
  [System.Text.Json.Serialization.JsonIgnore(Condition = System.Text.Json.Serialization.JsonIgnoreCondition.WhenWritingNull)]
  [JsonPropertyName("client_id")]
  public string? ClientId { get; set; }

  /// <summary>
  /// The invitation hashed id
  /// </summary>
  [System.Text.Json.Serialization.JsonIgnore(Condition = System.Text.Json.Serialization.JsonIgnoreCondition.WhenWritingNull)]
  [JsonPropertyName("invitation_id")]
  public string? InvitationId { get; set; }

  /// <summary>
  /// The client contact hashed id
  /// </summary>
  [System.Text.Json.Serialization.JsonIgnore(Condition = System.Text.Json.Serialization.JsonIgnoreCondition.WhenWritingNull)]
  [JsonPropertyName("client_contact_id")]
  public string? ClientContactId { get; set; }

  /// <summary>
  /// The user hashed id
  /// </summary>
  [System.Text.Json.Serialization.JsonIgnore(Condition = System.Text.Json.Serialization.JsonIgnoreCondition.WhenWritingNull)]
  [JsonPropertyName("user_id")]
  public string? UserId { get; set; }

  /// <summary>
  /// The payment type used to complete this payment
  /// </summary>
  [JsonConverter(typeof(EmptyStringToNullableEnumConverter<PaymentType>))]
  [System.Text.Json.Serialization.JsonIgnore(Condition = System.Text.Json.Serialization.JsonIgnoreCondition.WhenWritingNull)]
  [JsonPropertyName("type_id")]
  public PaymentType? TypeId { get; set; }

  /// <summary>
  /// The Payment date
  /// </summary>
  [System.Text.Json.Serialization.JsonIgnore(Condition = System.Text.Json.Serialization.JsonIgnoreCondition.WhenWritingNull)]
  [JsonPropertyName("date")]
  public string? Date { get; set; }

  /// <summary>
  /// The transaction reference as defined by the payment gateway
  /// </summary>
  [System.Text.Json.Serialization.JsonIgnore(Condition = System.Text.Json.Serialization.JsonIgnoreCondition.WhenWritingNull)]
  [JsonPropertyName("transaction_reference")]
  public string? TransactionReference { get; set; }

  /// <summary>
  /// The assigned user hashed id
  /// </summary>
  [System.Text.Json.Serialization.JsonIgnore(Condition = System.Text.Json.Serialization.JsonIgnoreCondition.WhenWritingNull)]
  [JsonPropertyName("assigned_user_id")]
  public string? AssignedUserId { get; set; }

  /// <summary>
  /// The private notes of the payment
  /// </summary>
  [System.Text.Json.Serialization.JsonIgnore(Condition = System.Text.Json.Serialization.JsonIgnoreCondition.WhenWritingNull)]
  [JsonPropertyName("private_notes")]
  public string? PrivateNotes { get; set; }

  /// <summary>
  /// Flags whether the payment was made manually or processed via a gateway
  /// </summary>
  [JsonPropertyName("is_manual")]
  public bool? IsManual { get; set; }

  /// <summary>
  /// Defines if the payment has been deleted
  /// </summary>
  [JsonPropertyName("is_deleted")]
  public bool? IsDeleted { get; set; }

  /// <summary>
  /// The amount of this payment
  /// </summary>
  [JsonConverter(typeof(EmptyStringToNullableDecimalConverter))]
  [JsonPropertyName("amount")]
  public decimal? Amount { get; set; }

  /// <summary>
  /// The refunded amount of this payment
  /// </summary>
  [JsonPropertyName("refunded")]
  public decimal? Refunded { get; set; }

  /// <summary>
  /// Timestamp
  /// </summary>
  [JsonConverter(typeof(UnixTimestampConverter))]
  [JsonPropertyName("updated_at")]
  public DateTimeOffset? UpdatedAt { get; set; }

  /// <summary>
  /// Timestamp
  /// </summary>
  [JsonConverter(typeof(UnixTimestampConverter))]
  [JsonPropertyName("archived_at")]
  public DateTimeOffset? ArchivedAt { get; set; }

  /// <summary>
  /// The company gateway id
  /// </summary>
  [System.Text.Json.Serialization.JsonIgnore(Condition = System.Text.Json.Serialization.JsonIgnoreCondition.WhenWritingNull)]
  [JsonPropertyName("company_gateway_id")]
  public string? CompanyGatewayId { get; set; }

  [System.Text.Json.Serialization.JsonIgnore(Condition = System.Text.Json.Serialization.JsonIgnoreCondition.WhenWritingNull)]
  [JsonPropertyName("paymentables")]
  public Paymentable[]? Paymentables { get; set; }

  [System.Text.Json.Serialization.JsonIgnore(Condition = System.Text.Json.Serialization.JsonIgnoreCondition.WhenWritingNull)]
  [JsonPropertyName("invoices")]
  public List<InvoicePaymentable>? Invoices { get; set; }

  [System.Text.Json.Serialization.JsonIgnore(Condition = System.Text.Json.Serialization.JsonIgnoreCondition.WhenWritingNull)]
  [JsonPropertyName("credits")]
  public List<CreditPaymentable>? Credits { get; set; }

  /// <summary>
  /// The payment number - is a unique alpha numeric number per payment per company
  /// </summary>
  [System.Text.Json.Serialization.JsonIgnore(Condition = System.Text.Json.Serialization.JsonIgnoreCondition.WhenWritingNull)]
  [JsonPropertyName("number")]
  public string? Number { get; set; }

}
