//
// <auto-generated>
// Invoice Ninja API Models - Auto-generated from OpenAPI specification
//
// Generated by: ApiGenerator
// Source: specs/invoiceninja.yaml
// API: Invoice Ninja API Reference.
// Version: 5.12.55
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
// </auto-generated>
//
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Text.Json;
using System.Text.Json.Serialization;

#nullable enable

namespace Apigen.InvoiceNinja.Models;

/// <summary>
/// PostImportRequest from OpenAPI schema.
/// Schema path: #/components/schemas/PostImportRequest
/// </summary>
public class PostImportRequest
{
  /// <summary>
  /// The unique file reference returned by the preimport endpoint.
  /// </summary>
  [Required]
  [System.Text.Json.Serialization.JsonIgnore(Condition = System.Text.Json.Serialization.JsonIgnoreCondition.Never)]
  [System.Text.Json.Serialization.JsonPropertyName("hash")]
  public string? Hash { get; set; }

  /// <summary>
  /// The source format of the import.
  /// </summary>
  [Required]
  [System.Text.Json.Serialization.JsonIgnore(Condition = System.Text.Json.Serialization.JsonIgnoreCondition.Never)]
  [System.Text.Json.Serialization.JsonPropertyName("import_type")]
  public string? ImportType { get; set; }

  /// <summary>
  /// When true, the first row of the CSV is treated as a header row and skipped during import.
  /// </summary>
  [System.Text.Json.Serialization.JsonIgnore(Condition = System.Text.Json.Serialization.JsonIgnoreCondition.WhenWritingNull)]
  [System.Text.Json.Serialization.JsonPropertyName("skip_header")]
  public bool? SkipHeader { get; set; }

  /// <summary>
  /// An object keyed by entity type. Each entity contains a mapping of CSV column indices to system fields.
  /// </summary>
  [Required]
  [System.Text.Json.Serialization.JsonIgnore(Condition = System.Text.Json.Serialization.JsonIgnoreCondition.Never)]
  [System.Text.Json.Serialization.JsonPropertyName("column_map")]
  public Dictionary<string, object?>? ColumnMap { get; set; }
}
