//
// <auto-generated>
// Invoice Ninja API Models - Auto-generated from OpenAPI specification
//
// Generated by: ApiGenerator
// Source: specs/invoiceninja.yaml
// API: Invoice Ninja API Reference.
// Version: 5.12.55
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
// </auto-generated>
//
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Text.Json;
using System.Text.Json.Serialization;

#nullable enable

namespace Apigen.InvoiceNinja.Models;

/// <summary>
/// PostImportRequestColumnMap from OpenAPI schema.
/// Schema path: #/components/schemas/PostImportRequestColumnMap
/// </summary>
public partial class PostImportRequestColumnMap
{
  /// <summary>
  /// Maps CSV column indices (as string keys) to system field names from the available array. Use an empty string to skip a column.
  /// </summary>
  [System.Text.Json.Serialization.JsonPropertyName("mapping")]
  public Dictionary<string, string?>? Mapping { get; set; }
}
