//
// <auto-generated>
// Invoice Ninja API Models - Auto-generated from OpenAPI specification
//
// Generated by: ApiGenerator
// Source: specs/invoiceninja.yaml
// API: Invoice Ninja API Reference.
// Version: 5.12.55
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
// </auto-generated>
//
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Text.Json;
using System.Text.Json.Serialization;

#nullable enable

namespace Apigen.InvoiceNinja.Models;

/// <summary>
/// PurchaseOrder from OpenAPI schema.
/// Schema path: #/components/schemas/PurchaseOrder
/// </summary>
public class PurchaseOrder
{
  /// <summary>
  /// The unique hashed identifier for the purchase order
  /// </summary>
  [System.Text.Json.Serialization.JsonPropertyName("id")]
  public string? Id { get; set; }

  /// <summary>
  /// The unique hashed identifier for the user who created the purchase order
  /// </summary>
  [System.Text.Json.Serialization.JsonPropertyName("user_id")]
  public string? UserId { get; set; }

  /// <summary>
  /// The unique hashed identifier for the user assigned to the purchase order
  /// </summary>
  [System.Text.Json.Serialization.JsonPropertyName("assigned_user_id")]
  public string? AssignedUserId { get; set; }

  /// <summary>
  /// The unique hashed identifier for the vendor associated with the purchase order
  /// </summary>
  [System.Text.Json.Serialization.JsonPropertyName("vendor_id")]
  public string? VendorId { get; set; }

  /// <summary>
  /// The status of the purchase order represented by a unique identifier
  /// </summary>
  [System.Text.Json.Serialization.JsonPropertyName("status_id")]
  public string? StatusId { get; set; }

  /// <summary>
  /// The unique alpha-numeric purchase order number per company
  /// </summary>
  [System.Text.Json.Serialization.JsonPropertyName("number")]
  public string? Number { get; set; }

  /// <summary>
  /// The quote number associated with this purchase order
  /// </summary>
  [System.Text.Json.Serialization.JsonPropertyName("quote_number")]
  public string? QuoteNumber { get; set; }

  /// <summary>
  /// The terms and conditions for the purchase order
  /// </summary>
  [System.Text.Json.Serialization.JsonPropertyName("terms")]
  public string? Terms { get; set; }

  /// <summary>
  /// Publicly visible notes associated with the purchase order
  /// </summary>
  [System.Text.Json.Serialization.JsonPropertyName("public_notes")]
  public string? PublicNotes { get; set; }

  /// <summary>
  /// Privately visible notes associated with the purchase order, not disclosed to the vendor
  /// </summary>
  [System.Text.Json.Serialization.JsonPropertyName("private_notes")]
  public string? PrivateNotes { get; set; }

  /// <summary>
  /// The footer text of the purchase order
  /// </summary>
  [System.Text.Json.Serialization.JsonPropertyName("footer")]
  public string? Footer { get; set; }

  /// <summary>
  /// First custom value field for additional information
  /// </summary>
  [System.Text.Json.Serialization.JsonPropertyName("custom_value1")]
  public string? CustomValue1 { get; set; }

  /// <summary>
  /// Second custom value field for additional information
  /// </summary>
  [System.Text.Json.Serialization.JsonPropertyName("custom_value2")]
  public string? CustomValue2 { get; set; }

  /// <summary>
  /// Third custom value field for additional information
  /// </summary>
  [System.Text.Json.Serialization.JsonPropertyName("custom_value3")]
  public string? CustomValue3 { get; set; }

  /// <summary>
  /// Fourth custom value field for additional information
  /// </summary>
  [System.Text.Json.Serialization.JsonPropertyName("custom_value4")]
  public string? CustomValue4 { get; set; }

  /// <summary>
  /// The name of the first tax applied to the purchase order
  /// </summary>
  [System.Text.Json.Serialization.JsonPropertyName("tax_name1")]
  public string? TaxName1 { get; set; }

  /// <summary>
  /// The name of the second tax applied to the purchase order
  /// </summary>
  [System.Text.Json.Serialization.JsonPropertyName("tax_name2")]
  public string? TaxName2 { get; set; }

  /// <summary>
  /// The rate of the first tax applied to the purchase order
  /// </summary>
  [System.Text.Json.Serialization.JsonPropertyName("tax_rate1")]
  public float? TaxRate1 { get; set; }

  /// <summary>
  /// The rate of the second tax applied to the purchase order
  /// </summary>
  [System.Text.Json.Serialization.JsonPropertyName("tax_rate2")]
  public float? TaxRate2 { get; set; }

  /// <summary>
  /// The name of the third tax applied to the purchase order
  /// </summary>
  [System.Text.Json.Serialization.JsonPropertyName("tax_name3")]
  public string? TaxName3 { get; set; }

  /// <summary>
  /// The rate of the third tax applied to the purchase order
  /// </summary>
  [System.Text.Json.Serialization.JsonPropertyName("tax_rate3")]
  public float? TaxRate3 { get; set; }

  /// <summary>
  /// The total amount of taxes applied to the purchase order
  /// </summary>
  [System.Text.Json.Serialization.JsonPropertyName("total_taxes")]
  public float? TotalTaxes { get; set; }

  /// <summary>
  /// An array of objects which define the line items of the purchase order
  /// </summary>
  [System.Text.Json.Serialization.JsonPropertyName("line_items")]
  public List<InvoiceItem>? LineItems { get; set; }

  /// <summary>
  /// The total amount of the purchase order before taxes and discounts
  /// </summary>
  [JsonConverter(typeof(EmptyStringToNullableDecimalConverter))]
  [System.Text.Json.Serialization.JsonPropertyName("amount")]
  public decimal? Amount { get; set; }

  /// <summary>
  /// The balance due for the purchase order after accounting for payments
  /// </summary>
  [JsonConverter(typeof(EmptyStringToNullableDecimalConverter))]
  [System.Text.Json.Serialization.JsonPropertyName("balance")]
  public decimal? Balance { get; set; }

  /// <summary>
  /// The total amount paid on the purchase order so far
  /// </summary>
  [System.Text.Json.Serialization.JsonPropertyName("paid_to_date")]
  public float? PaidToDate { get; set; }

  /// <summary>
  /// The discount amount or percentage applied to the purchase order
  /// </summary>
  [JsonConverter(typeof(EmptyStringToNullableDecimalConverter))]
  [System.Text.Json.Serialization.JsonPropertyName("discount")]
  public decimal? Discount { get; set; }

  /// <summary>
  /// The partial or deposit amount for the purchase order
  /// </summary>
  [System.Text.Json.Serialization.JsonPropertyName("partial")]
  public float? Partial { get; set; }

  /// <summary>
  /// Boolean flag indicating if the discount is a fixed amount or a percentage
  /// </summary>
  [System.Text.Json.Serialization.JsonPropertyName("is_amount_discount")]
  public bool? IsAmountDiscount { get; set; }

  /// <summary>
  /// Boolean flag indicating if the purchase order has been deleted
  /// </summary>
  [System.Text.Json.Serialization.JsonPropertyName("is_deleted")]
  public bool? IsDeleted { get; set; }

  /// <summary>
  /// Boolean flag indicating if the taxes used are inclusive or exclusive
  /// </summary>
  [System.Text.Json.Serialization.JsonPropertyName("uses_inclusive_taxes")]
  public bool? UsesInclusiveTaxes { get; set; }

  /// <summary>
  /// The date the purchase order was created
  /// </summary>
  [System.Text.Json.Serialization.JsonPropertyName("date")]
  public DateOnly? Date { get; set; }

  /// <summary>
  /// The last date the purchase order was sent to the vendor
  /// </summary>
  [System.Text.Json.Serialization.JsonPropertyName("last_sent_date")]
  public DateOnly? LastSentDate { get; set; }

  /// <summary>
  /// The next scheduled date for sending a reminder for the purchase order
  /// </summary>
  [System.Text.Json.Serialization.JsonPropertyName("next_send_date")]
  public DateOnly? NextSendDate { get; set; }

  /// <summary>
  /// The due date for the partial or deposit amount
  /// </summary>
  [JsonConverter(typeof(EmptyStringToDateOnlyConverter))]
  [System.Text.Json.Serialization.JsonPropertyName("partial_due_date")]
  public DateOnly? PartialDueDate { get; set; }

  /// <summary>
  /// The due date for the total amount of the purchase order
  /// </summary>
  [JsonConverter(typeof(EmptyStringToDateOnlyConverter))]
  [System.Text.Json.Serialization.JsonPropertyName("due_date")]
  public DateOnly? DueDate { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("settings")]
  public CompanySettings? Settings { get; set; }

  /// <summary>
  /// Timestamp
  /// </summary>
  [System.Text.Json.Serialization.JsonPropertyName("last_viewed")]
  public decimal? LastViewed { get; set; }

  /// <summary>
  /// Timestamp
  /// </summary>
  [JsonConverter(typeof(UnixTimestampConverter))]
  [System.Text.Json.Serialization.JsonPropertyName("updated_at")]
  public DateTimeOffset? UpdatedAt { get; set; }

  /// <summary>
  /// Timestamp
  /// </summary>
  [JsonConverter(typeof(UnixTimestampConverter))]
  [System.Text.Json.Serialization.JsonPropertyName("archived_at")]
  public DateTimeOffset? ArchivedAt { get; set; }

  /// <summary>
  /// First custom surcharge amount for the purchase order
  /// </summary>
  [System.Text.Json.Serialization.JsonPropertyName("custom_surcharge1")]
  public float? CustomSurcharge1 { get; set; }

  /// <summary>
  /// Second custom surcharge amount for the purchase order
  /// </summary>
  [System.Text.Json.Serialization.JsonPropertyName("custom_surcharge2")]
  public float? CustomSurcharge2 { get; set; }

  /// <summary>
  /// Third custom surcharge amount for the purchase order
  /// </summary>
  [System.Text.Json.Serialization.JsonPropertyName("custom_surcharge3")]
  public float? CustomSurcharge3 { get; set; }

  /// <summary>
  /// Fourth custom surcharge amount for the purchase order
  /// </summary>
  [System.Text.Json.Serialization.JsonPropertyName("custom_surcharge4")]
  public float? CustomSurcharge4 { get; set; }

  /// <summary>
  /// Boolean flag indicating if taxes are charged on the first custom surcharge amount
  /// </summary>
  [System.Text.Json.Serialization.JsonPropertyName("custom_surcharge_tax1")]
  public bool? CustomSurchargeTax1 { get; set; }

  /// <summary>
  /// Boolean flag indicating if taxes are charged on the second custom surcharge amount
  /// </summary>
  [System.Text.Json.Serialization.JsonPropertyName("custom_surcharge_tax2")]
  public bool? CustomSurchargeTax2 { get; set; }

  /// <summary>
  /// Boolean flag indicating if taxes are charged on the third custom surcharge amount
  /// </summary>
  [System.Text.Json.Serialization.JsonPropertyName("custom_surcharge_tax3")]
  public bool? CustomSurchargeTax3 { get; set; }

  /// <summary>
  /// Boolean flag indicating if taxes are charged on the fourth custom surcharge amount
  /// </summary>
  [System.Text.Json.Serialization.JsonPropertyName("custom_surcharge_tax4")]
  public bool? CustomSurchargeTax4 { get; set; }

  /// <summary>
  /// Backup data or file reference for this purchase order
  /// </summary>
  [System.Text.Json.Serialization.JsonPropertyName("backup")]
  public string? Backup { get; set; }

  /// <summary>
  /// The unique identifier of the client associated with this purchase order
  /// </summary>
  [System.Text.Json.Serialization.JsonPropertyName("client_id")]
  public string? ClientId { get; set; }

  /// <summary>
  /// The unique identifier of the currency
  /// </summary>
  [System.Text.Json.Serialization.JsonPropertyName("currency_id")]
  public string? CurrencyId { get; set; }

  /// <summary>
  /// The unique identifier of the design template used for this purchase order
  /// </summary>
  [System.Text.Json.Serialization.JsonPropertyName("design_id")]
  public string? DesignId { get; set; }

  /// <summary>
  /// The exchange rate used for currency conversion
  /// </summary>
  [JsonConverter(typeof(EmptyStringToNullableDecimalConverter))]
  [System.Text.Json.Serialization.JsonPropertyName("exchange_rate")]
  public decimal? ExchangeRate { get; set; }

  /// <summary>
  /// The unique identifier of the related invoice
  /// </summary>
  [System.Text.Json.Serialization.JsonPropertyName("invoice_id")]
  public string? InvoiceId { get; set; }

  /// <summary>
  /// The unique identifier of the location
  /// </summary>
  [System.Text.Json.Serialization.JsonPropertyName("location_id")]
  public string? LocationId { get; set; }

  /// <summary>
  /// The purchase order number
  /// </summary>
  [System.Text.Json.Serialization.JsonPropertyName("po_number")]
  public string? PoNumber { get; set; }

  /// <summary>
  /// The unique identifier of the project associated with this purchase order
  /// </summary>
  [System.Text.Json.Serialization.JsonPropertyName("project_id")]
  public string? ProjectId { get; set; }

  /// <summary>
  /// The unique identifier of the recurring schedule
  /// </summary>
  [System.Text.Json.Serialization.JsonPropertyName("recurring_id")]
  public string? RecurringId { get; set; }

  /// <summary>
  /// Timestamp when the first reminder was sent
  /// </summary>
  [System.Text.Json.Serialization.JsonPropertyName("reminder1_sent")]
  public decimal? Reminder1Sent { get; set; }

  /// <summary>
  /// Timestamp when the second reminder was sent
  /// </summary>
  [System.Text.Json.Serialization.JsonPropertyName("reminder2_sent")]
  public decimal? Reminder2Sent { get; set; }

  /// <summary>
  /// Timestamp when the third reminder was sent
  /// </summary>
  [System.Text.Json.Serialization.JsonPropertyName("reminder3_sent")]
  public decimal? Reminder3Sent { get; set; }

  /// <summary>
  /// Timestamp when the last reminder was sent
  /// </summary>
  [System.Text.Json.Serialization.JsonPropertyName("reminder_last_sent")]
  public decimal? ReminderLastSent { get; set; }
}
