//
// <auto-generated>
// Invoice Ninja API Models - Auto-generated from OpenAPI specification
//
// Generated by: ApiGenerator
// Source: specs/invoiceninja.yaml
// API: Invoice Ninja API Reference.
// Version: 5.12.55
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
// </auto-generated>
//
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Text.Json;
using System.Text.Json.Serialization;

#nullable enable

namespace Apigen.InvoiceNinja.Models;

/// <summary>
/// PurchaseOrderRequestLineItems from OpenAPI schema.
/// Schema path: #/components/schemas/PurchaseOrderRequestLineItems
/// </summary>
public partial class PurchaseOrderRequestLineItems
{
  [JsonConverter(typeof(EmptyStringToNullableDecimalConverter))]
  [System.Text.Json.Serialization.JsonPropertyName("quantity")]
  public decimal? Quantity { get; set; }

  [JsonConverter(typeof(EmptyStringToNullableDecimalConverter))]
  [System.Text.Json.Serialization.JsonPropertyName("cost")]
  public decimal? Cost { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("product_key")]
  public string? ProductKey { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("notes")]
  public string? Notes { get; set; }

  [JsonConverter(typeof(EmptyStringToNullableDecimalConverter))]
  [System.Text.Json.Serialization.JsonPropertyName("discount")]
  public decimal? Discount { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("is_amount_discount")]
  public bool? IsAmountDiscount { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("tax_name1")]
  public string? TaxName1 { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("tax_rate1")]
  public decimal? TaxRate1 { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("tax_name2")]
  public string? TaxName2 { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("tax_rate2")]
  public decimal? TaxRate2 { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("tax_name3")]
  public string? TaxName3 { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("tax_rate3")]
  public decimal? TaxRate3 { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("sort_id")]
  public string? SortId { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("custom_value1")]
  public string? CustomValue1 { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("custom_value2")]
  public string? CustomValue2 { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("custom_value3")]
  public string? CustomValue3 { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("custom_value4")]
  public string? CustomValue4 { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("type_id")]
  public string? TypeId { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("tax_id")]
  public string? TaxId { get; set; }
}
