//
// <auto-generated>
// Invoice Ninja API Models - Auto-generated from OpenAPI specification
//
// Generated by: ApiGenerator
// Source: specs/invoiceninja.yaml
// API: Invoice Ninja API Reference.
// Version: 5.12.55
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
// </auto-generated>
//
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Text.Json;
using System.Text.Json.Serialization;

#nullable enable

namespace Apigen.InvoiceNinja.Models;

/// <summary>
/// RecurringExpense from OpenAPI schema.
/// Schema path: #/components/schemas/RecurringExpense
/// </summary>
public partial class RecurringExpense
{
  /// <summary>
  /// The hashed id of the recurring expense
  /// </summary>
  [System.Text.Json.Serialization.JsonPropertyName("id")]
  public string? Id { get; set; }

  /// <summary>
  /// The hashed id of the user who created the recurring expense
  /// </summary>
  [System.Text.Json.Serialization.JsonPropertyName("user_id")]
  public string? UserId { get; set; }

  /// <summary>
  /// The hashed id of the user assigned to this recurring expense
  /// </summary>
  [System.Text.Json.Serialization.JsonPropertyName("assigned_user_id")]
  public string? AssignedUserId { get; set; }

  /// <summary>
  /// The hashed id of the client
  /// </summary>
  [System.Text.Json.Serialization.JsonPropertyName("client_id")]
  public string? ClientId { get; set; }

  /// <summary>
  /// The hashed id of the invoice
  /// </summary>
  [System.Text.Json.Serialization.JsonPropertyName("invoice_id")]
  public string? InvoiceId { get; set; }

  /// <summary>
  /// The id of the bank associated with this recurring expense
  /// </summary>
  [System.Text.Json.Serialization.JsonPropertyName("bank_id")]
  public string? BankId { get; set; }

  /// <summary>
  /// The currency id of the invoice associated with this recurring expense
  /// </summary>
  [System.Text.Json.Serialization.JsonPropertyName("invoice_currency_id")]
  public string? InvoiceCurrencyId { get; set; }

  /// <summary>
  /// The currency id of the expense associated with this recurring expense
  /// </summary>
  [System.Text.Json.Serialization.JsonPropertyName("expense_currency_id")]
  public string? ExpenseCurrencyId { get; set; }

  /// <summary>
  /// The category id of the invoice
  /// </summary>
  [System.Text.Json.Serialization.JsonPropertyName("invoice_category_id")]
  public string? InvoiceCategoryId { get; set; }

  /// <summary>
  /// The payment type id
  /// </summary>
  [System.Text.Json.Serialization.JsonPropertyName("payment_type_id")]
  public string? PaymentTypeId { get; set; }

  /// <summary>
  /// The recurring expense private notes
  /// </summary>
  [System.Text.Json.Serialization.JsonPropertyName("private_notes")]
  public string? PrivateNotes { get; set; }

  /// <summary>
  /// The recurring expense public notes
  /// </summary>
  [System.Text.Json.Serialization.JsonPropertyName("public_notes")]
  public string? PublicNotes { get; set; }

  /// <summary>
  /// The recurring expense transaction reference
  /// </summary>
  [System.Text.Json.Serialization.JsonPropertyName("transaction_reference")]
  public string? TransactionReference { get; set; }

  /// <summary>
  /// The transaction id of the recurring expense
  /// </summary>
  [System.Text.Json.Serialization.JsonPropertyName("transcation_id")]
  public string? TranscationId { get; set; }

  /// <summary>
  /// Custom value field
  /// </summary>
  [System.Text.Json.Serialization.JsonPropertyName("custom_value1")]
  public string? CustomValue1 { get; set; }

  /// <summary>
  /// Custom value field
  /// </summary>
  [System.Text.Json.Serialization.JsonPropertyName("custom_value2")]
  public string? CustomValue2 { get; set; }

  /// <summary>
  /// Custom value field
  /// </summary>
  [System.Text.Json.Serialization.JsonPropertyName("custom_value3")]
  public string? CustomValue3 { get; set; }

  /// <summary>
  /// Custom value field
  /// </summary>
  [System.Text.Json.Serialization.JsonPropertyName("custom_value4")]
  public string? CustomValue4 { get; set; }

  /// <summary>
  /// The tax name
  /// </summary>
  [System.Text.Json.Serialization.JsonPropertyName("tax_name1")]
  public string? TaxName1 { get; set; }

  /// <summary>
  /// The tax name
  /// </summary>
  [System.Text.Json.Serialization.JsonPropertyName("tax_name2")]
  public string? TaxName2 { get; set; }

  /// <summary>
  /// The tax rate
  /// </summary>
  [System.Text.Json.Serialization.JsonPropertyName("tax_rate1")]
  public float? TaxRate1 { get; set; }

  /// <summary>
  /// The tax rate
  /// </summary>
  [System.Text.Json.Serialization.JsonPropertyName("tax_rate2")]
  public float? TaxRate2 { get; set; }

  /// <summary>
  /// The tax name
  /// </summary>
  [System.Text.Json.Serialization.JsonPropertyName("tax_name3")]
  public string? TaxName3 { get; set; }

  /// <summary>
  /// The tax rate
  /// </summary>
  [System.Text.Json.Serialization.JsonPropertyName("tax_rate3")]
  public float? TaxRate3 { get; set; }

  /// <summary>
  /// The total amount of the recurring expense
  /// </summary>
  [JsonConverter(typeof(EmptyStringToNullableDecimalConverter))]
  [System.Text.Json.Serialization.JsonPropertyName("amount")]
  public decimal? Amount { get; set; }

  /// <summary>
  /// The frequency this recurring expense fires
  /// </summary>
  [System.Text.Json.Serialization.JsonPropertyName("frequency_id")]
  public decimal? FrequencyId { get; set; }

  /// <summary>
  /// The number of remaining cycles for this recurring expense
  /// </summary>
  [System.Text.Json.Serialization.JsonPropertyName("remaining_cycles")]
  public decimal? RemainingCycles { get; set; }

  /// <summary>
  /// The foreign currency amount of the recurring expense
  /// </summary>
  [JsonConverter(typeof(EmptyStringToNullableDecimalConverter))]
  [System.Text.Json.Serialization.JsonPropertyName("foreign_amount")]
  public decimal? ForeignAmount { get; set; }

  /// <summary>
  /// The exchange rate for the expernse
  /// </summary>
  [JsonConverter(typeof(EmptyStringToNullableDecimalConverter))]
  [System.Text.Json.Serialization.JsonPropertyName("exchange_rate")]
  public decimal? ExchangeRate { get; set; }

  /// <summary>
  /// The date of the expense
  /// </summary>
  [System.Text.Json.Serialization.JsonPropertyName("date")]
  public string? Date { get; set; }

  /// <summary>
  /// The date the expense was paid
  /// </summary>
  [System.Text.Json.Serialization.JsonPropertyName("payment_date")]
  public string? PaymentDate { get; set; }

  /// <summary>
  /// Boolean flag determining if the expense should be invoiced
  /// </summary>
  [System.Text.Json.Serialization.JsonPropertyName("should_be_invoiced")]
  public bool? ShouldBeInvoiced { get; set; }

  /// <summary>
  /// Boolean flag determining if the recurring expense is deleted
  /// </summary>
  [System.Text.Json.Serialization.JsonPropertyName("is_deleted")]
  public bool? IsDeleted { get; set; }

  /// <summary>
  /// The Date it was sent last
  /// </summary>
  [System.Text.Json.Serialization.JsonPropertyName("last_sent_date")]
  public DateOnly? LastSentDate { get; set; }

  /// <summary>
  /// The next send date
  /// </summary>
  [System.Text.Json.Serialization.JsonPropertyName("next_send_date")]
  public DateOnly? NextSendDate { get; set; }

  /// <summary>
  /// Boolean flag determining if the documents associated with this expense should be passed onto the invoice if it is converted to an invoice
  /// </summary>
  [System.Text.Json.Serialization.JsonPropertyName("invoice_documents")]
  public bool? InvoiceDocuments { get; set; }

  /// <summary>
  /// Timestamp
  /// </summary>
  [JsonConverter(typeof(UnixTimestampConverter))]
  [System.Text.Json.Serialization.JsonPropertyName("updated_at")]
  public DateTimeOffset? UpdatedAt { get; set; }

  /// <summary>
  /// Timestamp
  /// </summary>
  [JsonConverter(typeof(UnixTimestampConverter))]
  [System.Text.Json.Serialization.JsonPropertyName("archived_at")]
  public DateTimeOffset? ArchivedAt { get; set; }

  /// <summary>
  /// Flag indicating whether to calculate tax based on amount rather than percentage
  /// </summary>
  [System.Text.Json.Serialization.JsonPropertyName("calculate_tax_by_amount")]
  public bool? CalculateTaxByAmount { get; set; }

  /// <summary>
  /// The unique identifier of the expense category
  /// </summary>
  [System.Text.Json.Serialization.JsonPropertyName("category_id")]
  public string? CategoryId { get; set; }

  /// <summary>
  /// The unique identifier of the currency
  /// </summary>
  [System.Text.Json.Serialization.JsonPropertyName("currency_id")]
  public string? CurrencyId { get; set; }

  /// <summary>
  /// The next scheduled send date for the client
  /// </summary>
  [System.Text.Json.Serialization.JsonPropertyName("next_send_date_client")]
  public DateOnly? NextSendDateClient { get; set; }

  /// <summary>
  /// The unique number assigned to this recurring expense
  /// </summary>
  [System.Text.Json.Serialization.JsonPropertyName("number")]
  public string? Number { get; set; }

  /// <summary>
  /// The unique identifier of the project associated with this recurring expense
  /// </summary>
  [System.Text.Json.Serialization.JsonPropertyName("project_id")]
  public string? ProjectId { get; set; }

  /// <summary>
  /// The amount of the first tax
  /// </summary>
  [System.Text.Json.Serialization.JsonPropertyName("tax_amount1")]
  public float? TaxAmount1 { get; set; }

  /// <summary>
  /// The amount of the second tax
  /// </summary>
  [System.Text.Json.Serialization.JsonPropertyName("tax_amount2")]
  public float? TaxAmount2 { get; set; }

  /// <summary>
  /// The amount of the third tax
  /// </summary>
  [System.Text.Json.Serialization.JsonPropertyName("tax_amount3")]
  public float? TaxAmount3 { get; set; }

  /// <summary>
  /// The unique identifier of the transaction
  /// </summary>
  [System.Text.Json.Serialization.JsonPropertyName("transaction_id")]
  public string? TransactionId { get; set; }

  /// <summary>
  /// Flag indicating whether taxes are included in the price
  /// </summary>
  [System.Text.Json.Serialization.JsonPropertyName("uses_inclusive_taxes")]
  public bool? UsesInclusiveTaxes { get; set; }

  /// <summary>
  /// The unique identifier of the vendor associated with this recurring expense
  /// </summary>
  [System.Text.Json.Serialization.JsonPropertyName("vendor_id")]
  public string? VendorId { get; set; }
}
