//
// <auto-generated>
// Invoice Ninja API Models - Auto-generated from OpenAPI specification
//
// Generated by: ApiGenerator
// Source: specs/invoiceninja.yaml
// API: Invoice Ninja API Reference.
// Version: 5.12.55
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
// </auto-generated>
//
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Text.Json;
using System.Text.Json.Serialization;

#nullable enable

namespace Apigen.InvoiceNinja.Models;

/// <summary>
/// Tag from OpenAPI schema.
/// Schema path: #/components/schemas/Tag
/// </summary>
public partial class Tag
{
  /// <summary>
  /// The hashed tag id
  /// </summary>
  [Required]
  [System.Text.Json.Serialization.JsonPropertyName("id")]
  public string? Id { get; set; }

  /// <summary>
  /// The fully qualified class name this tag may be assigned to
  /// </summary>
  [Required]
  [System.Text.Json.Serialization.JsonPropertyName("entity_type")]
  public string? EntityType { get; set; }

  /// <summary>
  /// The tag name. Commas are not allowed. Unique per company and entity type, including archived tags.
  /// </summary>
  [Required]
  [MaxLength(191)]
  [RegularExpression(@"^[^,]+$")]
  [System.Text.Json.Serialization.JsonPropertyName("name")]
  public string? Name { get; set; }

  /// <summary>
  /// The tag color as a 3 or 6 digit hex value, or null when unset
  /// </summary>
  [Required]
  [RegularExpression(@"^#(?:[0-9a-fA-F]{3}){1,2}$")]
  [System.Text.Json.Serialization.JsonPropertyName("color")]
  public string? Color { get; set; }

  /// <summary>
  /// A boolean flag determining if the tag has been deleted
  /// </summary>
  [Required]
  [System.Text.Json.Serialization.JsonPropertyName("is_deleted")]
  public bool IsDeleted { get; set; }

  /// <summary>
  /// Timestamp
  /// </summary>
  [JsonConverter(typeof(UnixTimestampConverter))]
  [System.Text.Json.Serialization.JsonPropertyName("created_at")]
  public DateTimeOffset? CreatedAt { get; set; }

  /// <summary>
  /// Timestamp
  /// </summary>
  [JsonConverter(typeof(UnixTimestampConverter))]
  [System.Text.Json.Serialization.JsonPropertyName("updated_at")]
  public DateTimeOffset? UpdatedAt { get; set; }

  /// <summary>
  /// Timestamp
  /// </summary>
  [JsonConverter(typeof(UnixTimestampConverter))]
  [System.Text.Json.Serialization.JsonPropertyName("archived_at")]
  public DateTimeOffset? ArchivedAt { get; set; }
}
