//
// <auto-generated>
// Invoice Ninja API Models - Auto-generated from OpenAPI specification
//
// Generated by: ApiGenerator
// Source: specs/invoiceninja.yaml
// API: Invoice Ninja API Reference.
// Version: 5.12.55
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
// </auto-generated>
//
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Text.Json;
using System.Text.Json.Serialization;

#nullable enable

namespace Apigen.InvoiceNinja.Models;

/// <summary>
/// TagBulkAction from OpenAPI schema.
/// Schema path: #/components/schemas/TagBulkAction
/// </summary>
public partial class TagBulkAction
{
  /// <summary>
  /// Array of hashed tag IDs to action
  /// </summary>
  [Required]
  [System.Text.Json.Serialization.JsonPropertyName("ids")]
  public List<string?>? Ids { get; set; }

  /// <summary>
  /// Bulk action to perform. May be supplied in the query string or request body.
  /// </summary>
  [System.Text.Json.Serialization.JsonPropertyName("action")]
  public string? Action { get; set; }
}
