//
// <auto-generated>
// Invoice Ninja API Models - Auto-generated from OpenAPI specification
//
// Generated by: ApiGenerator
// Source: specs/invoiceninja.yaml
// API: Invoice Ninja API Reference.
// Version: 5.12.55
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
// </auto-generated>
//
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Text.Json;
using System.Text.Json.Serialization;

#nullable enable

namespace Apigen.InvoiceNinja.Models;

/// <summary>
/// TagRequest from OpenAPI schema.
/// Schema path: #/components/schemas/TagRequest
/// </summary>
public partial class TagRequest
{
  /// <summary>
  /// Required on create. Immutable after creation.
  /// </summary>
  [Required]
  [System.Text.Json.Serialization.JsonIgnore(Condition = System.Text.Json.Serialization.JsonIgnoreCondition.Never)]
  [System.Text.Json.Serialization.JsonPropertyName("entity_type")]
  public string? EntityType { get; set; }

  /// <summary>
  /// The tag name. Commas are not allowed. Unique per company and entity type, including archived tags.
  /// </summary>
  [Required]
  [MaxLength(191)]
  [RegularExpression(@"^[^,]+$")]
  [System.Text.Json.Serialization.JsonIgnore(Condition = System.Text.Json.Serialization.JsonIgnoreCondition.Never)]
  [System.Text.Json.Serialization.JsonPropertyName("name")]
  public string? Name { get; set; }

  /// <summary>
  /// The tag color as a 3 or 6 digit hex value, or null to clear it.
  /// </summary>
  [RegularExpression(@"^#(?:[0-9a-fA-F]{3}){1,2}$")]
  [System.Text.Json.Serialization.JsonPropertyName("color")]
  public string? Color { get; set; }
}
