//
// <auto-generated>
// Invoice Ninja API Models - Auto-generated from OpenAPI specification
//
// Generated by: ApiGenerator
// Source: specs/invoiceninja.yaml
// API: Invoice Ninja API Reference.
// Version: 5.11.48
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
// </auto-generated>
//
using System;
using System.Text.Json.Serialization;

#nullable enable

namespace Apigen.InvoiceNinja.Models;

/// <summary>
/// Which tasks to show in client portal
/// </summary>
[JsonConverter(typeof(JsonStringEnumConverter))]
public enum TaskDisplayMode
{
    [JsonPropertyName("all")]
    All,

    [JsonPropertyName("invoiced")]
    Invoiced,

    [JsonPropertyName("uninvoiced")]
    Uninvoiced
}
