//
// <auto-generated>
// Invoice Ninja API Models - Auto-generated from OpenAPI specification
//
// Generated by: ApiGenerator
// Source: specs/invoiceninja.yaml
// API: Invoice Ninja API Reference.
// Version: 5.12.55
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
// </auto-generated>
//
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Text.Json;
using System.Text.Json.Serialization;

#nullable enable

namespace Apigen.InvoiceNinja.Models;

/// <summary>
/// Task from OpenAPI schema.
/// Schema path: #/components/schemas/Task
/// </summary>
public partial class TaskItem
{
  /// <summary>
  /// The hashed id of the task
  /// </summary>
  [System.Text.Json.Serialization.JsonPropertyName("id")]
  public string? Id { get; set; }

  /// <summary>
  /// The hashed id of the user who created the task
  /// </summary>
  [System.Text.Json.Serialization.JsonPropertyName("user_id")]
  public string? UserId { get; set; }

  /// <summary>
  /// The assigned user of the task
  /// </summary>
  [System.Text.Json.Serialization.JsonPropertyName("assigned_user_id")]
  public string? AssignedUserId { get; set; }

  /// <summary>
  /// The hashed if of the client
  /// </summary>
  [System.Text.Json.Serialization.JsonPropertyName("client_id")]
  public string? ClientId { get; set; }

  /// <summary>
  /// The hashed id of the invoice associated with the task
  /// </summary>
  [System.Text.Json.Serialization.JsonPropertyName("invoice_id")]
  public string? InvoiceId { get; set; }

  /// <summary>
  /// The hashed id of the project associated with the task
  /// </summary>
  [System.Text.Json.Serialization.JsonPropertyName("project_id")]
  public string? ProjectId { get; set; }

  /// <summary>
  /// The number of the task
  /// </summary>
  [System.Text.Json.Serialization.JsonPropertyName("number")]
  public string? Number { get; set; }

  /// <summary>
  /// An array of unix time stamps defining the start and end times of the task
  /// </summary>
  [System.Text.Json.Serialization.JsonPropertyName("time_log")]
  public string? TimeLog { get; set; }

  /// <summary>
  /// Determines if the task is still running
  /// </summary>
  [System.Text.Json.Serialization.JsonPropertyName("is_running")]
  public bool? IsRunning { get; set; }

  /// <summary>
  /// Boolean flag determining if the task has been deleted
  /// </summary>
  [System.Text.Json.Serialization.JsonPropertyName("is_deleted")]
  public bool? IsDeleted { get; set; }

  /// <summary>
  /// The hashed id of the task status
  /// </summary>
  [System.Text.Json.Serialization.JsonPropertyName("task_status_id")]
  public string? TaskStatusId { get; set; }

  /// <summary>
  /// The task description
  /// </summary>
  [System.Text.Json.Serialization.JsonPropertyName("description")]
  public string? Description { get; set; }

  /// <summary>
  /// The task duration in seconds
  /// </summary>
  [JsonConverter(typeof(StringToIntegerConverter))]
  [System.Text.Json.Serialization.JsonPropertyName("duration")]
  public int? Duration { get; set; }

  /// <summary>
  /// The order of the task
  /// </summary>
  [JsonConverter(typeof(StringToIntegerConverter))]
  [System.Text.Json.Serialization.JsonPropertyName("task_status_order")]
  public int? TaskStatusOrder { get; set; }

  /// <summary>
  /// The task rate
  /// </summary>
  [JsonConverter(typeof(EmptyStringToNullableDecimalConverter))]
  [System.Text.Json.Serialization.JsonPropertyName("rate")]
  public decimal? Rate { get; set; }

  /// <summary>
  /// A custom value
  /// </summary>
  [System.Text.Json.Serialization.JsonPropertyName("custom_value1")]
  public string? CustomValue1 { get; set; }

  /// <summary>
  /// A custom value
  /// </summary>
  [System.Text.Json.Serialization.JsonPropertyName("custom_value2")]
  public string? CustomValue2 { get; set; }

  /// <summary>
  /// A custom value
  /// </summary>
  [System.Text.Json.Serialization.JsonPropertyName("custom_value3")]
  public string? CustomValue3 { get; set; }

  /// <summary>
  /// A custom value
  /// </summary>
  [System.Text.Json.Serialization.JsonPropertyName("custom_value4")]
  public string? CustomValue4 { get; set; }

  /// <summary>
  /// Boolean flag determining if the task is date based
  /// </summary>
  [System.Text.Json.Serialization.JsonPropertyName("is_date_based")]
  public bool? IsDateBased { get; set; }

  /// <summary>
  /// The calculated start date of the task
  /// </summary>
  [System.Text.Json.Serialization.JsonPropertyName("calculated_start_date")]
  public string? CalculatedStartDate { get; set; }

  /// <summary>
  /// Boolean flags which determines whether to include the task documents on the invoice
  /// </summary>
  [System.Text.Json.Serialization.JsonPropertyName("invoice_documents")]
  public bool? InvoiceDocuments { get; set; }

  /// <summary>
  /// Timestamp
  /// </summary>
  [JsonConverter(typeof(UnixTimestampConverter))]
  [System.Text.Json.Serialization.JsonPropertyName("created_at")]
  public DateTimeOffset? CreatedAt { get; set; }

  /// <summary>
  /// Timestamp
  /// </summary>
  [JsonConverter(typeof(UnixTimestampConverter))]
  [System.Text.Json.Serialization.JsonPropertyName("updated_at")]
  public DateTimeOffset? UpdatedAt { get; set; }

  /// <summary>
  /// Timestamp
  /// </summary>
  [JsonConverter(typeof(UnixTimestampConverter))]
  [System.Text.Json.Serialization.JsonPropertyName("archived_at")]
  public DateTimeOffset? ArchivedAt { get; set; }

  /// <summary>
  /// Unique hash identifier for this task
  /// </summary>
  [System.Text.Json.Serialization.JsonPropertyName("hash")]
  public string? Hash { get; set; }

  /// <summary>
  /// Metadata associated with this task
  /// </summary>
  [System.Text.Json.Serialization.JsonPropertyName("meta")]
  public object? Meta { get; set; }

  /// <summary>
  /// The unique identifier of the task status
  /// </summary>
  [System.Text.Json.Serialization.JsonPropertyName("status_id")]
  public string? StatusId { get; set; }

  /// <summary>
  /// Sort order for status display
  /// </summary>
  [JsonConverter(typeof(StringToIntegerConverter))]
  [System.Text.Json.Serialization.JsonPropertyName("status_order")]
  public int? StatusOrder { get; set; }

  /// <summary>
  /// Alternative sort order for status
  /// </summary>
  [JsonConverter(typeof(StringToIntegerConverter))]
  [System.Text.Json.Serialization.JsonPropertyName("status_sort_order")]
  public int? StatusSortOrder { get; set; }
}
