//
// <auto-generated>
// Invoice Ninja API Models - Auto-generated from OpenAPI specification
//
// Generated by: ApiGenerator
// Source: specs/invoiceninja.yaml
// API: Invoice Ninja API Reference.
// Version: 5.11.48
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
// </auto-generated>
//
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Text.Json;
using System.Text.Json.Serialization;

#nullable enable

namespace Apigen.InvoiceNinja.Models;

/// <summary>
/// UpdateLocationRequest from OpenAPI schema.
/// Schema path: #/components/schemas/UpdateLocationRequest
/// </summary>
public class UpdateLocationRequest
{
  /// <summary>
  /// The location name
  /// </summary>
  [System.Text.Json.Serialization.JsonIgnore(Condition = System.Text.Json.Serialization.JsonIgnoreCondition.WhenWritingNull)]
  [System.Text.Json.Serialization.JsonPropertyName("name")]
  public string? Name { get; set; }

  /// <summary>
  /// The first line of the address
  /// </summary>
  [System.Text.Json.Serialization.JsonIgnore(Condition = System.Text.Json.Serialization.JsonIgnoreCondition.WhenWritingNull)]
  [System.Text.Json.Serialization.JsonPropertyName("address1")]
  public string? Address1 { get; set; }

  /// <summary>
  /// The second line of the address
  /// </summary>
  [System.Text.Json.Serialization.JsonIgnore(Condition = System.Text.Json.Serialization.JsonIgnoreCondition.WhenWritingNull)]
  [System.Text.Json.Serialization.JsonPropertyName("address2")]
  public string? Address2 { get; set; }

  /// <summary>
  /// The city name
  /// </summary>
  [System.Text.Json.Serialization.JsonIgnore(Condition = System.Text.Json.Serialization.JsonIgnoreCondition.WhenWritingNull)]
  [System.Text.Json.Serialization.JsonPropertyName("city")]
  public string? City { get; set; }

  /// <summary>
  /// The state or region
  /// </summary>
  [System.Text.Json.Serialization.JsonIgnore(Condition = System.Text.Json.Serialization.JsonIgnoreCondition.WhenWritingNull)]
  [System.Text.Json.Serialization.JsonPropertyName("state")]
  public string? State { get; set; }

  /// <summary>
  /// The postal or zip code
  /// </summary>
  [System.Text.Json.Serialization.JsonIgnore(Condition = System.Text.Json.Serialization.JsonIgnoreCondition.WhenWritingNull)]
  [System.Text.Json.Serialization.JsonPropertyName("postal_code")]
  public string? PostalCode { get; set; }

  /// <summary>
  /// The ID of the associated country
  /// </summary>
  [System.Text.Json.Serialization.JsonIgnore(Condition = System.Text.Json.Serialization.JsonIgnoreCondition.WhenWritingNull)]
  [System.Text.Json.Serialization.JsonPropertyName("country_id")]
  public string? CountryId { get; set; }

  /// <summary>
  /// Custom field value 1
  /// </summary>
  [System.Text.Json.Serialization.JsonPropertyName("custom_value1")]
  public string? CustomValue1 { get; set; }

  /// <summary>
  /// Custom field value 2
  /// </summary>
  [System.Text.Json.Serialization.JsonPropertyName("custom_value2")]
  public string? CustomValue2 { get; set; }

  /// <summary>
  /// Custom field value 3
  /// </summary>
  [System.Text.Json.Serialization.JsonPropertyName("custom_value3")]
  public string? CustomValue3 { get; set; }

  /// <summary>
  /// Custom field value 4
  /// </summary>
  [System.Text.Json.Serialization.JsonPropertyName("custom_value4")]
  public string? CustomValue4 { get; set; }

  /// <summary>
  /// Indicates if this is a shipping location
  /// </summary>
  [System.Text.Json.Serialization.JsonIgnore(Condition = System.Text.Json.Serialization.JsonIgnoreCondition.WhenWritingNull)]
  [System.Text.Json.Serialization.JsonPropertyName("is_shipping_location")]
  public bool? IsShippingLocation { get; set; }

  /// <summary>
  /// The assigned user hashed id
  /// </summary>
  [System.Text.Json.Serialization.JsonIgnore(Condition = System.Text.Json.Serialization.JsonIgnoreCondition.WhenWritingNull)]
  [System.Text.Json.Serialization.JsonPropertyName("assigned_user_id")]
  public string? AssignedUserId { get; set; }

  /// <summary>
  /// The client hashed id
  /// </summary>
  [System.Text.Json.Serialization.JsonIgnore(Condition = System.Text.Json.Serialization.JsonIgnoreCondition.WhenWritingNull)]
  [System.Text.Json.Serialization.JsonPropertyName("client_id")]
  public string? ClientId { get; set; }

  /// <summary>
  /// The vendor hashed id
  /// </summary>
  [System.Text.Json.Serialization.JsonIgnore(Condition = System.Text.Json.Serialization.JsonIgnoreCondition.WhenWritingNull)]
  [System.Text.Json.Serialization.JsonPropertyName("vendor_id")]
  public string? VendorId { get; set; }
}
