//
// <auto-generated>
// Invoice Ninja API Models - Auto-generated from OpenAPI specification
//
// Generated by: ApiGenerator
// Source: specs/invoiceninja.yaml
// API: Invoice Ninja API Reference.
// Version: 5.12.55
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
// </auto-generated>
//
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Text.Json;
using System.Text.Json.Serialization;

#nullable enable

namespace Apigen.InvoiceNinja.Models;

/// <summary>
/// UpdateTagRequest (generated from inline request body).
/// Source: PUT /api/v1/tags/{id} (requestBody)
/// </summary>
public partial class UpdateTagRequest
{
  [MaxLength(191)]
  [System.Text.Json.Serialization.JsonIgnore(Condition = System.Text.Json.Serialization.JsonIgnoreCondition.WhenWritingNull)]
  [System.Text.Json.Serialization.JsonPropertyName("name")]
  public string? Name { get; set; }

  [RegularExpression(@"^#(?:[0-9a-fA-F]{3}){1,2}$")]
  [System.Text.Json.Serialization.JsonPropertyName("color")]
  public string? Color { get; set; }
}
