//
// <auto-generated>
// Invoice Ninja API Models - Auto-generated from OpenAPI specification
//
// Generated by: ApiGenerator
// Source: specs/invoiceninja.yaml
// API: Invoice Ninja API Reference.
// Version: 5.12.55
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
// </auto-generated>
//
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Text.Json;
using System.Text.Json.Serialization;

#nullable enable

namespace Apigen.InvoiceNinja.Models;

/// <summary>
/// UploadClientRequest from OpenAPI schema.
/// Schema path: #/components/schemas/UploadClientRequest
/// </summary>
public class UploadClientRequest
{
  [System.Text.Json.Serialization.JsonIgnore(Condition = System.Text.Json.Serialization.JsonIgnoreCondition.WhenWritingNull)]
  [System.Text.Json.Serialization.JsonPropertyName("_method")]
  public string? Method { get; set; }

  /// <summary>
  /// Array of files to upload. The files should be sent with the key name &apos;documents[]&apos;.
  /// 
  /// Supported file types:
  /// PDF (.pdf)
  /// Word (.doc, .docx)
  /// Excel (.xls, .xlsx)
  /// Images (.jpg, .jpeg, .png)
  /// Text (.txt)
  /// 
  /// Maximum file size: 20MB per file
  /// 
  /// </summary>
  [System.Text.Json.Serialization.JsonIgnore(Condition = System.Text.Json.Serialization.JsonIgnoreCondition.WhenWritingNull)]
  [System.Text.Json.Serialization.JsonPropertyName("documents[]")]
  public byte[][]? Documents { get; set; }
}
