//
// <auto-generated>
// Invoice Ninja API Models - Auto-generated from OpenAPI specification
//
// Generated by: ApiGenerator
// Source: specs/invoiceninja.yaml
// API: Invoice Ninja API Reference.
// Version: 5.11.48
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
// </auto-generated>
//
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Text.Json;
using System.Text.Json.Serialization;

#nullable enable

namespace Apigen.InvoiceNinja.Models;

/// <summary>
/// UserRef from OpenAPI schema.
/// Schema path: #/components/schemas/UserRef
/// </summary>
public class UserRef
{
  /// <summary>
  /// The hashed id of the user
  /// </summary>
  [System.Text.Json.Serialization.JsonPropertyName("id")]
  public string? Id { get; set; }

  /// <summary>
  /// The first name of the user
  /// </summary>
  [System.Text.Json.Serialization.JsonPropertyName("first_name")]
  public string? FirstName { get; set; }

  /// <summary>
  /// The last name of the user
  /// </summary>
  [System.Text.Json.Serialization.JsonPropertyName("last_name")]
  public string? LastName { get; set; }

  /// <summary>
  /// The users email address
  /// </summary>
  [System.Text.Json.Serialization.JsonPropertyName("email")]
  public string? Email { get; set; }

  /// <summary>
  /// The users phone number
  /// </summary>
  [System.Text.Json.Serialization.JsonPropertyName("phone")]
  public string? Phone { get; set; }

  /// <summary>
  /// The users sign off signature
  /// </summary>
  [System.Text.Json.Serialization.JsonPropertyName("signature")]
  public string? Signature { get; set; }

  /// <summary>
  /// The users avatar
  /// </summary>
  [System.Text.Json.Serialization.JsonPropertyName("avatar")]
  public string? Avatar { get; set; }

  /// <summary>
  /// The version of the invoice ninja terms that has been accepted by the user
  /// </summary>
  [System.Text.Json.Serialization.JsonPropertyName("accepted_terms_version")]
  public string? AcceptedTermsVersion { get; set; }

  /// <summary>
  /// The provider id of the oauth entity
  /// </summary>
  [System.Text.Json.Serialization.JsonPropertyName("oauth_user_id")]
  public string? OauthUserId { get; set; }

  /// <summary>
  /// The oauth entity id
  /// </summary>
  [System.Text.Json.Serialization.JsonPropertyName("oauth_provider_id")]
  public string? OauthProviderId { get; set; }

  /// <summary>
  /// The language id of the user
  /// </summary>
  [System.Text.Json.Serialization.JsonPropertyName("language_id")]
  public string? LanguageId { get; set; }

  /// <summary>
  /// Boolean flag if the user has their phone verified. Required to settings up 2FA
  /// </summary>
  [System.Text.Json.Serialization.JsonPropertyName("verified_phone_number")]
  public bool? VerifiedPhoneNumber { get; set; }

  /// <summary>
  /// The sms verification code for the user. Required to settings up 2FA
  /// </summary>
  [System.Text.Json.Serialization.JsonPropertyName("sms_verification_code")]
  public string? SmsVerificationCode { get; set; }

  /// <summary>
  /// The expiry date of the oauth token
  /// </summary>
  [System.Text.Json.Serialization.JsonPropertyName("oauth_user_token_expiry")]
  public string? OauthUserTokenExpiry { get; set; }

  /// <summary>
  /// Boolean flag determining if the user has a password
  /// </summary>
  [System.Text.Json.Serialization.JsonPropertyName("has_password")]
  public bool? HasPassword { get; set; }

  /// <summary>
  /// The last confirmed email address of the user
  /// </summary>
  [System.Text.Json.Serialization.JsonPropertyName("last_confirmed_email_address")]
  public string? LastConfirmedEmailAddress { get; set; }

  /// <summary>
  /// A custom value
  /// </summary>
  [System.Text.Json.Serialization.JsonPropertyName("custom_value1")]
  public string? CustomValue1 { get; set; }

  /// <summary>
  /// A custom value
  /// </summary>
  [System.Text.Json.Serialization.JsonPropertyName("custom_value2")]
  public string? CustomValue2 { get; set; }

  /// <summary>
  /// A custom value
  /// </summary>
  [System.Text.Json.Serialization.JsonPropertyName("custom_value3")]
  public string? CustomValue3 { get; set; }

  /// <summary>
  /// A custom value
  /// </summary>
  [System.Text.Json.Serialization.JsonPropertyName("custom_value4")]
  public string? CustomValue4 { get; set; }

  /// <summary>
  /// Boolean flag determining if the user has been deleted
  /// </summary>
  [System.Text.Json.Serialization.JsonPropertyName("is_deleted")]
  public bool? IsDeleted { get; set; }

  /// <summary>
  /// The google 2fa secret for the user
  /// </summary>
  [JsonConverter(typeof(BooleanFalseToNullStringConverter))]
  [System.Text.Json.Serialization.JsonPropertyName("google_2fa_secret")]
  public string? Google2faSecret { get; set; }
}
