//
// <auto-generated>
// Invoice Ninja API Models - Auto-generated from OpenAPI specification
//
// Generated by: ApiGenerator
// Source: specs/invoiceninja.yaml
// API: Invoice Ninja API Reference.
// Version: 5.11.48
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
// </auto-generated>
//
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Text.Json;
using System.Text.Json.Serialization;

#nullable enable

namespace Apigen.InvoiceNinja.Models;

/// <summary>
/// ValidationError from OpenAPI schema.
/// Schema path: #/components/schemas/ValidationError
/// </summary>
public class ValidationError
{
  /// <summary>
  /// The error message
  /// </summary>
  [System.Text.Json.Serialization.JsonPropertyName("message")]
  public string? Message { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("errors")]
  public object? Errors { get; set; }
}
