//
// <auto-generated>
// Invoice Ninja API Models - Auto-generated from OpenAPI specification
//
// Generated by: ApiGenerator
// Source: specs/invoiceninja.yaml
// API: Invoice Ninja API Reference.
// Version: 5.12.55
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
// </auto-generated>
//
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Text.Json;
using System.Text.Json.Serialization;

#nullable enable

namespace Apigen.InvoiceNinja.Models;

/// <summary>
/// Vendor from OpenAPI schema.
/// Schema path: #/components/schemas/Vendor
/// </summary>
public partial class Vendor
{
  /// <summary>
  /// The hashed id of the vendor. This is a unique identifier for the vendor.
  /// </summary>
  [System.Text.Json.Serialization.JsonPropertyName("id")]
  public string? Id { get; set; }

  /// <summary>
  /// The hashed id of the user who created the vendor. This is a unique identifier for the user.
  /// </summary>
  [System.Text.Json.Serialization.JsonPropertyName("user_id")]
  public string? UserId { get; set; }

  /// <summary>
  /// The hashed id of the assigned user to this vendor. This is a unique identifier for the user.
  /// </summary>
  [System.Text.Json.Serialization.JsonPropertyName("assigned_user_id")]
  public string? AssignedUserId { get; set; }

  /// <summary>
  /// An array of contacts associated with the vendor.
  /// </summary>
  [System.Text.Json.Serialization.JsonPropertyName("contacts")]
  public List<VendorContact>? Contacts { get; set; }

  /// <summary>
  /// The name of the vendor.
  /// </summary>
  [System.Text.Json.Serialization.JsonPropertyName("name")]
  public string? Name { get; set; }

  /// <summary>
  /// The classification of the vendor.
  /// </summary>
  [System.Text.Json.Serialization.JsonPropertyName("classification")]
  public string? Classification { get; set; }

  /// <summary>
  /// The website of the vendor.
  /// </summary>
  [System.Text.Json.Serialization.JsonPropertyName("website")]
  public string? Website { get; set; }

  /// <summary>
  /// The private notes of the vendor. These notes are only visible to users with appropriate permissions.
  /// </summary>
  [System.Text.Json.Serialization.JsonPropertyName("private_notes")]
  public string? PrivateNotes { get; set; }

  /// <summary>
  /// The industry id of the vendor. This is a unique identifier for the industry.
  /// </summary>
  [System.Text.Json.Serialization.JsonPropertyName("industry_id")]
  public string? IndustryId { get; set; }

  /// <summary>
  /// The size id of the vendor. This is a unique identifier for the size of the vendor.
  /// </summary>
  [System.Text.Json.Serialization.JsonPropertyName("size_id")]
  public string? SizeId { get; set; }

  /// <summary>
  /// The first line of the vendor&apos;s address.
  /// </summary>
  [System.Text.Json.Serialization.JsonPropertyName("address1")]
  public string? Address1 { get; set; }

  /// <summary>
  /// The second line of the vendor&apos;s address.
  /// </summary>
  [System.Text.Json.Serialization.JsonPropertyName("address2")]
  public string? Address2 { get; set; }

  /// <summary>
  /// The city of the vendor&apos;s address.
  /// </summary>
  [System.Text.Json.Serialization.JsonPropertyName("city")]
  public string? City { get; set; }

  /// <summary>
  /// The state of the vendor&apos;s address.
  /// </summary>
  [System.Text.Json.Serialization.JsonPropertyName("state")]
  public string? State { get; set; }

  /// <summary>
  /// The postal code of the vendor&apos;s address.
  /// </summary>
  [System.Text.Json.Serialization.JsonPropertyName("postal_code")]
  public string? PostalCode { get; set; }

  /// <summary>
  /// The phone number of the vendor.
  /// </summary>
  [System.Text.Json.Serialization.JsonPropertyName("phone")]
  public string? Phone { get; set; }

  /// <summary>
  /// The country id of the vendor. This is a unique identifier for the country.
  /// </summary>
  [JsonConverter(typeof(EmptyStringToNullableEnumConverter<CountryType>))]
  [System.Text.Json.Serialization.JsonPropertyName("country_id")]
  public CountryType? CountryId { get; set; }

  /// <summary>
  /// The currency id of the vendor. This is a unique identifier for the currency.
  /// </summary>
  [System.Text.Json.Serialization.JsonPropertyName("currency_id")]
  public string? CurrencyId { get; set; }

  /// <summary>
  /// The value of the first custom field for the vendor.
  /// </summary>
  [System.Text.Json.Serialization.JsonPropertyName("custom_value1")]
  public string? CustomValue1 { get; set; }

  /// <summary>
  /// The value of the second custom field for the vendor.
  /// </summary>
  [System.Text.Json.Serialization.JsonPropertyName("custom_value2")]
  public string? CustomValue2 { get; set; }

  /// <summary>
  /// The value of the third custom field for the vendor.
  /// </summary>
  [System.Text.Json.Serialization.JsonPropertyName("custom_value3")]
  public string? CustomValue3 { get; set; }

  /// <summary>
  /// The value of the fourth custom field for the vendor.
  /// </summary>
  [System.Text.Json.Serialization.JsonPropertyName("custom_value4")]
  public string? CustomValue4 { get; set; }

  /// <summary>
  /// The VAT number of the vendor.
  /// </summary>
  [System.Text.Json.Serialization.JsonPropertyName("vat_number")]
  public string? VatNumber { get; set; }

  /// <summary>
  /// The ID number of the vendor.
  /// </summary>
  [System.Text.Json.Serialization.JsonPropertyName("id_number")]
  public string? IdNumber { get; set; }

  /// <summary>
  /// The number of the vendor
  /// </summary>
  [System.Text.Json.Serialization.JsonPropertyName("number")]
  public string? Number { get; set; }

  /// <summary>
  /// Boolean flag determining if the vendor has been deleted
  /// </summary>
  [System.Text.Json.Serialization.JsonPropertyName("is_deleted")]
  public bool? IsDeleted { get; set; }

  /// <summary>
  /// The language id of the vendor. This is a unique identifier for the language.
  /// </summary>
  [System.Text.Json.Serialization.JsonPropertyName("language_id")]
  public string? LanguageId { get; set; }

  /// <summary>
  /// The vendor hash of the vendor. This is a unique identifier for the vendor.
  /// </summary>
  [System.Text.Json.Serialization.JsonPropertyName("vendor_hash")]
  public string? VendorHash { get; set; }

  /// <summary>
  /// The transaction name of the vendor.
  /// </summary>
  [System.Text.Json.Serialization.JsonPropertyName("transaction_name")]
  public string? TransactionName { get; set; }

  /// <summary>
  /// Timestamp
  /// </summary>
  [System.Text.Json.Serialization.JsonPropertyName("last_login")]
  public decimal? LastLogin { get; set; }

  /// <summary>
  /// Timestamp
  /// </summary>
  [JsonConverter(typeof(UnixTimestampConverter))]
  [System.Text.Json.Serialization.JsonPropertyName("created_at")]
  public DateTimeOffset? CreatedAt { get; set; }

  /// <summary>
  /// Timestamp
  /// </summary>
  [JsonConverter(typeof(UnixTimestampConverter))]
  [System.Text.Json.Serialization.JsonPropertyName("updated_at")]
  public DateTimeOffset? UpdatedAt { get; set; }

  /// <summary>
  /// The display name of the vendor.
  /// </summary>
  [System.Text.Json.Serialization.JsonPropertyName("display_name")]
  public string? DisplayName { get; set; }

  /// <summary>
  /// Flag indicating whether the vendor is exempt from taxes
  /// </summary>
  [System.Text.Json.Serialization.JsonPropertyName("is_tax_exempt")]
  public bool? IsTaxExempt { get; set; }

  /// <summary>
  /// Notes that are visible to the vendor
  /// </summary>
  [System.Text.Json.Serialization.JsonPropertyName("public_notes")]
  public string? PublicNotes { get; set; }

  /// <summary>
  /// The routing identifier for e-invoicing
  /// </summary>
  [System.Text.Json.Serialization.JsonPropertyName("routing_id")]
  public string? RoutingId { get; set; }
}
